sos/plugins/block.py
Changed the parted command to return data in sectors units
instead of human readable form.
=> [block] Don't use parted human readable output - rhbz #1183770

sos/plugins/manageiq.py
New plugin, loosely based on the script at https://access.redhat.com/solutions/650473 which is being used at the moment when web-based log collection via the appliance's UI is not available.
Instead of globs the plugin uses a list of files that are expected to be in the config/log dirs. These lists of files were generated from a few sample archives that were collected by the script mentioned above, except database configuration files (basically containing database credentials) and subdirs of config. Enabling `--all-logs` turns the log files list into globs to get previously rotated files.
Also: unlike the script, this plugin does not collect general logs (covered by other sos plugins) or PostgreSQL config/logs (covered by the postgresql plugin). As the appliance uses PostgreSQL from SCL, …
=> Initial plugin for CloudForms (ManageIQ) configuration and log collection.

sos/plugins/openshift.py
Obfuscate only the value, not the entire directive and value pair.
Signed-off-by: Timothy Williams <tiwillia@redhat.com>
=> [openshift] Obfuscate only DNS plugin credential values

sos/plugins/networking.py
There are some incompatible changes in nmcli since the release of
NetworkManager >= 0.9.9. In addition, NetworkManager >= 0.9.9 will
use the long names of "nmcli" objects. This is documented in the
following article:
https://wiki.gnome.org/Projects/NetworkManager/nmcli
=> [networking] nmcli incompatiblity issues

sos/plugins/networking.py
The nmcli status would always return 0, nmcli status
is now determined by the output of the command
instead of the return code.
=> [networking] nmcli status is obtained from the output

sos/plugins/__init__.py
Commit f06efd6 removed passing stderr in _collect_cmd_output to
get_cmd_output_now. That prevents passing stderr=False in several
scenarios.
This fix adds the argument to be passed back.
Resolves: #600
=> [plugin] pass stderr through _collect_cmd_output

sos/plugins/openstack_ceilometer.py, sos/plugins/openstack_cinder.py, sos/plugins/openstack_glance.py, sos/plugins/openstack_heat.py, sos/plugins/openstack_horizon.py, sos/plugins/openstack_keystone.py, sos/plugins/openstack_neutron.py, sos/plugins/openstack_nova.py, sos/plugins/openstack_sahara.py, sos/plugins/openstack_swift.py, sos/plugins/openstack_trove.py
- Add a postproc method to ceilometer, cinder, glance, hoirzon and swift.
- Add missing keys to the remaining plugins.
- Modify the regular expression used by all plugins to ignore commented
out keys.
Resolves: #574
Signed-off-by: Lee Yarwood <lyarwood@redhat.com>
=> [openstack] Ensure openstack passwords and secrets are obfuscated.

sos/plugins/sapnw.py
Call methods from the self class within "self." scope.
=> [sapnw] call self methods properly

sos/plugins/openstack_neutron.py
server_auth secrets in /etc/neutron/plugins/ml2/restproxy.ini need to be
obfuscated.
Resolves:  #639
=> [openstack_neutron] obfuscate server_auth in restproxy.ini

sos/plugins/ceph.py
Collect the two directories without some forbidden paths.
Reorder self.add_forbidden_path(..) to have some logical ordering there.
Resolves: #693
=> [ceph] Collect (parts of) /var/lib/ceph and /var/run/ceph

sos/policies/redhat.py
=> [redhat] A managled rhn systemid will crash sosreport.

sos/plugins/ceph.py
Do not collect any keyring files - expand the add_forbidden_path
regular expressions accordingly to cover there filenames like:
/var/lib/ceph/tmp/keyring.mon.magna055
Resolves: #861
=> [ceph] skip collecting of all keyring files

sos/plugins/samba.py
- add output of "testparm -s" (without -v)
- collect winbind log files by default
- collect all logs if --all-logs are given
=> Samba improvements

sos/plugins/virsh.py
When parsing output of "virsh -r *" commands, handle properly cases
when either command fails - do not parse the output then.
Resolves: #997
=> [virsh] Handle properly cases when virsh commands fail

sos/plugins/snappy.py
Adds a new plugin that lists information about snappy, including:
* all installed snaps with version info (snap list --all)
* Snappy's own version info (snap --version)
* status info and logs for the snapd daemon
* List snappy system changes (snap changes)
Signed-off-by: Bryan Quigley <bryan.quigley@canonical.com>
=> [snappy] new plugin to show snappy info

sos/plugins/__init__.py
When the stat is done on a broken symlink, it will return either OSError
or FileNotFoundError. Handle these and report accordingly.
Signed-off-by: Louis Bouchard <louis.bouchard@canonical.com>
=> [plugins] Handle stat errors on missing files

sos/plugins/kernel.py, sos/plugins/powerpc.py
The pstore data should be collected upon sosreport run for all
architecture (currently only enabled in powerpc.py) because the
data there will include any past oops event and/or panic events.
This data would assist diagnosing panics with little other data
available.
Also, the data included is a few kb in size, so it will not add
much size to the output of the report.
Collection of /sys/fs/pstore was previously in plugins/powerpc.py.
I moved it to plugins/kernel.py in order to have it collect for all architectures.
I also opened the Launchpad bug for Ubuntu, but figured I would 
suggest the changes here to help speed up the process.
https://bugs.launchpad.net/ubuntu/+source/sosreport/+bug/1687126
Signed-off-by: Chris Newcomer <chris@thenewcomers.org>
=> [kernel] add /sys/fs/pstore collection for all platforms

sos/plugins/docker.py
The binary name changed from docker.io to docker.
Update config and log file locations.
Signed-off-by: Karsten Graul <kgraul@linux.vnet.ibm.com>
Signed-off-by: Christy Perez <christy@linux.vnet.ibm.com>
=> [docker] Update Ubuntu copy spec

sos/plugins/hardware.py
Collect the entire /sys/class/dmi/id/ directory from the
hardware plugin. Today, this is really the "native" format for
this information, as far as Linux is concerned. The dmidecode
program (which historically at least read the data directly
from firmware tables, as no proc or sysfs interface existed) is
a legacy formatting of this information which we are
unfortunately obliged to keep around a little longer yet, as
many users have grown dependencies on its format.
The data included in this directory is small (about 500 bytes
on my system) and will not have an impact on the time or size
of the report.
Original discussion at:
https://github.com/sosreport/sos/pull/1034
Signed-off-by: David Coronel <david.coronel@canonical.com>
=> [hardware] add /sys/class/dmi/id/*

AUTHORS
We've had a lot of contributions from outside companies, organizations, and
individual contributors. I'd like to update this file to acknowledge those new
contributors and continue to encourage and promote this products ecosystem.
Signed-off-by: Adam Stokes <battlemidget@users.noreply.github.com>
=> [AUTHORS] update authors file with more contributors

.github/PULL_REQUEST_TEMPLATE.md
This includes information for users wishing to submit PR's and is visible during
their creation of the PR. This allows them to validate that they are providing
all necessary requirements prior to submitting and should reduce the amount of
back and forth we do asking users to follow our guidelines.
Fixes #1021
Signed-off-by: Adam Stokes <battlemidget@users.noreply.github.com>
=> [workflow] Add a pull request template

sos/plugins/gluster_block.py
gluster_block plugin collects config and log files related to blocks
Signed-off-by: venkata edara <redara@redhat.com>
---
=> [gluster_block] Added new plugin gluster_block

sos/plugins/mongodb.py, sos/plugins/mysql.py, sos/plugins/openstack_ceilometer.py, sos/plugins/openstack_cinder.py, sos/plugins/openstack_glance.py, sos/plugins/openstack_heat.py, sos/plugins/openstack_horizon.py, sos/plugins/openstack_instack.py, sos/plugins/openstack_ironic.py, sos/plugins/openstack_keystone.py, sos/plugins/openstack_manila.py, sos/plugins/openstack_neutron.py, sos/plugins/openstack_nova.py, sos/plugins/openstack_sahara.py, sos/plugins/openstack_swift.py, sos/plugins/openstack_trove.py, sos/plugins/pacemaker.py, sos/plugins/rabbitmq.py, sos/plugins/redis.py
Add Tripleo Pike opinionated logs paths to be collected
for services, when running in containers. This is a temporary
and will be reworked for Queens, like switching those to syslog
or fluentd shipping logs to Elasticsearch cluster.
Partial bug: https://bugs.launchpad.net/tripleo/+bug/1700909
Related blueprint: https://review.openstack.org/#/c/462900
Signed-off-by: Bogdan Dobrelya <bdobreli@redhat.com>
---
=> [plugins] Tripleo specific containerized services logs

sos/plugins/gnocchi.py, sos/plugins/openstack_glance.py, sos/plugins/openstack_heat.py, sos/plugins/openstack_instack.py, sos/plugins/openstack_ironic.py, sos/plugins/openstack_keystone.py, sos/plugins/openstack_neutron.py, sos/plugins/openstack_nova.py
With Tripleo Pike the default ENV changed from OS_TENANT_NAME to
OS_PROJECT_NAME. The commands of the openstack plugins against
the env should run when either OSP_TENANT_NAME or OS_PROJECT_NAME
is set.
Signed-off-by: Martin Schuppert mschuppe@redhat.com
---
=> [openstack plugins] run openstack command when correct ENV is set

man/en/sosreport.1
Fix small typo in the chroot section of the man page (alwyas -> always)
Fixes #1035
Signed-off-by: Adam Stokes <battlemidget@users.noreply.github.com>
=> [man/sosreport] fix typo in chroot description

sos/plugins/openstack_instack.py
This is attempt number two to add the tripleo-ui logs. The first one is #1042. The stdout streaming for `openstack object save` has been [merged](https://review.openstack.org/#/c/476199/) upstream.
We're using the "openstack" command to stream the ui log file to stdout.
Signed-off-by: Honza Pokorny <honza@redhat.com>
---
=> [tripleo] Add ui logs

sos/plugins/docker.py
"containers" is an unknown variable, "insp" is the correct one
Resolves: #1148
---
=> [docker] fix copy&paste error in a for cycle

sos/plugins/etcd.py
catch exception when etcd package isnt installed and we inspect its
version
Resolves: #1159
---
=> [etcd] dont traceback when etcd package isnt installed

sos/plugins/pcp.py
add_copy_spec must be called to files and not dirs, to apply sizelimit
Resolves: #1187
---
=> [pcp] really apply sizelimit to logs collected

sos/plugins/rabbitmq.py
Use do_file_sub() to mask the default password in
the config file /etc/rabbitmq/rabbitmq.conf, to resolve
#840.
---
=> [rabbitmq] Mask default password in rabbitmq.conf

sos/plugins/grub2.py
Newer Fedora systems, grub2 package is replaced by grub2-common
that needs to enable grub2 plugin by default as well.
Additionally, collect /boot/loader/entries with boot list entries.
Resolves: #1543
---
=> [grub2] Enable plugin by grub2-common package also

sos/plugins/xfs.py
xfs_admin is called with argument of mounting point while it accepts
device name.
Resolves: #1610
---
=> [xfs] call xfs_admin on device name

man/en/sosreport.1, sos/__init__.py, sos/plugins/__init__.py, sos/plugins/docker.py, sos/plugins/npm.py, sos/plugins/unpackaged.py, sos/sosreport.py, tests/option_tests.py, tests/plugin_tests.py
Predicates add a new facility to the `Plugin` class that allow file, command, and string collection to be overridden (skipped) based on the predicate's value, without the need for conditional code in plugins themselves.
This is useful since it allows collection gating to be controlled from both within and outside the plugin; for example, implementing a global `--dry-run` mode (a long standing feature request previously needing a great deal of conditionals) becomes relatively trivial.
The current implementation allows collection to be gated based on the presence of kernel modules, running services, or the global `--dry-run` command line argument.
Plugins may define their own predicates, and pass them to methods as appropriate, or they may specify a default predicate (or a default command …
=> [Plugin] Add SoSPredicate and predicates infrastructure

sos/plugins/amazon.py, sos/policies/amazon.py, sos/policies/redhat.py
Adds a policy for Amazon Linux. As Amazon Linux is a RHEL clone, it
inherits from the base RedHatPolicy and uses the RedHatPlugin tagging
class.
Fixes: #1563
---
=> [amazon] Add Amazon Linux policy

sos/plugins/katello.py
Newer katello versions deploy certs for qpid to
/etc/pki/pulp/qpid/client.crt certs instead of
/etc/pki/katello/qpid_client_striped.crt .
Sosreport should use either of the location that exists, to successfully
run few qpid-stat commands.
Resolves: #1680
---
=> [katello] support both locations of qpid SSL certs

sos/plugins/__init__.py
Fix pep8 issues from increasing indentation.
---
=> [pep8] Fix E501 line too long

sos/plugins/gluster.py
Traversing statedump dir for statedump files must skip
subdirectories (where the dump files won't appear).
Resolves: #1812
---
=> [gluster] process files only from a statedump dir

sos/plugins/__init__.py
The check in `Plugin.test_predicate()` relies on a 'is not None' test,
which on py2 invokes a call to `SoSPredicate.__nonzero__()` which in
turns runs our evaluation of the predicate. On py3 however, this test is
an explicit check to see if the object is `NoneType`. As such,
`__nonzero__()` never runs and the predicate defaults to always
evaluating ad `True`. This effectively removed any gating for command
execution on py3.
By overriding `SoSPredicate.__bool__()` to wrap `__nonzero__()` we can
ensure that predicate evaluation is performed properly on both py2 and
py3 runtimes.
Closes: #1839
Resolves: #1840
--- …
=> [Predicate] Override __bool__ to allow py3 evaluation

sos/plugins/__init__.py, sos/plugins/kernel.py, tests/plugin_tests.py
Fix several aspects of path handling that affect container environments using an alternate sysroot (`-s/--sysroot`):
* Invalid handling of symlink and directory paths, leading to `/host` paths appearing in the archive
* Incorrect  {strip,join}_sysroot() use in `_do_copy_path()` and `_is_forbidden_path()` leading to `/host` paths leaking into the archive and mis-blacklisting of plugin paths
* Forbidden path glob styles in the `kernel` plugin that conflict with the change to forbidden path checking in #1695 that cause forbidden paths to be incorrectly added to the archive
This addresses current and urgent issues that make sos unusable in this environment: further problems may exist (especially in the `FileCacheArchive` link follow-up handling used when intermediate path components contain …
=> [Plugin, kernel] interim sysroot fixes

sos/plugins/__init__.py, sos/policies/__init__.py
This commit makes two changes to how sos deals with kernel modules and
their state during a run of sosreport.
First, no longer call `lsmod` for every individual plugin during its
enablement check. Instead, call `Policy.lsmod()` only once during
`load_plugins()` before we begin iterating over the plugins, and save
that information as a policy class attr.
Second, have `Plugin.is_module_loaded()` check for kmod presence in the
saved policy class attr for kernel_mods, rather than checking through
`/proc/modules`. Have the plugin enablement checks now also use
`is_module_loaded()` to standardize with how `SoSPredicate`s are
checked.
Note that this change results in a significant performance increase for
sos initialization times in a RHEL 7 container.
Resolves: #1854
Signed-off-by: Jake …
=> [Plugin|Policy] Only call lsmod once and standardize kmod checks

man/en/sosreport.1
In #1435, --allow-system-changes option was added that is documented
in sosreport --help but not in manpages.
Resolves: #1850
---
=> [man] describe --allow-system-changes

sos/plugins/foreman.py
Due to a change in foreman DB scheme, we must explicitly cast
dynflow_execution_plans.uuid as a varchar since foreman-tasks
0.15.5 .
The explicit casting works well on older versions as well.
Resolves: #1882
---
=> [foreman] cast dynflow_execution_plans.uuid as varchar

sos/plugins/foreman.py
When foreman stores tens to hundreds of thousands of tasks, default
sizelimit causes the dynflow* or foreman_tasks_tasks files are truncated.
Let increase the sizelimit to 100MB.
Resolves: #1899
---
=> [foreman] increase sizelimit for tasks export

sos/policies/__init__.py
Wraps naked opens for `json.load()` calls in `with` statements to ensure
the file object gets closed properly.
Closes: #1322
Resolves: #1902
---
=> [Policy] Wrap json.load() in with clause

sos/plugins/kubernetes.py
Two patch set that first adds collection of `describe node <node>` output for each node returned by `get nodes`. Secondly, for RH OCP installations, rather than using `kubectl` with an updated config file, use the existing `oc` binary that performs the wrapping. This will allow us to be completely sure that the information collected by sos is the same information that would be seen when an end user runs the same commands manually.
---
=> [kubernetes] Add detailed node information and use oc when available

sos/policies/__init__.py, tests/option_tests.py, tests/plugin_tests.py
Commit 285873a introduces a regression in the performance of
LinuxProfile class initialisation:
commit 285873a4f753822a88d475a1b030ab622bf4c72e
Author: Bryan Quigley <bryan.quigley@canonical.com>
Date:   Tue Feb 11 15:03:16 2020 -0800
[policies] Detect systemd use instead of hardcoding it
All the patch does is to switch from testing self.init to
determine whether to use the SystemdInit() class or the
basic InitSystem() one, to looking for '/run/systemd/system'
in the file system.
This has more broad side effects than it might seem since
the test suite uses LinuxPolicy() as a mock policy object
for a large number of tests. Since SystemdInit() calls out
to systemctl to obtain the state of the init system this
both increases the run time for the tests and causes high
resource use in systemd …
=> [policies] fix LinuxPolicy performance regression (test suite)

sos/report/plugins/pci.py
It was reported that certain arches may create subdir structures under
/proc/bus/pci differently than others - most notably that the first
device subdir could be '0000:00' instead of just '00'.
Rather than chase these different layouts, update the gating check for
running `lspci` commands to being that /proc/bus/pci exists and it has
more than just the `devices` file present, as this file may be present
but empty when nothing else exists under `/proc/bus/pci`.
Resolves: #2138
---
=> [pci] Update gating for lspci commands

sos/report/plugins/autofs.py
This patch adds scrubbing of plain text password
from the output of `automount -m` command.
Before Patch :
test | -fstype=cifs,username=user,password=pass //server/sambashare
After Patch :
test | -fstype=cifs,username=user,password=**** //server/sambashare
Resolves : #2165 
Signed-off-by: Rohan Sable <rohanjsable@yahoo.com>
---
=> [autofs]: obsfucate password in `automount -m` cmd

sos/report/plugins/process.py
2-commit patchset that:
1. Drops `-b` per #2352 and adds a timeout to those `lsof` commands as a safeguard
2. Consolidates 2 duplicate `ps` calls to get some headway on #1979 
---
=> [process] Drop -b and consolidate duplicate calls

sos/policies/__init__.py
This is a backport of #2368 for the legacy-3.9 branch.
It was found that some implementations will return a 530 rather than a
503 as the more specific error for incorrect passwords. Handle this
error code explicitly, and then also add a catch-all for any other
ftplib errors that may get raised.
Resolves: #2369
---
=> [Policy] Backport: Handle additional FTP authentication issues

sos/report/plugins/virtwho.py
We can ignore .* at the start of a RE.
Resolves: #2527
---
=> [virtwho] improve regexp processing performance on huge lines

sos/report/plugins/block.py, sos/report/plugins/kernel.py, sos/report/plugins/snapper.py
This patch is to update kernel plugin to collect
page allocation failure info
Signed-off-by: Mamatha Inamdar mamatha4@linux.vnet.ibm.com
- [x ] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [ x] Is the subject and message clear and concise?
- [ x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [ x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ x] If this commit closes an existing issue, is the line `Closes: #ISSUENUMBER` included in an independent line?
- [ x] If this …
=> [kernel] Collect kernel log for page allocation failure

sos/archive.py, sos/policies/__init__.py, tests/report_tests/compression_tests.py, tests/sos_tests.py, tests/unittests/archive_tests.py
As sos is now python3-only, we can avoid shelling-out to compression
utilities like `xz` or `gzip`, and instead use the method provided by
the built-in `tarfile` module.
Resolves: #2523
---
=> [archive] Don't shell out for compressing the archive

sos/report/plugins/convert2rhel.py
Fixes the definition of `packages` and `profiles` within the plugin to
be tuples.
Resolves: #2537
---
=> [convert2rhel] Fix packages and profiles attrs as tuples

.cirrus.yml
Modifies the cirrus configuration to enable auto-cancellation of jobs
for the master branch (it is already enabled for PR branches by
default). This will prevent batch merges from kicking off a test job for
each merge. While it may arise that two or more independent commits that
pass testing on their own branches combine to form an unexpected
failure, this possibility seems remote for sos.
This is a cost saving decision - currently for each commit to master we
are spinning up a minimum of 13 VMs, which can very quickly snowball if
we do multiple merges in a short amount of time (which is historically
how the project does merges).
Second, modify the `gce_instance` fields in the cirrus config to use
pre-defined machine types, as these match our current "custom"
specifications already, and …
=> [cirrus] Enable auto-cancellation of jobs and specify type for GCE

sos/report/plugins/auditd.py
This commit captures the file audit-stop.rules, and
directory plugins.d.
Resolves: #2538 
---
=> [auditd] Capture missing files in /etc/auditd/

sos/collector/__init__.py, sos/policies/distros/__init__.py
While providing case id is fully optional, the current phrasing
might be insintepreted it is mandatory.
Resolves: #2542
---
=> [policy,collector] State explicitly that caseid is optional

man/en/sos-report.1, sos/collector/__init__.py, sos/policies/distros/__init__.py, sos/policies/distros/redhat.py, sos/policies/distros/ubuntu.py, sos/report/__init__.py
First, corrects the internal language used around HTTPS uploads.
Second, adds `--no-ssl-verify` to skip ssl verification for HTTPS uploads
---
=> [Policy] Correct internal HTTPS language and add SSL verify toggle

man/en/sos-report.1
Updates the language in the manpage to clarify that in order to enable
additional plugins outside of a profile when a profile is specified,
that users must use `-o` instead of `-e`.
Remove the 'current profiles' list from the manpage as it is outdated
and it is better to refer users to the list reported by the local
installation.
Closes: #504
Resolves: #2543
---
=> [docs] Clarify profile in manpage and how to enable further plugins

sos/report/plugins/networking.py
As netstat command is being deprecated,
we need nstat as an alternative to "netstat -s".
Signed-off-by: Seiichi Ikarashi <s.ikarashi@fujitsu.com>
---
=> [networking] Add nstat command support

sos/report/__init__.py, tests/report_tests/exception_tests.py
Specifying a non-existing plugin to skip is no longer considered a fatal
error. This was previously in place, in part, for third party utilities
calling sos to ensure adherence to known plugins. However, since
`collect` has been integrated into sos natively, this is far less of a
concern.
Specfying non-existing plugins will now only generate a warning message
for plugins wanting to be skipped (`-n`). If non-existing plugins are
specified for enablement via `-e` or `-o`, that will still generate a
fatal error.
Closes: #537
Closes: #1723
Resolves: #2517
---
=> [report] Do not fail on skipping non-existing plugins

sos/report/plugins/networking.py
tc filter show must be called with "ingress" subcommand, otherwise
it shows nothing.
Resolves: #2550
---
=> [networking] call tc filter show with mandatory ingress subcommand

sos/report/plugins/__init__.py, sos/report/plugins/boot.py, sos/report/plugins/crio.py, sos/report/plugins/docker.py, sos/report/plugins/filesys.py, sos/report/plugins/logs.py, sos/report/plugins/networking.py, sos/report/plugins/podman.py, sos/report/plugins/process.py, sos/report/plugins/rpm.py, sos/report/plugins/selinux.py, tests/report_tests/command_priority_tests.py, tests/sos_tests.py
Adds a `priority` parameter to `add_cmd_output()` and `add_journal()`,
that can be used to influence the order in which commands are executed
within a plugin. This allows for plugins to specify that long-running
commands should be run last, regardless of where in the plugin those
commands are defined.
As part of accounting for this, minor fixups in the evaluation of run
times for individual commands and how those are reflected in the
report's manifest are included.
Assigns new `priority` values to known long running commands, to ensure
those commands run last in their respective plugins' execution.
Finally, adds a new test to ensure all of this is and remains working.
--- …
=> [Plugin,plugins] Allow plugins to influence command execution order

tests/report_tests/basic_report_tests.py, tests/report_tests/smoke_tests.py, tests/sos_tests.py
Improves error reporting for failed sos commands by logging stderr (or
stdout if stderr is not populated) to the console, which was previously
being truncated by the builtin error handling of avocado. Printed output
is limited to the last 8k to avoid dumping several MBs at a time for
scenarios such as timeouts where command failure may generate
significant logging prior to failing.
Included with this are 2 minor changes to existing tests. First, remove
verbose output from the expected plugins test to reduce otherwise
irrelevant output for command failures. Second limit the number of
plugins run for the LogLevelTest, both to reduce overall run time for a
test where we aren't testing specific plugins and to improve readability
of failures for such a test.
Resolves: #2556
Signed-off-by: Jake …
=> [tests] Improve failed command reporting in test output

sos/report/plugins/candlepin.py
The file contains important config about internal candlepin broker
routing.
Also, apply scrubbing of two passwords on a single line / in one URI.
Resolves: #2558
---
=> [candlepin] collect /etc/candlepin/broker.xml

sos/archive.py, tests/vendor_tests/redhat/rhbz1965001.py
A supplement of #1399 fix, now also for adding strings or special
device files.
Resolves: #2560
---
=> [archive] skip copying SELinux context for /proc and /sys everytime

sos/report/plugins/juju.py
With --all-logs, it could potentially collect the kvms that are created
by juju, and hence the sos report size could be significant. This
change will ensure that the kvm images are not collected as part of sos
report.
Closes: #2563
---
=> [juju] Don't allow collection of kvm

man/en/sos-report.1, sos/collector/__init__.py, sos/policies/distros/__init__.py, sos/policies/distros/redhat.py, sos/report/__init__.py
This patchset adds support for SFTP uploads, using `pexpect` to handle the connection, auth, and upload monitoring.
Further, the `RedHat` policy is updated to drop the legacy FTP server as a fallback and instead use the new SFTP server if there are any issues using the RH Customer Portal, or if credentials are not supplied.
A new `--upload-protocol` option is added which can be used to skip protocol determination and use a specific protocol. In the case of RHEL systems, this means  using `--upload-protocol sftp` will entirely skip any attempts to use the customer portal even if valid credentials are supplied.
---
=> [Policy,redhat] Add support for SFTP uploads, replace legacy RH FTP fallback

man/en/sos-collect.1, sos/collector/__init__.py, sos/collector/clusters/__init__.py, sos/collector/clusters/kubernetes.py, sos/collector/clusters/ocp.py, sos/collector/sosnode.py, sos/policies/distros/__init__.py, sos/policies/distros/redhat.py, sos/policies/runtimes/__init__.py
This patchset adds several options to facilitate pulling an image that does not already exist on containerized hosts when those hosts need to provide authentication to the registry where the image will be pulled from. Fixes some cases around sos inspection on containerized hosts.
Additionally, adds a cluster profile for OpenShift Container Platform v4.
---
=> [collect|ocp] Add an OCP4 collect profile, add registry auth options, improve containerized execution

tests/report_tests/encryption_tests.py, tests/sos_tests.py
Adds two test cases for using `--encrypt-pass`; one with just the bare
option and another in conjunction with `--clean` to ensure both can be
used in the same execution.
Resolves: #2566
---
=> [tests] Add test for using `--encrypt-pass`

sos/report/plugins/block.py
This patch captures information from loop devices
via 'losetup -a' and the content of
/sys/block/loopN/loop/ directory.
Resolves: #2570 
---
- [] If this commit closes an existing issue, is the line `Closes: #ISSUENUMBER` included in an independent line?
=> [block] Add information about loop devices

sos/report/plugins/sssd.py
We have reports that sssd logs are not
collected, when we investigated
we found associate wants to collect
sssd related logs also when only
sssd-common package is installed.
We got this confirmed by sbr-idm.
Resolves: #2571
---
=> [sssd] sssd plugin when sssd-common

.cirrus.yml
Updates the testing matrix for F34, dropping F32.
Resolves: #2574
---
=> [cirrus] Update Fedora testing for F34

sos/collector/__init__.py, sos/collector/clusters/__init__.py, sos/collector/clusters/kubernetes.py, sos/collector/clusters/ovirt.py, sos/collector/clusters/pacemaker.py, sos/collector/clusters/satellite.py
This commit begins the deprecation of the use of `master` in favor of
`primary`. For this initial step, `sos collect` will deprecate the
`--master` option and print a notice whenever it is used. This option is
being replaced by `--primary` with aliases `--manager` and
`--controller`.
This deprecation will last through 4.2, with `--master` being removed in
4.3.
Additionally, the `exec_master_cmd()` method for cluster profiles has
been similarly deprecated in favor of `exec_primary_cmd()`, with a
deprecation note logged whenever a cluster profile uses the former
method.
The internal assignment of the `SoSNode` object as `master` remains
for now, as this initial step is to deprecate the user-visible bits. By
full removal of `--master` in 4.3, these internal assignments should all
be changed …
=> [collect] Deprecate 'master' in favor of 'primary'

sos/cleaner/__init__.py
Fixes an issue where empty lines would be stripped from files that have
other obfuscations in them. Those empty lines may be important for file
structure and/or readability, so we should instead simply not pass empty
lines to the parsers rather than skipping them wholesale in the flow of
writing obfuscations to a temp file before replacing the source file
with a potentially changed temp file.
Resolves: #2562
---
=> [cleaner] Don't strip empty lines from substituted files

sos/report/plugins/__init__.py, sos/report/plugins/ceph.py, sos/report/plugins/clear_containers.py, sos/report/plugins/cockpit.py, sos/report/plugins/crio.py, sos/report/plugins/cups.py, sos/report/plugins/etcd.py, sos/report/plugins/fwupd.py, sos/report/plugins/gdm.py, sos/report/plugins/lightdm.py, sos/report/plugins/maas.py, sos/report/plugins/peripety.py, sos/report/plugins/rasdaemon.py, sos/report/plugins/snap.py, sos/report/plugins/stratis.py, tests/report_tests/plugin_tests/defaults.py, tests/sos_tests.py
Adds automatic collection of journals for any service defined in a
plugin's `services` tuple, if that service exists on the system.
Updates several plugins to define a `services` tuple in place of
manually calling `add_journal()` (and as a bonus, removing redundant
`add_service_status()` calls that are already performed based on the
tuple).
Additionally, add an appropriate tag to each `add_journal` call for
easier collection lookup in the manifest.
Resolves: #2579
---
=> [Plugin] Add default journal collection for Plugin services

man/en/sos-clean.1, man/en/sos-collect.1, man/en/sos-report.1, man/en/sos.1
Unify capitalisation of name and synopsis.
Add references to sos.conf to SEE ALSO of all binaries.
Resolves: #2581
---
=> [man] unify some syntax in manpages

sos/cleaner/__init__.py, sos/cleaner/obfuscation_archive.py
As we did with `report` in #2523, update `clean` to use the built-in
compression capability of TarFile to re-compress unpacked archives.
Resolves: #2576
---
=> [cleaner] Use built-in TarFile compression functionality

sos/plugins/pulpcore.py
The command also prints content of /etc/pulp/settings.py
where we need to also obfuscate the SECRET_KEY and PASSWORD values.
Related: #2583
Resolves: #2584
---
=> [pulpcore] obfuscate two passwords from 'dynaconf list'

sos/report/plugins/vmware.py
Updates the `vmware` plugin for more current collections based on the
use of the `open-vm-tools` package which is the current recommendation
from VMware to use instead of the legacy VMWare-Tools package.
Command collections are expanded and updated to use
`vmware-toolbox-cmd`.
Closes: #2580
Resolves: #2582
---
=> [vmware] Update command and log collections

sos/report/__init__.py
In the "top-level" `ThreadPoolExecutor` used for threading plugin
execution, increase readability and reliability by wrapping it in a
`with` context manager, so that the pool's cleanup is run in all
situations explicitly.
This is a continuation of #2294, bringing it up to date with the current
state of the project and iterating over the plugin list as a discreet
unit rather than individual plugins.
Closes: #2294
Resolves: #2578
Co-authored-by: Erik Bernoth <ebernoth@redhat.com>
---
=> [report] Increase readability and reliability of top-level ThreadPool

sos/report/plugins/__init__.py, sos/report/plugins/openstack_cinder.py, sos/report/plugins/openstack_glance.py, sos/report/plugins/openstack_heat.py, sos/report/plugins/openstack_ironic.py, sos/report/plugins/openstack_manila.py, sos/report/plugins/openstack_nova.py, sos/report/plugins/openstack_placement.py, sos/report/plugins/ovn_central.py, tests/unittests/conformance_tests.py
Adds an enablement trigger tuple, `containers`, that can be used to enable plugins based on the presence of a running container matching any of the names or regexes in the tuple.
Also updates several plugins to make use of this new enablement tuple.
---
=> [Plugin] Add container enablement trigger

.github/PULL_REQUEST_TEMPLATE.md
While using Github merging we don't need to track Resolves to
close PRs anymore. If existing (and not the PR currently on)
it still makes sense to use Resolves though.
Signed-off-by: Bryan Quigley <code@bryanquigley.com>
---
=> [github] Merge Closes and Resolves lines

sos/cleaner/__init__.py, sos/cleaner/mappings/__init__.py, sos/cleaner/mappings/hostname_map.py, sos/cleaner/obfuscation_archive.py, sos/cleaner/parsers/__init__.py, sos/cleaner/parsers/hostname_parser.py, sos/cleaner/parsers/keyword_parser.py, sos/cleaner/parsers/username_parser.py, sos/collector/__init__.py, sos/collector/clusters/__init__.py, sos/collector/clusters/ocp.py, sos/collector/sosnode.py
This patchset touches several aspects of `collect` and `clean` that do not solely related to OCP or the (new) cluster profile, however the enhancements added we discovered as needed (or needed to be improved/fixed) as part of further enhancements to the OCP profile. Normally, these would be broken out into separate PRs, however given how linked these are to the ultimate changes being made for OCP collections and cleaning, it would be drastically higher overhead to split these out.
Of particular note, is the fix for not clobbering sos command options between nodes, which was inadvertently using a shared variable scope rather than private copies for each node.
Further, this includes allowing cluster profiles to individually set master/worker options, command env vars, and vastly improved …
=> [collect,clean,ocp] Enhance OCP cluster collection and archive cleaning

sos/report/__init__.py
Since --build does not produce a tarball, we cannot encrypt any
collections. However, the encryption options are set in the global
option group so we cannot add a report-only option to that mutex group.
Instead, print a warning informing the user of this limitation.
Closes: #2568
---
=> [report] Log a warning message when trying to encrypt with --build

sos/report/plugins/pulpcore.py, sos/report/plugins/rhui.py
Add a new/revoked plugin for RHUI (newly based on python3 and pulp-3).
Edditionally, collect /etc/pki/pulp certificates except for RSA keys.
Resolves: #2590
---
=> [rhui] add plugin to RHUI

sos/report/plugins/libvirt.py
We are very interested in gathering data about dnsmasq processes that libvirt always spawns for every network.
This will add those kind of configuration files, which can tell us how DNS is actually configured in the internal libvirt networks.
---
An example artifact:
[sosreport.zip](https://github.com/sosreport/sos/files/6701370/sosreport.zip)
=> [libvirt] Gather libvirt's dnsmasq configuration files

sos/report/plugins/openstack_designate.py
Use designate-manage to grab the current pools from designate, in
case they differ from the pools stored in pools.yaml
Signed-off-by: Michael Chapman <woppin@gmail.com>
---
=> [openstack_designate] Add current pool configuration

sos/report/plugins/date.py, sos/report/plugins/systemd.py
Changes which collection the `date` root symlink points to. It will now
reference the `timedatectl` command run via the `systemd` plugin, as it
provides more complete and accurate information.
Closes: #2559
---
=> [date,systemd] Switch 'date' root symlink to timedatectl

.cirrus.yml
Updates the image used for CentOS Stream 8 testing to the latest release
for that distro.
---
=> [cirrus] Update CentOS Stream 8 image in GCE testing

sos/report/plugins/yum.py
Like we did in #969 for `dnf`, fix a potential issue where we would
generate a traceback in the plugin when `yum history` is empty.
---
=> [yum] Fix potential traceback when yum history is empty

sos/report/plugins/__init__.py
Just making the code more robustness, it could be dangerous to
set pred = None and then potentially call log_skipped_cmd that
expects "pred" of SoSPredicate type.
Currently such a call flow can not happen, but it is worth to
make the code more robust for potential future changes.
Resolves: #2601
---
=> [plugins] Set default predicate instead of None for robustness

.cirrus.yml, sos/cleaner/__init__.py, sos/cleaner/parsers/__init__.py, sos/cleaner/parsers/mac_parser.py, tests/cleaner_tests/full_report_run.py, tests/sos_tests.py
Adds a full `sos report --clean` execution test, that is one that does not limit what the report is gathering like the current tests do. Then, inspect the contents of the archive more deeply, ensuring the local hostname and primary IP address do not appear anywhere within the archive. 
Also includes two fixes found during test case development. First, catch a json decoding exception like we do a non-existing file exception. Second, allow test cases to define their own timeout if needed, still defaulting back to 300 seconds.
---
=> [tests] Add full execution clean test

sos/report/plugins/mysql.py
- All configuration files from /etc/mysql/
- Default error log path: /var/log/mysql/error.log
- Alternative data directory location /var/lib/percona-xtradb-cluster
- gvwstate.dat for galera debugging
- Update the various server package names (though all seem to depend on
mysql-common anyway)
Signed-off-by: Trent Lloyd <trent.lloyd@canonical.com>
---
=> [mysql] Update collection paths for Debian/Ubuntu

sos/collector/sosnode.py
Fixes an issue where options provided for `skip-commands` and
`skip-files` were not properly formatted, thus causing an exception
during the finalization of the node's sos command.
---
=> [sosnode] Properly format skip-commands and skip-files on nodes

sos/report/plugins/kata_containers.py
Kata Containers 1.x, which is the base for this plugin, has reached its
EOL on May 12th 2021*.
Based on that, let's update the sos plugin to match the current Fedora
RPM (kata-containers, instead of kata-runtime), and set the identifiers
we'd be interested in, which are the crio and containerd ones.
Currently, kata-containers can only be used in the kubernetes world and
it'll always be spawn either by CRI-O or containerd, and then it'll log
to the journal using their identifier.
*: https://medium.com/kata-containers/about-kata-containers-releases-8b3d91d1166e
Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>
---
=> kata_containers: Update to the 2.x release

sos/report/plugins/foreman.py, sos/report/plugins/foreman_installer.py, sos/report/plugins/foreman_proxy.py, sos/report/plugins/puppet.py, tests/product_tests/foreman/foreman_tests.py
Most of foreman plugin is not applicable to a smart proxy, so
split that functionality to a separate plugin.
Resolves: #2546
Closes: #2423
---
=> [foreman-proxy] split the plugin from foreman

sos/report/plugins/openvswitch.py
Updates PR #1820 to bring in additional command collection for the
openvswitch plugin. Note that the `ovs-appctl` command added in that
original PR is not brought forward, as subsequent changes since that PR
have added an iterative collection of that command.
Resolves: #1820
---
=> [openvswitch] Add collection for OVS datapaths

sos.spec
Removes an old dependency on python-libxml2 that has not been required
for some time.
---
=> [build] Remove old libxml2 dependency

sos/report/plugins/__init__.py
Set default value for the attribute 'changes' when_add_cmd_output is
called without that argument.
Further, add reason to "skipped command" log due to --dry-run.
Resolves: #2626
---
=> [report] Improve logging skipped commands during dry run

sos/report/plugins/migration_results.py
A new tiny plugin independent on leapp and convert2rhel is proposed.
It should collect /etc/migration-results with info about RHEL
conversions and upgrades, whenever the file is present.
Resolves: #2627
Relevant to: rhbz#1959598
---
=> [MigrationResults] collect info about conversions and upgrades

tests/vendor_tests/redhat/rhbz1928628.py
Avocado will, by default, use the "recursive" behavior when looking
for tests.  It means that the class hierarchy will be crawled
recursively, until, for "avocado-instrumented" tests, the top-most
parent "avocado.Test" is found.
When the "enable" behavior is activated, it forces the class to be
considered one containing avocado-instrumented tests, but, it disables
the recursive behavior and only the tests local to that specific class
are found.
Signed-off-by: Cleber Rosa <crosa@redhat.com>
---
=> [tests] use Avocado "recursive" behavior by default

.packit.yaml
Updates the packit configuration to enable GH comment notifications, as
well as expand the architectures the COPR RPMs are built for.
---
=> [packit] Update packit configuration

sos/component.py, sos/policies/distros/redhat.py
Adds an alert suppression for 2 LGTM.com alerts. First, one involving
the overriding of `load_options()` when we're initializing the
placeholder component for `collect` on systems that do not have the
proper support for it.
Second, an alert about logging sensitive data when we are reporting the
temporary anonymous user used to leverage the RH SFTP server when the
user does not provide credentials.
---
=> [lgtm] Suppress false positive alerts

sos/cleaner/__init__.py, sos/cleaner/parsers/__init__.py, sos/cleaner/parsers/hostname_parser.py, sos/cleaner/parsers/ip_parser.py, sos/cleaner/parsers/keyword_parser.py, sos/cleaner/parsers/mac_parser.py, sos/cleaner/parsers/username_parser.py, tests/unittests/cleaner_tests.py
Instead of re-reading the mapping file for each parser, read it once and
store the contents, then hand those contents over to each parser.
This allows us to side-step handling the same exception for malformed
config files over and over for each parser loaded.
---
=> [cleaner] Read map file only once for parsers

.cirrus.yml, MANIFEST.in
First, adds a MANIFEST.in file for distutils to reference, so that we
can easily ensure that the .po files are included in any manual build
from the git checkout.
Second, add a cirrus task to ensure that basic rpm builds from the git
checkout can be done by the user.
---
=> [build,tests] Include .po files for manual builds, add cirrus test

sos/cleaner/__init__.py, sos/cleaner/parsers/__init__.py, sos/cleaner/parsers/username_parser.py
AD/LDAP users are not reported into `lastlog` generally, however they
are reported in `last`. Conversely, `last` does not report local users
who have not logged in but still exist.
In order to obfuscate both kinds of users, we need to look at both
sources.
For this, first allow parsers to specify multiple prep files. Second,
update the username parser to search through all `lastlog` collections
as well as the `last` collection.
Also includes a small update to the username parser's prep loading logic
to ensure we are iterating over each username discovered only once.
---
=> [username parser] Load usernames from `last` for LDAP users

man/en/sos-report.1, sos/collector/__init__.py, sos/report/__init__.py, sos/report/plugins/__init__.py, sos/report/plugins/conntrack.py, sos/report/plugins/ebpf.py, sos/report/plugins/networking.py, sos/utilities.py, tests/unittests/plugin_tests.py
Adds a new `--namespaces` option that controls the number of namespaces to iterate over for anything that calls `get_network_namespaces()` (and in the future, any other `get_*_namespaces()` methods that might be added).
This global option may be overridden by plugin specific options, and plugin options are added for the `ebpf` and `conntrack` plugins. 
Finally, fixup the display of options with magic/non-standard defaults in `--list` output.
---
=> [report,collect,Plugin] Add global namespaces options

sos/cleaner/obfuscation_archive.py, tests/cleaner_tests/existing_archive.py, tests/cleaner_tests/full_report_run.py, tests/sos_tests.py
This commit inserts a nested ProcessPoolExecutor into the extraction
workflow for archives that are being obfuscated by `sos clean`.
Previously, the extraction was handled inside the same thread as the
rest of the obfuscation routines for each archive. However, it has been
found that when very large archives are manipulated concurrently,
performance can take a massive hit during the extraction process. This
is due to GIL limitations.
In this aspect 'very large archives' implies many tens of thousands of
files - e.g. 50K+. Because TarFile uses a 10K internal buffer, we end up
spinning a lot of time processing each file via the interpreter.
By shunting each extraction off into a new process space, we can avoid
the GIL issues altogether.
--- …
=> [cleaner] Use a nested ProcessPoolExecutor for extraction

sos/component.py, tests/test_data/etc/sos/extras.d/sos_clean_config.conf, tests/test_data/etc/sos/sos.conf, tests/test_data/var/log/clean_config_test.txt, tests/vendor_tests/redhat/rhbz1950350.py
When a `report` or `collect` run would use `--clean` or `--mask` to do
in-line obfuscation of collected reports, sos would not read the config
section for clean - it would only be read if `sos clean` was called
directly. As such, users would need to manually specify config file
values for each run.
Alleviate this gap by reading the config section for `clean` if either
of the cleaner options are used. Do this before we apply cmdline options
so that we maintain our order of precedence.
Related: RHBZ#1950350
---
=> [sos] Read config section for clean when `--clean` is used

sos/collector/__init__.py, sos/collector/sosnode.py
Fixes the handling of plugin options passed by `sos collect` to each
node by first aligning the SoSOption name to those of `report`
(`plugopts`), and second re-arranges the handling of plugin options and
preset options passed by the user when also using `--only-plugins` so
that the former are preserved and passed only with the `--only-plugins`
option value.
Resolves: #2641
---
=> [sosnode] Fix passing of plugin options when using `--only-plugins`

sos/report/plugins/sapnw.py
This patch solves the situation where the
command:
/usr/sap/hostctrl/exe/saphostctrl
-function ListInstances
returns:
No instances found
And a non-zero return code.
Fixes: RHBZ#1992938
Closes: #2643 
---
=> [sapnw] Fix IndexError exception

.cirrus.yml
Updates the Foreman tests to use new images created for Foreman 2.5.
Additionally, adds an option to the prep script to prevent new Debian
release suite changes from causing the prep scripts to abort the tests.
For out purposes, suite changes are not important during test runs as
these images are built on known versions.
Resolves: #2656
---
=> [tests] Update Cirrus testing for Foreman 2.5

.cirrus.yml, README.md, docs/index.rst, man/en/sos-collect.1, man/en/sos.1, man/en/sos.conf.5, plugins_overview.py, sos.conf, sos/collector/__init__.py, sos/collector/clusters/__init__.py, sos/collector/clusters/ocp.py, sos/collector/clusters/ovirt.py, sos/collector/clusters/satellite.py, sos/collector/sosnode.py, tests/test_data/etc/sos/sos.conf
This commit follows up on the previous changes from #2555 by fully
dropping the `--master` option in favor of `--primary`, `--manager`, and
`--controller`.
Internal references have been updated as well, using the term `primary`
across all instances. Note that within OCP cluster profile, 'primary'
labeling and option setting still relies on the 'master' label/role
reported by the environment, as that remains the term used to identify
such nodes.
Resolves: #2329
---
=> [collect] Drop `--master` and update internal references

sos/collector/__init__.py
Remove the case ID prompt within `collect`, since the one from `Policy`
will always apply. This avoids a double prompt for a case ID if the user
does not originally provide one.
---
=> [collect] Remove double prompt for case ID

sos/report/plugins/udisks.py
This new plugin captures the udisks config
in:
/etc/udisks/
And status and object dump via udisksctl command.
Resolved: #2654 
---
=> [udisks] New udisks plugin

sos/report/plugins/openvswitch.py
OVS has options for the userspace datapath so certain functionality
can use implementations based on SIMD instructions if available.
Add some commands which show the implementations available and used.
Signed-off-by: Kevin Traynor <ktraynor@redhat.com>
---
=> [openvswitch] Get userspace datapath implementations

sos/report/plugins/omnipath_client.py
While omnipath_client plugin is collecting "opacapture",
`depmod -a` command is executed to regenerates some files
under /usr/lib/modules/$kernel.
modules.dep
modules.dep.bin
modules.devname
modules.softdep
modules.symbols
modules.symbols.bin
This patch ensures that the command is only run when
the option --allow-system-changes is used.
Fixes: RHBZ#1998433
Closes: #2662 
---
=> [omnipath_client] Ensure opacapture runs only with allow-system-changes

sos/report/plugins/processor.py
Copy /sys/devices/system/cpu/cpuX with separately applied sizelimit.
This is required for systems with tens/hundreds of CPUs where the
cumulative directory size exceeds 25MB or even 100MB.
Resolves: #2639
Closes: #2665
---
=> [processor] Apply sizelimit to /sys/devices/system/cpu/cpuX

sos/report/plugins/unpackaged.py
When the plugin processes a recursive loop of symlinks, it currently
hangs in an infinite loop trying to follow the symlinks. Use
pathlib.Path.resolve() method to return the target directly.
Resolves: #2664
---
=> [unpackaged] deal with recursive loop of symlinks properly

.cirrus.yml
Avocado has been developing a new test runner (dubbed nrunner) and the
upcoming release 91.0 will activate the new runner as the default one.
While most of the tests and jobs should work under the new runner,
there are a few caveats, and possibly unknown issues.
To avoid regressions in the test execution and CI status, let's pin
the test runner to the known working version.  A switch to use the new
runner may be done as a separate future change after compatibility is
fully investigated and validated.
Reference: https://avocado-framework.readthedocs.io/en/90.0/releases/90_0.html#important-announcement
Signed-off-by: Cleber Rosa <crosa@redhat.com>
---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution- …
=> [tests] Pin avocado test runner to known working version

sos/options.py, sos/report/__init__.py, tests/report_tests/options_tests.py, tests/sos_tests.py, tests/test_data/etc/sos/options_tests_sos.conf
This patchset fixes the issue raised in #2663 by adding an explicit handler for plugopts in the `to_args()` logic used to generate the command line logged for the ending effective options. We need to do this because the way `SoSOptions()` builds from the `arg_defaults` compared to reading config file sections does not work for how we parse the `plugin_options` section, as it ends up updating the `arg_defaults` inadvertently. During testing however, fixing this more generically lead to either command line values for `plugopts` not being honored or the section handling methods breaking. So, I see this as the least bad option.
Additionally, a new test class is added to ensure logging and option handling from config files behaves as we expect it to. To do this, a companion commit that allows …
=> [report,options] Fix reporting of plugopts with effective options message

.cirrus.yml, tests/sos_tests.py
Adds a failure handling to cirrus tasks that actually run sos so that if
an error is encountered in the test suite, the logs from the tests are
uploaded to the GCE cloud storage bucket associated with the GCE sos
project.
Note this initial push includes a temporary commit to force a failure of the stage 1 tasks in order to test this change. Once verified, that commit will be dropped.
---
=> [cirrus] Upload logs from failed tests to GCE storage bucket

sos/report/plugins/firewall_tables.py, sos/report/plugins/firewalld.py
We collect 'nft list ruleset' in both plugins, while:
- nft is not shipped by firewalld package, so we should not collect
it in firewalld plugin
- running the command requires both nf_tables and nfnetlink kmods, so
we should use both kmods in the predicate
Resolves: #2679
---
=> [firewalld] collect nft rules in firewall_tables only

man/en/sos-report.1, sos/report/__init__.py
Add report option `--estimate-mode` to estimate disk space requirements
when running a sos report.
Reasoning for changing some cmdline options when `--estimate-mode` is used:
- `--threads=1` is required to limit disk usage during the estimation and to simplify the calculation
- `--build` enabled as the outcome is rather in UI logs than in packing the (almost empty) tarball; anyway we can agree on any solution here (to optionally pack the almost empty directory, or to delete the tarball/directory (but it contains `sos.log` that can be valuable for understanding of the disk space consumption)
- `--no-postproc` enabled as we dont care about any password obfuscation (in files we will delete either way)
- `--clean` disabled due to the same reason
- `--upload` disabled as a redundant feature …
=> [report] Implement --estimate-mode

sos/report/plugins/subscription_manager.py
As syspurpose utility is being integrated into subscription-manager,
we need to call both legacy and sub-man version of the command.
Resolves: #2681
---
=> [subscription_manager] collect syspurpose data via sub-man

.editorconfig
EditorConfig is fairly editor agnostic and is understood by a wide
range of editors/IDEs [1].
Signed-off-by: Nicolas Bock <nicolas.bock@canonical.com>
[1] https://editorconfig.org/
---
=> Add `editorconfig` for basic editor settings

sos/report/plugins/kernel.py
Kernel 4.20 includes PSI metrics for CPU, memory and IO.
The feature is enabled after adding "psi=1" as
kernel boot parameter.
The information is captured in files
in the directory /proc/pressure.
Closes: #2677
Closes: RHBZ #2002145
---
=> [kernel] Capture Pressure Stall Information

sos/report/__init__.py, sos/report/plugins/__init__.py, sos/report/plugins/jars.py, sos/report/plugins/python.py, sos/report/plugins/unpackaged.py, sos/report/plugins/yum.py, tests/report_tests/plugin_tests/logs.py, tests/report_tests/plugin_tests/string_collection_tests.py, tests/unittests/plugin_tests.py
This commit allows plugins that call `add_string_as_file` to specify if
the string should be written to `sos_strings/$name/` (current behavior)
or if it should be written to `sos_commands/$name/` which may be
desireable for organizational purposes for plugin collections.
`add_string_as_file()` has also been updated to write to a plugin's
manifest section for any files written this way. Accordingly, the method
will now accept a `tags` parameter to add specified tags to the manifest
entry.
Certain plugins directly calling this method have been updated, but the
existing logic to write truncated data to `sos_strings/` remains
untouched, and will not generate manifest entries (as those should
already be handled by the method that trigged the truncated collection).
Signed-off-by: Jake Hunsaker …
=> [Plugin] Improve add_string_as_file collection and manifest recording

setup.py
Adds the newly abstracted `sos.cleaner.archives` package to `setup.py`
so that manual builds will properly include it.
---
=> [build] Add archives to setup.py packages

setup.py, sos/collector/__init__.py, sos/collector/clusters/__init__.py, sos/collector/clusters/jbon.py, sos/collector/clusters/kubernetes.py, sos/collector/clusters/ocp.py, sos/collector/clusters/ovirt.py, sos/collector/clusters/pacemaker.py, sos/collector/clusters/satellite.py, sos/collector/sosnode.py, sos/collector/transports/__init__.py, sos/collector/transports/control_persist.py, sos/collector/transports/local.py
Since its addition to sos, collect has assumed the use of a system
installation of SSH in order to connect to the nodes identified for
collection. However, there may be use cases and desires to use other
transport protocols.
As such, provide an abstraction for these protocols in the form of the
new `RemoteTransport` class that `SoSNode` will now leverage. So far an
abstraction for the currently used SSH ControlPersist function is
provided, along with a psuedo abstraction for local execution so that
SoSNode does not directly need to make more "if local then foo" checks
than are absolutely necessary.
Related: #2668
--- …
=> [collect] Abstract transport protocol from SoSNode

sos/policies/distros/__init__.py, sos/policies/distros/redhat.py, sos/policies/init_systems/__init__.py, sos/policies/init_systems/systemd.py
This commit resolves a situation in which `sos` is being run in a
container but the `SystemdInit` InitSystem would not properly load
information from the host, thus causing the `Plugin.is_service*()`
methods to erroneously fail or return `False`.
Fix this scenario by pulling the `_container_init()` and related logic
to check for a containerized host sysroot out of the Red Hat specific
policy and into the base `LinuxPolicy` class so that the init system can
be initialized with the correct sysroot, which is now used to chroot the
calls to the relevant `systemctl` commands.
For now, this does impose the use of looking for the `container` env var
(automatically set by docker, podman, and crio regardless of
distribution) and the use of the `HOST` env var to read where the host's
`/` filesystem …
=> [Systemd, Policy] Correct InitSystem chrooting when chroot is needed

sos/policies/distros/__init__.py
When prompting for a case id, `Policy` was not properly updating the
option value, only assigning the value to `Policy` which meant that
aspects outside of `Policy` could not always properly reference the
(updated) case id.
Fix this by assigning the case id prompt response back to the case_id
option value. `Policy` still retains a local reference to case_id as
existing logic was setting that based on the (assumed-to-be-updated)
option value, which until this commit would have been superfluous.
Closes: #2707
---
=> [Policy] Fix assignment of case id prompt

sos/report/plugins/foreman.py
Collect foreman-puma-status and 'pumactl [gc-|]stats', optionally using
SCL (if detected).
Resolves: #2712
---
=> [foreman] Collect puma status and stats

sos/report/plugins/insights.py
Collect 'insights-client --test-connection --net-debug' cmdout
with a limited timeout to prevent plugin stuck for too long in case
of a networking/proxy issue.
Resolves: #2704
---
=> [insights] collect connection check command output

tests/report_tests/basic_report_tests.py, tests/report_tests/plugin_tests/logs.py, tests/report_tests/plugin_tests/string_collection_tests.py, tests/sos_tests.py
Minor two-patch set that first enables verbosity by default to produce more helpful logs from test failures, and second provides a stopgap measure of increasing the stagetwo logs test timeout until we can determine a better path forward there.
---
=> [tests] Enable default verbosity and increase logs test timeout

sos/report/plugins/__init__.py, sos/report/plugins/rabbitmq.py
`get_container_logs()` is now `add_container_logs()` to align it better
with our more common `add_*` methods for plugin collections.
Additionally, it has been extended to accept either a single string or a
list of strings like the other methods, and plugin authors may now
specify either specific container names or regexes.
---
=> [Plugin] Rework get_container_logs to be more useful

sos/report/__init__.py
Wait for shutting down threads of timeouted plugins, to prevent
them in writing to moved auxiliary files like sos_logs/sos.log
Resolves: #2722
Closes: #2746
---
=> [report] shutdown threads for timeouted plugins

sos/report/__init__.py, sos/report/plugins/__init__.py, tests/vendor_tests/redhat/rhbz2018033.py
It was discovered that setting a specific plugin timeout via the `-k
$plugin.timeout` option could influence the timeout setting for other
plugins that are not also having their timeout explicitly set. Fix this
by moving the default plugin opts into `Plugin.__init__()` so that each
plugin is ensured a private copy of these default plugin options.
Additionally, add more timeout data to plugin manifest entries to allow
for better tracking of this setting.
Adds a test case for this scenario.
Closes: #2744
---
=> [Plugin] Ensure specific plugin timeouts are only set for that plugin

sos/report/plugins/ceph_osd.py
Enhance the ceph_osd plugin to collect more data
specific to OSD nodes.
Closes: #2735
Signed-off-by: Nikhil Kshirsagar <nkshirsagar@gmail.com>
---
=>     [ceph] Add more data collection to ceph_osd

sos/report/plugins/__init__.py
Curently, -k networking.namespace_pattern=.. is broken as the R.E. test
forgets to add the namespace in case of positive match.
Resolves: #2748
---
=> [report] fix filter_namespace per pattern

sos/cleaner/__init__.py, sos/collector/__init__.py, sos/component.py, sos/report/__init__.py
Catch unhandled EOFError in collector and cleaner.
Update the behaviour in report that redundantly prints
the error message twice.
Resolves: #2751
---
=> Catch exceptions on user prompt for ENTER / Ctrl+C

sos/presets/redhat/__init__.py
Sos report on OCP having hundreds of namespaces timeouts in networking
plugin, as it collects >10 commands for each namespace.
Let use a balanced approach in:
- increasing network.timeout
- limiting namespaces to traverse
- disabling ethtool per namespace
to ensure sos report successfully finish in a reasonable time,
collecting rasonable amount of data.
Resolves: #2754
---
=> [presets] Optimise OCP preset for hundreds of network namespaces

sos/cleaner/__init__.py, sos/cleaner/archives/sos.py, sos/cleaner/mappings/hostname_map.py, sos/cleaner/parsers/hostname_parser.py, tests/cleaner_tests/full_report_run.py
This patchset addresses two issues:
1. Adds sourcing of `/etc/hosts`, which we aren't doing currently, provides valuable information for prepping the hostname parser, in particular with short names where we would otherwise have a race condition for obfuscation.
2. Fixes a condition where our shortname handling was unintentionally case sensitive.
---
=> [clean] Improve hostname obfuscation sourcing and reliability

sos/collector/__init__.py
SoSCollector does not further declare get_upload_url method
as that was moved under Policy class(es).
Resolves: #2766
---
=> [collect] fix moved get_upload_url under Policy class

sos/report/plugins/networking.py
This commit adds `-d` to the `ip address show` executed in each of the
network namespaces on the host. This prints additonal info per each
interface, the most useful probably being VLAN information.
---
=> [networking] Print additional interfaces info in netns

sos/policies/distros/openeuler.py, sos/report/plugins/__init__.py
I'm planning to do more works on add support for openEuler distribution, including making some plugins and improve existing openEuler policy. Adding this tagging class for the first step.
openEuler has made some projects that not published on other distros yet, like iSulad, A-Tune, stratovirt , etc. So I think make a tagging might be necessary
Signed-off-by: lijingwei <lijingwei@uniontech.com>
---
=> [Plugin] Add tagging class for openEuler distro

sos/archive.py, sos/component.py, sos/policies/__init__.py, sos/policies/distros/__init__.py, sos/policies/distros/debian.py, sos/policies/distros/redhat.py, sos/policies/runtimes/__init__.py, sos/policies/runtimes/docker.py, sos/report/__init__.py, sos/report/plugins/__init__.py, sos/report/plugins/unpackaged.py, sos/utilities.py
This patchset addresses a small number of issues surrounding sysroot handling inside containers:
1. Use the correct sysroot (the policy determined sysroot, not just blindly passing the default) for `PackageManager`. I am unsure where/when this broke, but this resolves sos using the container-local package list instead of the host package list.
2. Extend kmod detection to account for non-`/` sysroots.
3. Enable `ContainerRuntime`s to activate when sos is run in a container, and the runtime is accessible through the policy-determined sysroot.
---
=> [global] Refactor sysroot determination and usage across different components

sos/report/plugins/ceph_mgr.py, sos/report/plugins/ceph_mon.py
Enhance the ceph_mgr plugin to collect more data specific to
mgr nodes. Also collect some additional manager data in the
ceph_mon plugin.
Related: #1945
Resolves: #2759
Signed-off-by: Nikhil Kshirsagar <nkshirsagar@gmail.com>
---
=> [ceph_mgr] Add more data collection to ceph_mgr

sos/collector/transports/__init__.py
When running a command that does not exist on the system, catch the
resulting pexpect exception and return the proper status code rather
than allowing an untrapped exception.
Closes: #2768
---
=> [collect] Catch command not found exceptions from pexpect

man/en/sos-collect.1, man/en/sos-report.1, sos/collector/__init__.py, sos/collector/sosnode.py, sos/report/__init__.py
Adds a new `--container-runtime` option that allows users to control
what default container runtime is used by plugins for container based
collections, effectively overriding policy defaults.
If no runtimes are active, this option is effectively ignored. If
however runtimes are active, but the requested one is not, raise an
exception to abort collection with an appropriate message to the user.
---
=> [report,collect] Add option to control default container runtime

sos/report/plugins/__init__.py, sos/report/plugins/ceph_mgr.py, sos/report/plugins/ceph_mon.py, sos/report/plugins/ceph_osd.py, sos/report/plugins/opencontrail.py, sos/report/plugins/openstack_database.py, sos/report/plugins/openstack_designate.py, sos/report/plugins/openstack_ironic.py, sos/report/plugins/ovn_central.py, sos/report/plugins/rabbitmq.py
Adds a new `container` parameter for `Plugin.add_cmd_output()`, which if
set will format all commands passed to that call for execution in the
specified container.
`Plugin.fmt_container_cmd()` is called for this purpose, and has been
modified so that if the given container does not exist, an empty string
is returned instead, thus preventing execution on the host.
---
=> [Plugin] Add container parameter for add_cmd_output()

sos/policies/distros/rocky.py
Rocky Linux is an enterprise Linux distribution based on RHEL. This adds
a Rocky Linux policy, which inherits the RedHatPolicy base and uses the
RedHatPlugin tagging class.
Signed-off-by: Louis Abel <label@rockylinux.org>
---
=> [policies] Add Rocky Linux policy

sos/report/plugins/vdsm.py
This patch adds the directory /var/lib/vdsm/storage/transient_disks
to the list of forbidden paths, because it contains sensitive data
(cloud-init disks) or big files.
Resolves: RHBZ#2029154
---
=> [vdsm] Exclude /var/lib/vdsm/storage/transient_disks

sos/cleaner/archives/sos.py, sos/cleaner/mappings/hostname_map.py, sos/cleaner/mappings/username_map.py, sos/cleaner/parsers/username_parser.py
First, simplify the case matching of hostnames to all upper case conventions for domains.
Second, make username matching similarly case insensitive like we did with hostnames. Additionally, fix and extend the sourcing of usernames to not skip the first entry in `last` by erroneously accounting for a header that is only in `lastlog`, and include `/etc/cron.{allow|deny}` as a source for usernames for an edge case where (ldap/ad) users are allowed or denied to modify crontab but have not actually logged in.
---
=> [cleaner] Fix username casing and sourcing, simplify hostname casing

sos/report/__init__.py
Fixes an issue where the use of `-a` would fail due to trying to
iterate over the key of the plugin's options dict rather than the actual
`PluginOpt` value.
Closes: #2786
---
=> [report] Fix setting of all options via `-a`

sos/collector/sosnode.py
When `cleanup()` is called for a local node, we were generating a false
warning that we couldn't remove the sos report. This removal attempt is
unnecessary since local nodes moves the sos archive during collector
archive creation, rather than copying it like we do for remote nodes.
Closes: #2769
---
=> [sosnode] Fix removal warning when cleaning up on a local node

sos/policies/__init__.py, sos/policies/distros/__init__.py, sos/policies/distros/debian.py, sos/policies/distros/redhat.py, sos/policies/distros/suse.py
This commit fixes an issue where policies loaded for remote nodes when
using `sos collect` would override the PATH setting for the local
policy, which in turn could prevent successful execution of cluster
profile operations.
Related: #2777
---
=> [Policy,collect] Prevent remote node policies from setting local PATH

sos/policies/distros/__init__.py, sos/policies/runtimes/__init__.py, sos/policies/runtimes/crio.py, sos/report/plugins/openshift_ovn.py
`openshift_ovn` plugin collects logs from crio containers
Fix `get_container_by_name` function returning container_id and not name
Tested with new `--container-runtime` option, works well.
---
=> [runtimes:crio][plugins:openshift_ovn] Add crio runtime and openshift_ovn plugin

sos/collector/clusters/ocp.py, sos/report/plugins/crio.py, sos/report/plugins/networking.py
Fixes a corner case where we would still attempt to create a new project
within the OCP cluster even if we weren't using the `oc` transport.
---
=> [ocp] Skip project setup whenever oc transport is not used

sos/cleaner/mappings/hostname_map.py
Fixes an edge case that would cause us to at first not recognize that a
given hostname string is a new host in a known subdomain, but then on
the obfuscation attempt properly recognize it as such and result in an
incomplete obfuscation.
This was mostly triggered by specific patterns for build hosts within
`sos_commands/rpm/package-data`. With this refined check, these types of
matches are properly obfuscated.
---
=> [hostname] Fix edge case for new hosts in a known subdomain

sos/report/plugins/ipmitool.py
Hardware vendors choose an IPMI channel number for BMC LAN.
The current IPMI plugin is collecting data for channel 3.
Dell is using channel number 1. The number is not reserved for
a specific hardware vendor. It can be used by others too.
Add data collection for IPMI channel number 1.
https://www.dell.com/support/manuals/en-us/virtual-edge-platform-4600-4c/vep4600_bmc_user_guide_pub/configurations?guid=guid-7e10db8f-114e-475b-808a-3254f2dac46e&lang=en-us
---
=> [ipmitool] Collect data for IPMI channel number 1

sos/collector/__init__.py, sos/collector/clusters/ocp.py, sos/collector/sosnode.py, sos/collector/transports/__init__.py, sos/collector/transports/local.py, sos/collector/transports/oc.py
If a paritcular attempt to retrieve a remote file fails, we should
automatically retry that collection up to a certain point. This provides
`sos collect` more resiliency for the collection of sos report archives.
This change necessitates a change in how we handle the SoSNode flow for
failed sos report retrievals, and as such contains minor fixes to
transports to ensure that we do not incorrectly hit exceptions in error
handling that were not previously possible with how we exited the
SoSNode retrieval flow.
Closes: #2777
---
=> [transport] Detect retrieval failures and automatically retry

sos/options.py
The `--keywords` option supports spaces to allow for obfuscated phrases,
not just words. This however breaks if a phrase is added to the config
file *before* a run with the phrase in the cmdline option, due to the
safeguards we have for all other values that do not support spaces.
Add a check in our flow for updating options from the config file to not
replace illegal spaces if we're checking the `keywords` option, for
which spaces are legal.
---
=> [options] Allow spaces in --keywords values in sos.conf

sos/report/plugins/rpmostree.py
- `rpm-ostree status` replaced with `rpm-ostree status -v`
- Added `rpm-ostree kargs` output
Signed-off-by: Pablo Alonso Rodriguez <palonsoro@gmail.com>
---
=> [rpmostree] Improvements at rpm-ostree plugin

sos/policies/__init__.py
Depending on configuration, certain downstreams may provide pexpect 2.3
or 4.6 (or later). The backport for SFTP upload support assumed a 4.x
version pexpect, however 2.x does not support the `encoding` parameter
to `pexpect.spawn()`.
Add a version check to determine if that parameter needs to be used or
not. Note that this does not need to be implemented against `main`, as
all supported downstreams for `main` support a minimum version of 4.x.
---
=> [report] Handle exceptionally old pexpect versions

man/en/sos-report.1, sos/report/__init__.py
As --estimate-only calculates disk usage based on `stat` data that
differs from outputs of other commands like `du`, enhance the warning
about reliability of the calculated estimation.
Also add a rule-of-thumb recommendation of real disk space requirements.
Resolves: #2815
---
=> [report] Provide better warning about estimate-mode

sos/report/plugins/system.py
=> [system] Collect glibc tuning decisions

sos/report/__init__.py, tests/sos_tests.py
In the event a CI test execution fails before the archive is created,
for any reason, we want to preserve the temp directory as the logs there
are still useful.
As such, add a specific env var to our test runs via avocado. Then, when
we detect a failure check for that env var to determine if we should in
fact do our cleanup or not.
---
=> [tests] Do not remove temp dirs from failed CI test runs

sos/report/plugins/networking.py
'ss -peaonmi' does require also xsk_diag kmod that must be
added to the list of kmod predicates of the ss command.
Resolves: #2818
Related: #2816
---
=> [networking] Enhance ss_pred by xsk_diag kmod

.cirrus.yml
F35 has been out for a bit, we should update our testing matrix
accordingly.
New images have been pushed to GCP, so this change updates Cirrus to use
those new images.
---
=> [cirrus,tests] Update testing matrix to Fedora 35

sos/cleaner/__init__.py, sos/cleaner/archives/__init__.py, sos/cleaner/mappings/hostname_map.py, sos/cleaner/parsers/ip_parser.py, sos/cleaner/parsers/username_parser.py
This patchset includes an alternative fix to #2811 which also carries some fixes for other issues found while investigating the CI failures from that change.
We should now properly account for long `--domains` values, and better handle parser file skips. Additionally, some well-known files/strings are added to skip lists that were discovered in tandem with this work.
---
=> [cleaner] Fix long domain handling/detection, parser handling, and known skips

sos/utilities.py
Arguments that start with / and must contain a * are
the only ones that get checked if they can be expanded.
Signed-off-by: Bryan Quigley <code@bryanquigley.com>
---
=> [utilities] Restrict when commands are checked for wildcards

sos/collector/__init__.py, sos/collector/sosnode.py
Reproducer: on a non-`ovirt` system, try to wrongly sos collect like it would be that cluster type:
python3 bin/sos collect -vvv --case-id=666 --no-local --cluster-type ovirt --primary "127.0.0.1" --batch
---
=> Make cluster init failure more robust

sos/archive.py, sos/report/__init__.py, sos/report/plugins/__init__.py, sos/utilities.py
This patchset aims to address a long standing ask for sos - that command output is not _required_ to be stored entirely in memory while we are collecting it.
With these commits, when `--all-logs` is used, or if `sizelimit` is zero for specific commands, `sos_get_command_output()` will write the output directly to a temp file rather than storing the output in memory and returning that.
This is so far only exposed via `add_cmd_output()` by a new `to_file` parameter, but this is automatically handled in the cases above for both `add_cmd_output()` and `add_journal()`. This functionality is not exposed via `exec_cmd()` or `collect_cmd_output()`.
After the command output temp file has been copied to the archive, the temp file is removed via the second commit extending `TempFileUtil`.
Resolves: …
=> [Plugin, utilities] Allow writing command output directly to disk

sos/report/plugins/storcli.py
Adapter information is not showing in
/call show events command because it
requires file=<filename> as a parameter
e.g.
/opt/MegaRAID/storcli/storcli64 /call show events file=storcli64_.call_show_events
Signed-off-by: Mahesh Potkar <maheshpotkar@gmail.com>
---
=> [storcli] Fix show events command

sos/report/plugins/vmware.py
It displays information whether VMware time sync is enabled, which
affects how ntpd/chronyd works.
Resolves: #2824
---
=> [vmware] collect vmware timesync status

sos/cleaner/__init__.py, sos/cleaner/parsers/__init__.py, sos/cleaner/parsers/keyword_parser.py, sos/cleaner/parsers/username_parser.py, tests/unittests/cleaner_tests.py
For parsers such as the username and keyword parsers, we don't discover
new items through parsing archives - these parsers use static lists
determined before we begin the actual obfuscation process.
As such, we can build a list of regexes for these static items once, and
then reference those regexes during execution, rather than rebuilding
the regex for each of these items for every obfuscation.
For use cases where hundreds of items, e.g. hundreds of usernames, are
being obfuscated this results in a significant performance increase.
Individual per-file gains are minor - fractions of a second - however
these gains build up over the course of the hundreds to thousands of
files a typical archive can be expected to contain.
---
Please place …
=> [clean,parsers] Build regex lists for static items only once

sos/cleaner/mappings/__init__.py, sos/cleaner/mappings/username_map.py, sos/cleaner/parsers/username_parser.py
This commit fixes a couple edge cases where an item empty (e.g. and
empty string '') was not being properly ignored, which in turned caused
failures in writing both obfuscations and replacement files.
This should no longer be possible.
---
=> [clean] Ignore empty items for obfuscation better

sos/report/plugins/systemd.py
Systemd has a hard limit of units that it can keep, and the limit is 128K.
Once that limit is hit (which is usually happening due to various bugs),
systemd returns E2BIG ("Argument list too long") when trying to start a
new unit. Until recently, it was not possible to figure out what is
going on without looking at the "systemctl list-units --all" output.
That's why it's nice to have it in sos report.
Found while working on https://bugzilla.redhat.com/show_bug.cgi?id=2028153
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>
---
=> [systemd] Collect systemctl list-units --all

sos/cleaner/parsers/mac_parser.py
The regex trys to match a single character not present
in the given list [^:|-]. The string which starts with
addresses are left out as there is
no character to match.
Adding ? to matches the previous token between zero and one time.
Resolves Issue: #2829
Signed-off-by: Nikhil Kakade <nikhilkaka5@outlook.com>
---
=> [cleaner] Update regex for finding IPv4/v6 addresses

man/en/sos-help.1, sos/__init__.py, sos/cleaner/__init__.py, sos/collector/__init__.py, sos/collector/clusters/__init__.py, sos/collector/clusters/jbon.py, sos/collector/clusters/kubernetes.py, sos/collector/clusters/ocp.py, sos/collector/clusters/ovirt.py, sos/collector/clusters/satellite.py, sos/collector/transports/__init__.py, sos/collector/transports/control_persist.py, sos/collector/transports/local.py, sos/collector/transports/oc.py, sos/component.py, sos/help/__init__.py, sos/policies/__init__.py, sos/policies/distros/__init__.py, sos/policies/distros/redhat.py, sos/report/__init__.py, sos/report/plugins/__init__.py, sos/report/plugins/apache.py, sos/report/plugins/filesys.py, sos/report/plugins/kernel.py, sos/report/plugins/podman.py, sos/utilities.py
This patchset adds a new `help` component, enabling the execution of `sos help $topic`.
This subcommand is intended to provide more detailed information on the various parts of the SoS project that cannot reasonably be maintained in a manpage or `--help` output.
For this initial implementation, I have added help for `report`, `collect`, `clean|mask`, as well as various constructs within those commands. I have not yet however added help sections for parsers within `clean`, as there is very little user control or interaction there. As we build that out, we can add help sections at that time.
Generally speaking, this makes it so items like plugins have help pages built automatically from the plugins themselves - i.e. enablement criteria, available options, etc... I would eventually like to …
=> [sos] Add a new `help` component

sos/report/plugins/ovn_central.py, sos/report/plugins/ovn_host.py
Previous ovn packages were 'ovn2xxx' and now they have
been renamed to 'ovn-2xxx'. This causes sos tool to not
recognize that the packages are installed and it won't
collect the relevant data.
This patch is changing the match expression to be compatible
with the previous and newer naming conventions.
Signed-off-by: Daniel Alvarez Sanchez <dalvarez@redhat.com>
---
=> [ovn_central] Account for Red Hat ovn package naming

sos/report/plugins/virsh.py
In case virsh output is malformed or missing 'Name' otherwise,
catch parsing exception and continue in next for loop iteration.
Resolves: #2836
---
=> [virsh] Catch parsing exception

sos/policies/runtimes/__init__.py, sos/policies/runtimes/crio.py, sos/policies/runtimes/docker.py, sos/report/plugins/__init__.py
2-patch set to add support for copying files from containers via `add_copy_spec()` with a new `container` parameter.
The second patch in this set provides symlinking of container-based command collections to the new `sos_containers/` location introduced by the first commit from the normal location inside `sos_commands/$plugin/`.
Closes: #2439
---
=> [Plugin] Add support for copying files from containers

sos/report/plugins/discovery.py
This commit creates as new plugin for the
discovery tool. This tool is an inspection
and reporting tool, designed to find, identify,
and report environment data.
Fixes: RHBZ#2018549
---
=> [discovery] Add new discovery plugin

sos/cleaner/parsers/mac_parser.py
This commit adds a negative look-behind to the regex patterns for mac
addresses so we avoid matching substrings from both non-mac-address
strings, certain ipv6 address strings, and longer strings of hextets
that we could potentially match a substring of.
---
=> [mac_parser] Avoid substring matches with look-behinds

sos/report/plugins/ovn_central.py
Add commands to collect cluster status of Northbound and
Southbound ovsdb servers.
Resolves: #2840
Signed-off-by: Hemanth Nakkina hemanth.nakkina@canonical.com
---
=> [ovn-central] collect NB/SB ovsdb-server cluster status

sos/cleaner/mappings/hostname_map.py
This commit aims to reduce false-positive matches by the hostname
parser/map. Do this by first removing a too-broad substring check that
is better covered by a simpler check in the `_domains` internal dict,
made possible by the previous change which explicitly checks without the
tld as part of the domain string.
Second, improve the set of extensions to strip from potential matches
that would otherwise be regarded as TLDs, but are in fact not TLDs.
---
=> [hostname] Reduce false positive matches

sos/report/plugins/libvirt.py
Update the libvirt plugin to collect logs from /var/log/containers,
which may be populated in certain environments, like
OpenStack TripleO
This is an addition to #1130 where a couple of things got missed
Signed-off-by: Bogdan Dobrelya <bdobreli@redhat.com>
---
=> [libvirt] Collect containerized logs

sos/report/plugins/dellrac.py
Due to the runat=logpath argument, we must ensure the logpath directory
is created. Also catch properly the case when the directory has been
created before.
Resolves: #2845
---
=> [dellrac] ensure the logpath directory exists

sos/policies/distros/__init__.py
9596473 commit added a regression allowing to set sysroot to None
when running sos report on a regular system (outside a container). In
such a case, we need to fallback to '/' sysroot.
Resolves: #2846
---
=> [policies] Set fallback to None sysroot

.cirrus.yml
The latest release of avocado-framework, 95.0, makes several changes
that will require us to investigate moving to the newer nrunner
test-runner.
For the moment, pin our CI tests to a previous version so that the
changes in newer avocado versions don't block current development.
---
=> [avocado] Pin avocado test suite to version 94

sos/utilities.py
With the recent fix for sysroot being `None` to always being (correctly)
`/`, we should guard against situations where `sos_get_command_output()`
would now try to chroot to `/` before running any command. Incidentally,
this would also cause our unittests to fail if they were run by a
non-root user.
---
=> [utilities] Don't try to chroot to /

sos/report/__init__.py
An early implementation of #2729 included expanding `TempFileUtil` and
passing it as a means to create temp files to write command output
directly to. That approach was abandoned in favor of a more robust
implementation, but the cleanup of the previous design was apparently
not complete.
Fix this by removing the inclusion of tempfile_util in our `commons`
dict.
---
=> [report] Remove useless inclusion of tempfile_util in commons

sos/report/plugins/host.py
While `default_mapping` is typically the only file expected under
`/etc/sos/cleaner/` it is possible for other mapping files (such as
backups) to appear there.
Make the `add_forbidden_path()` spec here target the entire cleaner
directory to avoid ever capturing these map files.
---
=> [host] Skip entire /etc/sos/cleaner directory

sos/policies/runtimes/__init__.py, sos/report/plugins/__init__.py
As container runtimes can interchange container names and container IDs,
sos should also allow the use of container IDs when checking for the
presence of a given container.
In particular, this change unblocks the use of `Plugin.exec_cmd()` when
used in conjunction with `Plugin.get_container_by_name()` to pick a
container based on a provided regex that the container name may match.
Related: #2856
---
=> [runtimes] Allow container IDs to be used with `container_exists()`

sos/report/plugins/ovn_central.py
ovn_central plugin is running by container with
name 'ovn-dbs-bundle*', a typo has been identified and
this cause plugin ovn_central not enabled by default as it
does not recognize any container responsible of this.
This patch fix this container name match.
Signed-off-by: Fernando Royo  <froyo@redhat.com>
---
=> [ovn_central] Rename container responsable of Red Hat ovn_central plugin

sos/report/plugins/pulpcore.py
The reserved resource approach was used by pulp-3 for a sporadic time
in early pulp-3 development only. It is abandoned and should not be
productised anywhere. So it is safe to remove the commands (together
with rq broker status that was in charge of reserved resources).
Resolves: #2865
---
=> [pulpcore] Stop collecting commands relevant to old taskig system

sos/report/plugins/__init__.py
Currently, plugin's plugin_timeout hardcoded default is superseded by
whatever --plugin-timeout value, even when this option is not used and
we eval it to TIMEOUT_DEFAULT.
In this case of not setting --plugin-timeout, honour plugin's
plugin_timeout instead.
Resolves: #2863
Closes: #2864
---
=> [report] Honor plugins' hardcoded plugin_timeout

sos/cleaner/mappings/__init__.py, sos/cleaner/mappings/hostname_map.py, sos/cleaner/mappings/ip_map.py, sos/cleaner/mappings/mac_map.py, sos/cleaner/parsers/__init__.py, sos/cleaner/parsers/hostname_parser.py, sos/cleaner/parsers/ip_parser.py, sos/cleaner/parsers/keyword_parser.py, sos/cleaner/parsers/mac_parser.py, sos/cleaner/parsers/username_parser.py
This commit follows the initial change made to the username and keyword
parsers in #2823 and applies it to all parsers by default.
When a new match is found, a new `regex.Pattern()` object will now be
compiled and saved in the parser's map, and this object will be used for
ongoing obfuscations from that point forward, rather than rebuilding
regexes for every line we iterate over with that parser.
This is now built into the base `SoSMap` and leveraged by parsers,
rather than being handled directly by parsers. Further, this will be
enabled by default for all existing and new parsers. This shows decent
improvements to hostname parser performance in local testing. Note that
this functionality is explicitly disabled for the mac and ip parsers. …
=> [cleaner] Use compiled regex lists for parsers by default

sos/policies/distros/redhat.py
When missing some credentials, do overwrite upload_url to the Red Hat
SFTP server *only* when upload-url points to the Customer Portal API
server.
Resolves: #2869
Closes: #2870
---
=> [redhat] Honour credential-less --upload-url on RedHat distro properly

tests/report_tests/timeout_tests.py, tests/test_data/fake_plugins/timeout_test.py
There was a gap in our testing that allowed #2863 to escape our notice -
that a `Plugin()`'s `plugin_timeout` attribute would be ignored if it
wasn't set to `TIMEOUT_DEFAULT`.
As that was resolved by #2864, add a test to ensure it remains working
as expected. The expected resolution order for a plugin's whole timeout
is as follows:
1. The value set by `-k plugin.timeout`
2. The value set by `--plugin-timeout`
3. The value hardcoded in the plugin via the `plugin_timeout` attr
4. `TIMEOUT_DEFAULT`
Related: #2863
Related: #2864
---
=> [tests] Add a test for non-default plugin_timeout compliance

sos/report/plugins/collectl.py
collectl is a tool that helps gather performance data
and perform benchmarks and monitoring of the systems'
health. The plugin captures the configuration file
and the logs in /var/log/collectl/
Resolves: #2876 
---
=> [collectl] New collectl plugin

sos/report/plugins/tigervnc.py
First, relaxes the file specifications for collection by capturing the
entire `/etc/tigervnc/` directory.
Second, adds collection of service status and journal output for each
configured vnc server. Collection of `vncserver -list` is kept for
backwards compatibility.
Finally, add a short docstring for the plugin for --help output.
---
=> [tigervnc] Update collections for newer versions of TigerVNC

sos/report/plugins/ceph_mgr.py, sos/report/plugins/ceph_mon.py, sos/report/plugins/ceph_osd.py
mon_status command is no longer available since Octopus
release. Replaced it with its ceph tell equivalent that
works in both older as well as newer Ceph releases.
Signed-off-by: Ponnuvel Palaniyappan <pponnuvel@gmail.com>
---
=> [ceph_mon] Replace an obsolete command

sos/cleaner/parsers/mac_parser.py, tests/unittests/cleaner_tests.py
First, update the regexes to account for possible quotes wrapping the
mac address to match.
Second, fix an edge case with these quoted mac addresses in our check
for avoiding duplicating obfuscations of already obfuscated addresses by
checking the stripped mac address instead of the raw one.
Closes: #2873
---
=> [mac_parser] Match quoted mac addresses, fix duplication check

sos/policies/distros/redhat.py
Commit 1bcb449 needs to be enhanced to test if self.upload_url has been
already set. Otherwise, 'NoneType' object has no attribute 'startswith'
is raised.
Resolves: #2879
---
=> [distros] Fix broken upload due to 1bcb449

sos/report/plugins/openshift_ovn.py, sos/report/plugins/openvswitch.py
Add ovs datapath and groups collection commands
Add ct-zone-list command for openshift-ovn
Here is the sos report archive to check commands output: https://drive.google.com/file/d/15sJH6QceFUy1BeZGRl63XjUqv4GC2hWs/view?usp=sharing
---
=> [openvswitch][openshift_ovn] Add collection commands

sos/policies/distros/__init__.py, sos/policies/distros/redhat.py
Apart of that, print a heads up message during SFTP upload when --upload-directory
was set.
Resolves: #2880
---
=> [distros] Pass --upload-directory to SFTP uploads

sos/report/plugins/md.py
When generating sos report, md-raid plugin won't capture the
metadata information from the actual RAID device. Also, it
tries to fetch metadata information for all block devices
available in the system.
Sometimes RAID is created using the disk partition,
but sos won't collect metadata from those devices.
This patch takes the list of raid members from lsblk,
and captures the output only for these devices.
Fixes: RHBZ#2062283
Fixes: #2881 
---
=> [md] Restrict data capture to raid members

sos/collector/clusters/ocp.py, sos/collector/transports/oc.py
1. wait for sos tmp project to be deleted (just calling delete changes
project state to Terminating, and running a new sos collect is not
possible before this project is fully deleted)
2. use --retries flag to copy sos reports from the nodes more reliably.
The flag has been recently added to kubectl, and the most reliable way
to check if it's available or not is to check command error output for
"unknown flag" substring
---
=> [collector] Improve sos collect for OCP

sos/report/plugins/ceph_mon.py
Adds a `postproc()` to the `ceph_mon` plugin to obfuscate sensitive
configuration keys printed by the `ceph config-key dump` command.
Closes: #2885
---
=> [ceph_mon] Obfuscate sensitive config keys

sos/report/plugins/cgroups.py
Forbid collection of memory.kmem.slabinfo
which in case of system with lot of
containers may cause stuck kworker.
Resolves: #2889
---
=> [cgroups] not collect memory.kmem.slabinfo

sos/report/plugins/scsi.py
Adds collection of various `sq_persist` and `sg_inq` commands to the
`scsi` plugin for scsi block devices on the host system.
Also adds a docstring description to the plugin to assist with `sos
help` output.
---
=> [scsi] Add collection of SCSI persistent reserve commands

sos/collector/__init__.py
Corrects the initial assignment of `self.primary` to `None` instead of
`False`, so that quick scanning over the code is more inline with
`Cluster` instances.
Closes: #2892
---
=> [collect] Correct `self.primary` to NoneType default

sos/report/plugins/__init__.py, tests/report_tests/plugin_tests/plugin_environment.py, tests/test_data/fake_plugins/default_env_test.py, tests/unittests/plugin_tests.py
Adds the ability for plugins to define a default set of environment vars
to pass to all commands executed by the plugin. This may be done either
via the new `set_default_cmd_environment()` or
`add_default_cmd_environment()` methods. The former will override any
previously set values, whereas the latter will add/update/modify any
existing values.
---
=> [Plugin] Allow plugins to define default command environment vars

sos/archive.py, sos/cleaner/__init__.py
Two commits preventing to apply cleaner obfuscation to the working directory path itself. Creating files or moving directories must happen within the (non-obfuscated) working dir.
The `archive` commit changes purpose of `self._name` variable from `/var/tmp/sos.oq9ae6gj/sosreport-pmoravec-rhel8-2022-03-16-qzazpxi` to just `sosreport-pmoravec-rhel8-2022-03-16-qzazpxi`. Since the full path is already captured in `_archive_root` variable.
---
=> Sos pmoravec dont obfuscate tmpdir path

sos/collector/__init__.py, sos/collector/clusters/__init__.py, sos/collector/clusters/pacemaker.py
This 2-patch set overhauls how the `pacemaker` profile enumerates nodes.
Rather than rely on `pcs status` output which is liable to change (and apparently has changed recently), instead use `crm_mon` which is what the former called under the hood anyways. If that fails for any reason, directly reference `/etc/corosync/corosync.conf`. Note however that this fallback method does not let us separate online nodes from offline ones.
Further, due to pacemaker's ability to have node names reported that are not the node's actual resolvable hostnames (they can be named arbitrarily by sysadmins) there is a potential for duplicate collections of the primary node. As such, add a toggle to cluster profiles via the `strict_node_list` class attr that can be used to tell collect to not add the local host …
=> [pacemaker] Update collect cluster profile for pacemaker

sos/presets/redhat/__init__.py
Adjust the options used by the 'ocp' preset to better reflect the
current collection needs and approach.
This includes disabling the `cgroups` plugin due to the large amount of
mostly irrelevant data captured due to the high number of containers
present on OCP nodes, ensuring the `--container-runtime` option is set
to `crio` to align container-based collections, disabling HTML report
generation and increasing the base log size rather than blindly enabling
all-logs.
---
=> [presets] Adjust OCP preset options

.cirrus.yml
Updates the CentOS Stream 8 image used to run the CI tests, and adds
testing on CentOS Stream 9 now that those images are available.
---
=> [cirrus] Update CentOS Stream 8 image, add Stream 9 testing

.cirrus.yml, requirements.txt, setup.py, sos.spec, sos/cleaner/archives/__init__.py, sos/report/plugins/__init__.py, sos/utilities.py, tests/unittests/plugin_tests.py
First, implement better binary file detection for `sos clean` via the `python-magic` module. Which is the python bindings for `libmagic` - which among other things is the backend behind the `file` command.
Then add a check to `add_copy_spec()` so we don't tail binary files.
Closes: #2839
Closes: #2851
---
=> [utilities, Plugin] Improve binary file detection, don't tail binary files

sos/report/plugins/seagate_ses.py
Adding a new plugin to get Seagate JBOD status
SES Monitoring tool "getstatus" is used to the information of Seagate storage products.
Signed-off-by: Nikhil Kakade <nikhilkaka1@gmail.com>
---
=> [seagate_ses] Add new plugin to get Seagate JBOD status

sos/report/plugins/rpm.py
Adds collection of directory listing output for `/var/lib/rpm`.
---
=> [rpm] Capture directory listing for /var/lib/rpm

sos/policies/distros/__init__.py
Simplifies the logic and flow of `LinuxPolicy._container_init()` so that
it is both easier to follow and less prone to edge cases that could
break in-container collections that are not setup to capture from the
host system.
---
=> [policies] Simplify flow in _container_init()

docs/archive.rst, docs/clusters.rst, docs/parsers.rst, docs/plugins.rst, docs/policies.rst, docs/reporting.rst, docs/utilities.rst, sos/policies/__init__.py, sos/report/plugins/__init__.py
First commit fixes the sphinx doc configuration to remove `:noindex:` which was throwing off cross-referencing via `automodule`.
Second, minor fixes to docstrings (and filling out the docstring) in a few places in `Policy` and `Plugin`. Additionally make tagging classes have an actual base class of `PluginDistroTag`. Re-organize the declaration of supported tagging classes so they are all in one spot.
Closes: #2917
---
=> [docs] Fix cross-referencing in sphinx config, doc fixups in Plugin and Policy

sos/utilities.py
Call _output.close() only when to_file=true.
Closes: #2925
---
=> [utilities] Close file only when storing to file

sos/report/plugins/fibrechannel.py
Collect /sys/kernel/debug/fnic statistics about Cisco UCS fibre channel
fNIC connection.
Resolves: #2926
---
=> [fibrechannel] collect Cisco fnic statistics

sos/report/__init__.py
When using `--list-plugins`, sos should report the values that will be
used in a given command, or with a given config file, not what the
default values are.
By reporting the set value, users can be sure their configuration or
commandline settings are being honored correctly before executing a
report collection.
Closes: #2921
---
=> [report] --list-plugins should report used, not default, option values

sos/report/plugins/candlepin.py, sos/report/plugins/pulpcore.py
Collect `db_tables_sizes` also for `pulpcore` and unify/extend the format of the same psql stats in `candlepin`.
---
=> Sos pmoravec pulpcore candlepin psql tablesizes

sos/report/plugins/networkmanager.py
NetworkManager's keyfiles (`*.nmconnection`) can contain secrets in plain
text. Let's try harder to filter them out.
The files are in `GKeyFile` format ([1]), so a naive regex doesn't really
cut it, because the meaning of the key also depends on the group
(keyfile section) it is in. But this probably still helps in many cases.
The current list (1.39.2) of NetworkManager secret properties in the
various keyfile groups is:
```
mka-cak
password-raw
pin
private-key
psk
secrets
wep-key0
wep-key1
wep-key2
wep-key3
```
plus several ending in /password/:
```
ca-cert-password
client-cert-password
leap-password
password
phase2-ca-cert-password
phase2-client-cert-password
phase2-private-key-password
private-key-password
```
Additionally, and what this patch does not cover, vpn secrets are in a …
=> [networkmanager] filter out more passwords from NetworkManager keyfiles

sos/policies/__init__.py, sos/policies/distros/__init__.py
Over time a lot has changed with `Policy()` implementation. Along with
that, the functionality of `GenericPolicy` broke at some point, thus
preventing any form of execution of SoS on distributions without
explicit policies.
Fix this by changing `GenericPolicy` to `GenericLinuxPolicy` (to be more
explicit in case we re-add non-Linux support in the future) and having
it subclass `LinuxPolicy` instead of the top-level `Policy`.
Further, add a platform check to ensure we are not inadvertently loading
a Linux-based policy on a non-Linux platform which would likely result
in failure to do anything useful.
The `GenericLinuxPolicy` will only load `IndependentPlugin`-tagged
plugins, does not leverage an init system, and does not provide any
default upload functionality.
Related: #2928 …
=> [GenericPolicy] Fix execution when GenericPolicy is loaded

sos/report/plugins/__init__.py
For PlugOpt type 'str', we should allow any content including e.g.
numbers, and interpret it as a string.
Resolves: #2922
Closes: #2935
---
=> [plugins] Allow 'str' PlugOpt type to accept any value

sos/report/plugins/postgresql.py
After the change introduced via PR #2935
(Allow 'str' PlugOpt type to accept any value)
the postgresql plugin was the only one specifying
both str and int as possible values. This patch
simplifies the val_type field to be in line
with the rest of plugins where str covers int as well.
Depends on: #2935 
Closes: #2936
---
=> [postgresql] Simplify val_type for dbport

sos/collector/transports/oc.py
This option should be useful both for testing and real-life usage to be able to control version of support-tools container.
Description looks correct - https://github.com/sosreport/sos/blob/main/sos/collector/__init__.py#L357-L359, but please let me know if it was meant for something else or if I can update it.
---
=> [collector] use --image option for oc-based sos collect

sos/report/plugins/ceph_mon.py, sos/report/plugins/ceph_osd.py
Ceph uses leveldb (old versions) or rocksdb (recent to current ones)
for metadata. The older filestore backend is deprecated since
Quincy (17.2.0) which uses leveldb. So it's useful to know
if, for example, ceph-mon is still using leveldb for metadata.
This can happen even after upgrading to newer Ceph versions
if the leveldb isn't migrated to leveldb.
Signed-off-by: Ponnuvel Palaniyappan <pponnuvel@gmail.com>
---
=> [ceph_mon/ceph_osd] Collect metata type used in the backend

sos/report/plugins/shmcli.py
shmcli provides information of the adapters, emms, drives,
enclosures, fans, and power supplies.
And the sensing data of temp, voltage, and current sensors.
[1] https://dl.dell.com/topicspdf/powertools-shm-ag_en-us.pdf
Signed-off-by: Nikhil Kakade <nikhilkaka1@gmail.com>
---
=> [shmcli] Added new plugin to get information from PowerVault/Dell

sos/report/__init__.py
This patch tries to capture the exception when running
the sosreport at the same time the temp directory
specified as an option is deleted.
Resolves: #2806
---
=> [sos] Fix unhandled exception when concurrently removing temp dir

sos/report/plugins/fibrechannel.py
This patch is to update fibrechannel plugin to collect
HBA device logs
following commands are added
hbacmd listhbas
hbacmd HbaAttributes <WWPN | MAC>
hbacmd PortAttributes <WWPN | MAC>
hbacmd ServerAttributes
Signed-off-by: Mamatha Inamdar <mamatha4@linux.vnet.ibm.com>
Reported-by: Borislav Stoymirski <borislav.stoymirski@bg.ibm.com>
Reported-by: Toni Gibson <cajun1@us.ibm.com>
Tested-by: Borislav Stoymirski <borislav.stoymirski@bg.ibm.com>
---
- [ x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x ] Is the subject and message clear and concise?
- [x ] Does the subject start with **[plugin_name]** …
=> [fibrechannel]: Update fibrechannel plugin to collect HBA logs

sos/component.py
Changed loglevel logic to be more transparent.
Setting file loglevel (flog) on DEBUG when any verbosity is
set.
If not leave flog to INFO.
---
=> [component] Adjust loglevel setting to be more transparent

sos/report/plugins/ovirt.py
Instead of hard-coding specific keys and having to maintain them over
time, replace the values of all keys that have 'password' in their name.
I think this covers all our current and hopefully future keys. It might
add "false positives" - keys that are not passwords but have 'password'
in their name - and I think that's a risk worth taking.
A partial list of keys added since the replaced code was written:
- grafana-related stuff
- keycloak-related stuff
- otopi-style answer files
---
=> [ovirt] answer files: Filter out all password keys

sos/report/plugins/systemtap.py
The enablement trigger of `files` in this plugin was incorrect, and
should have been `commands` given we're checking for an executable.
Fix that, so that this plugin can properly enable on more than just the
package names.
---
=> [systemtap] Correct enable trigger to `commands`

sos/report/plugins/libvirt.py
Update the libvirt plugin to collect swtpm logs from hosts,
and certain containerized environments, like OpenStack TripleO
---
=> [libvirt] Collect swtpm logs from host/container

sos/report/plugins/vdsm.py
Since RHV 4.4 SP1, vdsm configures LVM to use devicesfile, causing that
the LVM filter configuration used by sos is ignored.
This change disables the use of the devicesfile, so that the information
of the devices used for RHV storage domains can be collected.
Fixes: RHBZ#2093993
Signed-off-by: Juan Orti <jortialc@redhat.com>
---
=> [vdsm] Set LVM option use_devicesfile=0

sos/report/plugins/__init__.py, sos/report/plugins/cgroups.py, sos/report/plugins/pulpcore.py, sos/report/plugins/rhui.py
Forbidden path checks have up until now worked by taking a given file
path (potentially with globs), expanding that against all discovered
files that actually exist on the system, and then comparing a potential
collection path against that list.
While this works, and works reasonably fast for most scenarios, it isn't
very efficient and causes significant slow downs when a non-standard
configuration is in play - e.g. thousands of block devices which sos
would individually have to compare against tens of thousands of paths
for every path the `block` plugin wants to collect.
Improve this by first not expanding the forbidden path globs, but taking
them as distinct patterns, translating from shell-style (to maintain
historical precedent of using globs to specify paths to be skipped) to
python …
=> [Plugin] Make forbidden path checks more efficient

sos/report/plugins/ostree.py
Adds two services to the `services` tuple for this plugin to both serve
as an enablement trigger, and to capture the status and journals of
these services automatically.
This is an update/replacement to #2919 originally proposed by Colin
Walters.
Closes: #2919
Co-authored-by: Colin Walters <walters@verbum.org>
---
=> [ostree] Add services enablement trigger

sos/policies/distros/redhat.py, sos/policies/init_systems/__init__.py, sos/policies/init_systems/systemd.py
The base `InitSystem` used when systemd is not present (or at least
functional), defaults to returning `True` for all probes, in an effort
to not inadvertantly block service queries.
This works well for most scenarios, however it backfires when checking
for runlevel-analogous systemd targets for items such as the `cantboot`
preset - in that the base `InitSystem` will always enable that preset.
Fix that by allowing calls to `InitSystem.is_running()` to specify a
default value to return, instead of blindly always returning `True`.
Similarly, update the preset check to default to `False` to avoid
improperly enabling that preset when systemd is unavailable.
Closes: #2913
---
Please place an 'X' inside each '[]' to confirm you adhere to our …
=> [InitSystem] Allow toggle of default `is_running` result

man/en/sos-clean.1, sos/cleaner/__init__.py, sos/collector/__init__.py, sos/report/__init__.py, tests/cleaner_tests/report_disabled_parsers.py
Adds a new `--disable-parsers` option that allows users to selectively
disable parsers for a given execution of `sos clean`.
This may be useful in specific scenarios where obfuscation is not
strictly needed for all the types of data we obfuscate, and where the
user trusts whomever may be receiving the archive for review.
---
=> [cleaner] Allow disabling specific parsers individually

sos/collector/sosnode.py
The `namespaces` option was presented to `sos collect`, but was not
actually being passed to nodes.
Fix this, and gate the usage of the option to version 4.3, or the
relevant RHEL backport version like we do for `--container-runtime`.
---
=> [sosnode] Properly pass `--namespaces` to nodes

sos/cleaner/__init__.py, sos/cleaner/archives/__init__.py
Previously, there was a small but not impossible situation for a race
condition within `clean`'s handling of symlinks where a symlink name
could be obfuscated differently than what the link's target could be
obfuscated too.
Fix this by handling symlinks separately than the rest of the archive,
like what we do for directory names. When obfuscating files, archives
will now skip over symlinks and yield file names for iteration, rather
than generating and returning full file lists. Once the obfuscation of
"real" files is complete, then separately iterate over symlinks. Since
the file obfuscation also includes file names, this means that link
targets are already known to the mappings and we eliminate the potential
race condition.
Closes: #2852 …
=> [clean] Refactor handling of symlink obfuscation

sos/utilities.py
Changes the `LC_ALL` locale env var used for all command collections
from `C` to `C.UTF-8` which should provide safer/more reliable output
from non-English localizations. This is backed up by PEP-538:
https://peps.python.org/pep-0538/
Closes: #2946
---
=> [utilities] Switch locale to C.UTF-8

sos/policies/distros/__init__.py, sos/policies/distros/redhat.py, sos/policies/distros/suse.py
Removes the `runlevel_by_service()` methods from the redhat and suse
policies, as these methods are both outdated (by trying to leverage
`chkconfig`) and entirely unsued.
Further, removes the `LinuxPolicy.default_runlevel()` method as it is
similarly unused in sos.
---
=> [policies] Remove deadcode around runlevels

sos/policies/distros/redhat.py, sos/policies/distros/suse.py, sos/policies/package_managers/__init__.py, sos/report/plugins/__init__.py, sos/report/plugins/etcd.py, sos/report/plugins/networking.py, tests/unittests/policy_tests.py
As highlighted in #1817, `pkg_by_name()` could provide unpredictable
results, when using wildcards. As such, limited this method to only
returning package info for exact package name matches. In turn, change
`Plugin.is_installed()` to leverage `PackageManager.all_pkgs_by_name()`
which does explicitly support wildcards and returns information on _all_
matching packages, not just the last one found.
In so doing, clean up the `PackageManager` design to use a new
`packages` property for these lookups, and update the former usage of
`all_pkgs()` accordingly. Similarly, signal `get_pkg_list()` should be
private (in any sense that a python method can be) by renaming to
`_get_pkg_list()` and update the single Plugin (`etcd`) referencing this
method.
Closes: #1817
Signed-off-by: Jake Hunsaker …
=> [PackageManager] Make pkg_by_name() more predictable

tests/sos_tests.py
For our CI tests, CPU resources are not guaranteed which in turn can
cause longer-than-expected run times for test executions. In practice,
this is only seen occasionally but it requires manual intervention when
the timeouts are hit (and thus far it has been seen that the changes
these timeouts are hit on are not actually causing the timeouts).
Previous conversations have revolved around improving test efficiency,
however this seems unlikely given the nature of some of the test setup
and further, even with the most efficienct approach possible we would
still be at the whim of resource availability.
As such, increase the default timeout to account for this resource
consideration.
Closes: #2700
---
Please place an 'X' inside each '[]' to …
=> [tests] Increase default timeout

sos/report/plugins/logs.py, tests/report_tests/plugin_tests/logs.py
Removes catalog entries from the journal collection for `this` and
`last` boot collections.
Closes: #2132
---
=> [logs] Drop catalog from `this` and `last` boot

sos/policies/__init__.py, sos/report/plugins/insights.py
Adds collection of `/var/lib/insights` to the `insights` plugin.
There is an `.egg` in this location but rather than individually
skipping it, add a global forbidden path on all eggs.
Related: RHBZ#2103233
---
=> [insights] Collect /var/lib/insights

sos/cleaner/parsers/ip_parser.py, tests/cleaner_tests/skip_version_ip_parser.py, tests/test_data/fake_plugins/skip_versions.py, tests/test_data/tmp/sos-test-version-noskip, tests/test_data/tmp/sos-test-version.txt
For files that can be considered obvious version files - those that end
specifically with either `version` or `version.txt` - skip processing
via the IP parser, as this may lead to improper obfuscation of certain
version strings.
Closes: #2962
---
=> [clean,IP Parser] Skip obvious version files for the IP parser

.cirrus.yml
Updates the images for Fedora to use the stock images on GCE, the CentOS
Stream images to their latest release, and the Ubuntu images to test on
the latest 22.04 LTS release.
---
=> [cirrus] Update GCE testing images

sos/report/__init__.py, sos/report/plugins/__init__.py, sos/report/plugins/ata.py, sos/report/plugins/block.py, sos/report/plugins/fibrechannel.py, sos/report/plugins/nvme.py, sos/report/plugins/scsi.py, sos/utilities.py
Initially, the design behind `add_blockdev_cmd()` made the assumption
that there would (eventually) be separate methods for different kinds of
devices. On review, this is less practical and less maintainable than a
single method, `add_device_cmd()` paired with improved functionality for
handling device lists.
As such, rework `add_blockdev_cmd()` into `add_device_cmd()` and with
it, change the logic on how device lists are sourced. The `devices` dict
handed to plugins now has a top-level separation between device types,
in this revision putting `block` and `fibre` devices under `storage` in
the `devices` dict.
In using `add_device_cmd()`, plugins may now specify either `block`,
`fibre`, or `storage` for both. In addition, any devices passed via the
`devices` parameter that aren't keys in …
=> [Plugin] Refactor add_blockdev_cmd into add_device_cmd

sos/report/__init__.py, sos/report/plugins/__init__.py
The `logging` module does not support non UTF-8 characters, and as such
there was an exception being thrown when trying to log for example a
copied file that has such characters in the file name.
Safeguard against this by converting all messages logged via
`Plugin._format_msg()` to UTF-8, and replace any problematic characters
with `?`s to attempt to preserve context within the logs.
Closes: #2790
---
=> [logging] Safeguard against attempting to log non-UTF characters

sos/report/__init__.py, sos/report/plugins/__init__.py, sos/report/plugins/networking.py, sos/report/plugins/networkmanager.py, sos/report/plugins/teamd.py, tests/report_tests/plugin_tests/networking.py
This patchset first adds enumeration of network devices to the `devices` dict handed to plugins for device iteration. Second, it updates `add_device_cmd()` to allow handling of the `subdir` parameter, and finally it updates various network-related plugins to use `add_device_cmd()` instead of enumerating devices themselves.
---
=> [report,Plugin] Enumerate network devices for plugins

sos/report/plugins/gnocchi.py, sos/report/plugins/openstack_barbican.py, sos/report/plugins/openstack_glance.py, sos/report/plugins/openstack_manila.py, sos/report/plugins/openstack_neutron.py, sos/report/plugins/openstack_novajoin.py, sos/report/plugins/openstack_octavia.py, sos/report/plugins/openstack_placement.py, sos/report/plugins/openstack_trove.py
The memcache_secret_key parameter from the keystonemiddleware library
takes the secret key used to encrypt data stored in memcache, so it is
considered as sensitive information.
Signed-off-by: Takashi Kajinami <tkajinam@redhat.com>
---
=> [openstack] Ensure memcache_secret_key is masked

sos/policies/distros/redhat.py
Simplifies the logic in `dist_version()` to just return the major
version of the `redhat-release` package. This will not only remove a
requirement to update this check for new major version releases, but
also makes the call meaningful on RH-family distros aside from RHEL,
such as Fedora.
Note that this may fail on RHEL 5, but that is not a valid concern as
RHEL 5 does not support python3 and thus should never be in a situation
where sos-4.x+ is installed on such a system.
---
=> [redhat] Simplify `dist_version()` logic

sos/report/plugins/python.py
Updates the python plugin to use `python3` for Ubuntu and Debian
distributions, and locks the use of `platform-python` to RHEL 8 as RHEL
9 does not continue to use of this interpreter executable.
Closes: #2502
---
=> [python] Update version-dependent command for installed version

sos/archive.py, sos/report/plugins/openstack_keystone.py
Fix two new alerts from `flake8` that appear to have gone unnoticed
until a recent update.
---
=> [flake8] Fix new style alerts

sos/report/plugins/__init__.py
Stop logging the contents of strings added via `add_string_as_file()`.
This can ultimately be used via sizelimiting mechanisms, which means we
effectively are writing the entire sizelimited content twice, which can
make the logs needlessly bloated and harder to quickly navigate.
---
=> [Plugin] Don't log content of captured strings

sos/report/plugins/auditd.py
The location of the audit.log files can be changed
in the configuration file /etc/audit/audit.conf.
This change ensures that we capture the log files
when the user specifies a different location via
log_file.
---
=> [auditd] Capture log files when configured to a non default location

sos/policies/distros/redhat.py, sos/policies/distros/ubuntu.py
This currently breaks `python` plugin that does not collect `/usr/libexec/platform-python` on RHEL8.
Resolves: #2997
---
=> [python] proper test for RHEL 8 dist_version

tests/report_tests/plugin_tests/teamd.py, tests/sos_tests.py
Adds a new test case for the `teamd` plugin that also inherently acts to
test team device enumeration.
Included with this test case is an addition to the base test classes
that allows for tests to define a `post_test_tear_down()` method that
will be run at the end of each test execution to allow for manual
cleanup - in this case deleting a 'fake' team device created for the
test.
---
=> [teamd,tests] Add a test for teamd plugin and device enumeration

sos/report/plugins/stratis.py
Update the stratis plugin commands to unclude stopped pools,
the stopped pools and managed object reports, and remove the
collection of the daemon redundancy command which is no longer
supported.
This implements the changes discussed in stratis-storage/project#499
Signed-off-by: Bryn M. Reeves <bmr@redhat.com>
---
=> [stratis] Update plugin commands for stratis-3.x

sos/report/plugins/ceph_mgr.py
This patch adds the following commands to
the Ceph Manager plugin:
- To list hosts:
ceph orch host ls
- To list devices on a host:
ceph orch device ls
- To check the curent specification file/List
services known to orchestrator:
ceph orch ls --export
- To list daemons known to orchestrator:
ceph orch ps
- To check the configured backend and its status:
ceph orch status --detail
- To check service versions vs available and
target containers:
ceph orch upgrade status
- To see the recent activities/log from cephadm:
ceph log last cephadm
Resolves: RHBZ#2116602
---
=> [ceph_mgr] Add orchestrator CLI commands

sos/report/plugins/hpssm.py
Signed-off-by: Trevor Benson <trevor.benson@scality.com>
Command output for both subcommands are included in the output from the `ssacli ctrl all show config detail`, but not of the command output per controller slot. This resolves that discrepancy.
---
=> [hpssm] array and controller show detail subcommands per slot.

sos/report/plugins/elastic.py
Signed-off-by: Trevor Benson <trevor.benson@scality.com>
---
I'm marking all as "compliant". In the past I left it empty when there was no related issues to resolve with the PR. However thinking it over it seems this would then mean both:
- No existing Issue to resolve from this PR
- I did not relate the existing issue to this PR
So in hindsight I presume all boxes should be marked even when no related issues exist, confirming it should be good for review/merge.
=> [elastic] Add the command output for /_cat/indices

.cirrus.yml, tests/report_tests/smoke_tests.py, tests/sos_tests.py
We've built RPMs of each PR in Cirrus for some time, and recently added snaps as well.
We should use these built artifacts for more complete testing than what can be gained from running
from a git checkout of the PR.
This patchset allows the test suite to use a locally installed version of sos instead of forcing the use of the git checkout. This can be leveraged by adding `-p TESTLOCAL=true` to a given `avocado run` command. This is then brought forward in to the tasks run by Cirrus CI, using the rpm and snap built for each PR.
---
=> [tests] Allow testing from local installation, use PR-built packages in Cirrus CI

sos/report/plugins/mysql.py
Adds collection of mysqlrouter config and log files to the `mysql`
plugin.
Closes: #2987
---
=> [mysql] Capture mysqlrouter config and logs

sos/policies/distros/anolis.py
Anolis OS is an enterprise Linux distribution based on RHEL. This adds
a Anolis OS policy, which inherits the RedHatPolicy base and uses the
RedHatPlugin tagging class.
=> [policies] Add Anolis OS policy

.cirrus.yml, tests/cleaner_tests/report_disabled_parsers.py, tests/cleaner_tests/report_with_mask.py, tests/report_tests/encryption_tests.py
The Fedora 36 image is now available on GCP, so update our testing
matrix to use it. Accordingly, this means we no longer need to build or
maintain our own Fedora images going forward.
---
=> [cirrus] Update Fedora images used in CI tests

sos/cleaner/__init__.py
The domain parser is built to understand actual names, e.g.
'example.com', and not operate off of just 'example' despite the fact
that the parser handles TLDs separately.
To safeguard against potential errors when trying to parse the latter
example above as an actual domain, validate any values passed to
`--domains` during cleaner initialization.
---
=> [cleaner] Check --domains values for validity

sos/policies/distros/cos.py
Policies when initialized it only contains independent plugin, adding
CosPlugin while initializing the CosPolicy
Signed-off-by: Varsha Teratipally <teratipally@google.com>
---
=> [COS] add-remote-exec-arg-to-COS-policy-and-COSPlugin-to-valid-subclass

sos/cleaner/mappings/hostname_map.py, tests/unittests/cleaner_tests.py
Hostname parser works with stripped leading/trailing '.' and '_' characters for a match. When no pattern match is found, we must return the original unstripped item.
Resolves: #3022
---
=> [cleaner] Prevent stripping '_' on no match in hostname parser

sos/cleaner/__init__.py, tests/cleaner_tests/unicode_in_file.py, tests/test_data/fake_plugins/unicode_test.py, tests/test_data/tmp/sos-test-unicode.txt
A scenario was found that if a file had encoding issues when `sos clean` went to open the file for obfuscation, we would stop processing the file but leave it in the archive, which had the potential to leave unobfuscated information in that file in the archive.
Fix this, by using the `errors='replace'` parameter when opening archive files. This allows us to continue parsing the file normally, while replacing the problematic characters with `?`s.
Closes: #3015
---
=> [cleaner] Replace encoding errors when opening files

requirements.txt, setup.py, sos.spec, sos/utilities.py
For compatibility reasons on some distros, sos should not have a hard dependency on 'magic' python library. It should attempt to use it for detection of binary file content, but should fall back to previous "read the very first byte" method otherwise.
Resolves: #3025
Relates: #3021
---
=> [utilities] Relax from hard dependency of python3-magic

sos/cleaner/mappings/__init__.py, sos/cleaner/parsers/username_parser.py
In some configurations, we can expect usernames to be written as `DOMAIN\user`, as well as the plain `user` form. Previously, the domain-prefixed format would throw an exception in our obfuscation if the letter after the `\` would cause the interpreter to regard that as a special character.
Fix this by escaping the values passed to `get_regex_result()` so that we can successfully compile a regex pattern object for domain-prefixed usernames as well.
Further, when we encounter one of these usernames, the username parser should automatically add an entry for the non-prefixed username as well. While this will result in a secondary obfuscation match (due to the current design of `sos clean`), this is preferable to potentially leaving non-prefixed usernames in plaintext, if they happen to …
=> [clean,username_parser] Handle usernames with domain prefixes

.cirrus.yml, tests/test_data/foreman_setup.sh
Foreman has made several releases since we initially added integration testing for it. Rebuilding the images is maintenance overhead we can reduce by automating the installation of foreman on images.
Provide this scripted installation, and expand our testing matrix to additional versions of Foreman. As of this commit, we will be testing versions 2.5 and 3.1 on CentOS Stream 8 to cover Red Hat Satellite features, as well as Foreman version 3.4 (the latest current upstream) for CentOS 8 and Debian 11.
---
=> [cirrus|foreman] Expand Foreman testing matrix, automate install

.cirrus.yml, snap/snapcraft.yaml
core20 has python3-magic 0.4.15, and hence the binary detection will not work by default. Moving to core22 goes to 0.4.24-2 which would mean this would work nevertheless
---
=> [snap] Update base to core22

sos/policies/package_managers/__init__.py, sos/policies/package_managers/dpkg.py, sos/policies/package_managers/rpm.py, sos/report/__init__.py, sos/report/plugins/__init__.py, sos/report/plugins/gcp.py, sos/report/plugins/process.py, sos/report/plugins/python.py, sos/report/plugins/unpackaged.py, tests/report_tests/plugin_tests/collect_manual_tests.py, tests/report_tests/plugin_tests/collet_manual_tests.py, tests/unittests/plugin_tests.py
This patchset implements changes that allow plugins to perform manual data collections/compilations that will get saved in the archive alongside normal command output collections.
First, adjust the behavior of collecting `tail`s of file specs that exceed the given log size so that it is no longer performed during `setup()`, but instead the actual collection takes place during the collection phase.
Second, renamed the `collect()` method to `collect_plugin()`, and implement `collect()` as a new entry point for plugin authors to define their manual collections.
The patches following the first two adjust existing plugins to use this new functionality. Additionally, the `process` plugin has been updated to collect a pid->package mapping, as has been long requested in #1350. This includes an …
=> [Plugin] Allow plugins to perform manual collections

sos/report/plugins/__init__.py
For any kernel modules specified as a plugin enablement trigger via `kernel_mods`, we should automatically collect `modinfo` output for those modules, much like we do with journals for units that are specified for the `services` plugin enablement trigger.
---
=> [Plugin] Collect `modinfo` output for `kernel_mods` enablement trigger

sos/report/plugins/composer.py
lorax was deprecated a while ago; [osbuild/osbuild-composer](https://github.com/osbuild/osbuild-composer) is the reimplemenation which is actively maintained.
I left lorax files in there just in case, happy to remove them if that's preferred. Also happy to squash in case the commits are too small.
---
=> [composer] Update plugin for OSBuild Composer

sos/cleaner/parsers/mac_parser.py, sos/report/plugins/__init__.py, sos/report/plugins/firewall_tables.py, sos/report/plugins/nvme.py, sos/report/plugins/xfs.py
This patchset first refines the mac parser's file skipping to skip all `modinfo` commands, instead of just the one from the kernel plugin.
Second, it updates several plugins to define modules in their respective `kernel_mods` enablement trigger, which will also cause separate `modinfo` collections within those plugins per #3037 
---
=> [mac_parser, plugins] Refine parser skipping, add kmods to plugins

sos/report/plugins/krb5.py, tests/report_tests/plugin_tests/krb5.py
It was found that the `krb5` plugin was not executing on Ubuntu/Debian systems due to a legacy change that inadvertently removed support for those distributions.
Re-enable support by defining a new plugin class for those distros, setting the kdc directory appropriately. Additionally, expand the package tuple to include newer package names.
Closes: #3041
---
=> [krb5] Enable on Ubuntu/Debian, expand package tuple

.cirrus.yml
The stagetwo tests are getting closer to consistent 30 minutes timeouts, with centos 8 generally hitting the timeout most often among the stagetwo tests. This is mostly due to the inefficient way in which we dump 100MB into the system journal in order to test journal size limiting.
As a stopgap measure until we can figure out a better/more reliable way to artificially increase the journal size, increase the timeout of these tests to avoid unnecessary re-runs which would otherwise pass.
---
=> [cirrus] Increase stagetwo timeout

sos/report/plugins/ovn_central.py
Debian & Ubuntu OVN packages store the ovsdb files in /var/lib/ovn
Signed-off-by: Trent Lloyd <trent.lloyd@canonical.com>
---
=> [ovn_central] Add ovsdb directory for Ubuntu

snap/snapcraft.yaml
The python environment for core22 is python3.10. The environment needed changing accordingly.
core20 and core22 snapcraft doc suggests that python3-venv needs to be added for the python
plugin to work effectively
Partial fix for #3044 
---
=> [snap] Fix python env

sos/component.py, sos/report/__init__.py, sos/report/plugins/__init__.py, sos/report/plugins/ssh.py, tests/report_tests/basic_report_tests.py, tests/report_tests/plugin_tests/collect_manual_tests.py
Red Hat Insights is looking to better leverage sos tags to satisfy their own specs for rules and such. Currently, tags are added directly to collections, which presents a scalability problem when iterating through a report's collection manifest for a large number of rules.
Mitigate this by compiling a "tag summary" within the report manifest, which collates a dict whose keys are all existing tags for collections existing within that report, and whose values are lists of every file (be it file copied or command output collection) in the report that has that tag.
---
=> [manifest,Plugin] Create a tag summary within a report's manifest

sos/cleaner/parsers/hostname_parser.py, tests/unittests/cleaner_tests.py
Hostname parser treats strings like 'host.domain.com' with precompiled domain 'domain.com' in a wrong way. It first obfuscates the domain while subsequent _parse_line skips host obfuscation.
Calling _parse_line before _parse_line_with_compiled_regexes does clean both the host name and the domain name well.
Adding a unittest with a reproducer.
Resolves: #3054
---
=> [cleaner] Apply compile_regexes after a regular parse line

sos/report/plugins/ovn_central.py
In order to automate the parsing of the plugin output files, by systems could only read file contentit, seems useful to add an output cmd file where data, such as the size or permissions, of the OVN DBs is directly available.
This patch modifies the current behaviour to copy the db files of each OVN DB to create a file containing the ls -lan output of the files. The list of possible locations of these *.db files is maintained for backwards compatibility but it has been necessary to iterate over them to only obtain the information file of those that really exist.
---
=> [ovn_central] Add commands to get OVN DBs file information

sos/report/plugins/pulpcore.py
Since PASSWORD can be in a one-liner list, we must mark the password value in a non-greedy manner until first ',' or '}' is found.
This works well also for multi-line lists where any line terminates by a comma.
Resolves: #3058
---
=> [pulpcore] obfuscate PASSWORD in non-greedy manner

.github/workflows/snap.yaml
Add concutrrency to the job, so that if there is one already running, then that would be cancelled
Remove the deb package, and that takes precedance with the path do the test doesn't quite work
---
=> [build] add concurrency to workflow

.github/workflows/snap.yaml
The environment for the build doesn't seem to be refreshing between runs, and hence sos from the snab binary location is not working. Having the full path ensures that this doesn't fail
---
=> [build] use full path for snap check

.github/workflows/snap.yaml
When installing via --danegerous, the aliases are not done automatically, so create he sos alias, so that we can run via "sos report"
---
=> [build] Require the sos alias

sos/report/__init__.py
When moving sos tarball from a private directory to /var/tmp, apply filename obfuscation just to the file and not the tmpDir path itself.
Resolves: #3065
---
=> [report] Prevent obfuscating tmpDir path before tarbal move

sos/report/__init__.py
Likewise #3065, we should not obfuscate path to directory when --build option is used.
Resolves: #3071
Relates: #3065
---
=> [report] Prevent obfuscating tmpDir path also in --build mode

sos/report/plugins/dnf.py
Currently the dnf plugin scrubs passwords from the repository files and DNF variables, however "password" and "proxy_password" can be defined in "/etc/dnf/dnf.conf".
This patch ensures that passwords are scrubbed from dnf.conf too.
Example of scrubbing:
Before:
proxy_password = hackme
After:
proxy_password = ********
Resolves: #3072
Signed-off-by: Stepan Broz <sbroz@redhat.com>
---
=> [dnf] Scrub passwords from dnf.conf

sos/report/plugins/autofs.py
The XML configuration file /etc/autofs_ldap_auth.conf may contain
an authentication secret in the <autofs_ldap_sasl_conf/> tag.
This patch makes sure the secret gets scrubbed.
Example of scrubbing of the secret:
`secret="hackme"`
or
`secret='hackme'`
to:
`secret="********"`
or
`secret='********'`
Signed-off-by: Stepan Broz <sbroz@redhat.com>
---
=> [autofs] Scrub autofs_ldap_auth secrets

sos/report/plugins/virsh.py
Implement the virsh sub-command `nodedev-list --tree` and `nodedev-dumpxml` to virsh plugins.
Resolves: #3079
Signed-off-by: Han Han <hhan@redhat.com>
---
=> [virsh] Collect the node device info

man/en/sos-clean.1, sos/cleaner/__init__.py, sos/cleaner/mappings/__init__.py, sos/cleaner/mappings/ipv6_map.py, sos/cleaner/parsers/ipv6_parser.py, tests/unittests/cleaner_tests.py
This commit adds a new parser and accompanying map for obfuscating IPv6 addresses.
This new parser will attempt to capture valid IPv6 networks and addresses, and produce a mostly-randomized obfuscated pair. Due to the multiple formats an IPv6 address can take, some identifiers are necessary to preserve relevant information while still obfuscating actual addresses and networks.
For example, global unicast addresses that have more than one defined hextet (greater than /16 prefix) will always generate an obfuscated address starting with `534f` (or 'so', continuing the style of our mac address handling that uses 'sos' as an identifier). Addresses with a /16 prefix or less, will start with simply '53'. Private addresses, which start with `fd` will generate an obfuscated address starting with …
=> [cleaner,ipv6] Add support for IPv6 obfuscation

man/en/sos-collect.1, sos/collector/__init__.py, sos/collector/sosnode.py
Removes the `--sos-cmd` option for `sos collect`. Allowing passthru options in this manner is inherently flawed, and any attempts at sanitizing potentially malicious/dangerous values will always be a losing battle. Instead, `sos collect` should leverage available `report` options that are vetted and handled via the existing per-node capabilities checks that is well-defined for explicit passthru options.
---
=> [collect] Remove --sos-cmd option

sos/report/plugins/openstack_instack.py, sos/report/plugins/openstack_mistral.py
Logs as well as deploy information are located in /var/lib/mistral as well. Until now, this location was overlooked, and important information about the deploy state, configuration and potential errors were missing from the initial SOS-Report, leading to time loss for both Customer and Support.
This patch intends to correct this situation, by ensuring the content is taken from the Undercloud.
Notes:
- this is especially important for OSP<17.0
- the location may content multiple subdirectories
- the location will contain the history of the different actions done by the operator
---
=> [openstack_mistral] Collect mistral content itself

.packit.yaml
Packit is moving srpm builds from sandbox to copr, which means we need to specify the build dependencies for packit to know how to create the build environment.
As part of this change, re-organize the config file to be easier to read, and update some of the deprecated keys or nesting per docs.
---
=> [packit] Update packit configuration for Copr srpm builds

sos/collector/__init__.py, sos/collector/clusters/__init__.py, sos/collector/clusters/ceph.py, sos/collector/sosnode.py
Adds a new cluster profile for RHCS 5 for `sos collect`. This profile depends upon the use of `cephadm` which is used to both deploy and manage the cluster. Users may optionally restrict the list of nodes to collect from by using the `-c ceph.labels` option to specify a set of label(s) to filter node results with.
---
=> [ceph] Add new collect cluster profile for RHCS5

sos/report/plugins/ceph_common.py, sos/report/plugins/ceph_mds.py, sos/report/plugins/ceph_mgr.py, sos/report/plugins/ceph_mon.py, sos/report/plugins/ceph_osd.py, sos/report/plugins/ceph_rgw.py
This patchset first corrects an overall issue with the enablement of the ceph plugins for newer versions of Ceph, and then delves into updating the individual plugins to ensure collections remain consistent with expectations across those ceph versions.
---
=> [ceph] Update Ceph plugins for newer versions of Ceph

sos/collector/__init__.py
The changes in respecting strict_node_list are three-fold:
1) Don't add local hostname among "list of nodes to collect from:"
2) Skip explicit adding of the primary node to client_list
3) Don't reduce_node_list (as it can purge away local host e.g. in case   of IP address node)
Resolves: #3096
---
=> [collector] Prevent appending local host in strict_node_list mode

sos/report/plugins/__init__.py
The string or strings are treated as globs, not regular expressions.
---
=> Fix docstring for copyspecs param in add_copy_spec

sos/collector/sosnode.py, sos/policies/__init__.py, sos/policies/package_managers/__init__.py
Previously, remote command executions handled by policies were done by moodifying the command string based on the `remote_exec` property of the given `SoSTransport` in use for the node that the policy was loaded for.
While this worked well for SSH connections, newer transports may need to do some manipulation of returned data in order for the rest of `sos collect` to function as intended.
As such, switch to directly using a transport's `run_command()` method, which will ideally handle any needed manipulations of either how the command is execute and/or how the returned data is presented to the calling component.
Related: #3087
--- …
=> [policies] Directly use a Transport for remote commands

sos/collector/__init__.py, sos/collector/clusters/__init__.py, sos/collector/clusters/ocp.py, sos/component.py, sos/report/__init__.py, sos/report/plugins/gluster.py, sos/utilities.py, tests/sos_tests.py
One such change is already done in https://github.com/sosreport/sos/pull/3106 .
Resolves: #3109
---
=> Replace deprecated Logger.warn by Logger.warning

bin/sos, sos/utilities.py
[seagate_ses] Add timeout for fwdownloader in seagate_ses plugin.
Recently, I found the **fwdownloader -ses**  command would never finish sometime when run sos report .
It will cause sos report hang.  
I have manual test in my environment , The parameter plugin_timeout can't restrict plugin execution time if the inside command execution time over plugin_timeout.
Here is invoke stack when hang problem occurred.
=> cmd fwdownloader may never end sometimes, add timeout for it

.gitignore, requirements.txt, setup.py, sos.spec, sos/collector/sosnode.py
2-patch set that first updates `setup.py` to use setuptools, and second replaces the usage of `LooseVersion` with `parse_version` for the purposes of comparing sos versions for option compatibility with `collect`.
As noted in the commit message, and specified in #3093, this conversion will stop compiling `.mo` translation files for packaged releases. However, this is currently seen as acceptable as the compiled translations have been found to be currently broken anyways.
---
=> [build] Convert to setuptools

sos/policies/distros/debian.py
Add all the new versions since 7, and update name/versions based on
https://wiki.debian.org/DebianReleases. Checked latest bookworm and
the release string was in /etc/debian_version, but
/etc/debian_version was inconsistent on other versions.
/etc/lsb-release didnt exist by default.
grab the codename from /etc/os-release and base the versions from
there
forky and trixie and not out yet, but added as per the releases page
for future proofing.
Closes: #2691
---
=> [policy] Update new debian versions

sos/cleaner/mappings/ipv6_map.py
Fix a corner case in separating host address from an IPv6 address when the host string is (substring of) the network address string.
Resolves: #3121
Relevant: #3120
---
=> [cleaner] Improve separating host from IPv6 address

sos/policies/distros/__init__.py, sos/policies/distros/redhat.py
Since prompting for upload username/password relies on case_id for some policies, let fully set case_id before that.
Resolves: #3117
---
=> [policies] set case_id before prompting for upload credentials

sos/report/plugins/ceph_mgr.py, sos/report/plugins/ceph_mon.py, sos/report/plugins/ceph_osd.py
This supersedes #3103.
Simplify the log collection condition by introducing a file glob. It can capture logs from both existing clusters such as package based deployments and container based deployments such as cephadm.
Closes: #3100
Co-authored-by: Samuel Walladge <samuel.walladge@canonical.com>
Signed-off-by: Nobuto Murata <nobuto.murata@canonical.com>
---
---
Testing procedure:
```bash
./bin/sos report --batch --build -n fwupd --label "<LABEL e.g. 4.4>"
grep -c 'plugin:ceph.* collecting path ' /tmp/sosreport-*-LABEL-*/sos_logs/sos.log
grep -c 'plugin:ceph.* collecting output ' /tmp/sosreport-*-LABEL-*/sos_logs/sos.log
```
Testing …
=> [ceph] Accommodate both running on host and containers

sos/report/plugins/ceph_common.py
Updates the log patterns for `ceph_common` to handle Ceph versions that use or don't use fsid's as part of the logging paths.
Related: #3122
---
=> [ceph_common] Update log patterns for multiple ceph versions

sos/report/plugins/ovn_central.py
When a list of command are sent to run on a container the output is
printed to file on sos_commands/<plugin> folder, but also a symbolic
link is created from the sos_container/<container> file to the
sos_commands/<plugin> file. When a command is duplicated, we get an
exception on the plugin and the rest of commands are not executed.
This patch removes some hardcoded commands, and clean the list from
duplicated commands before sending to the container.
---
=> [ovn_central] Remove duplicate commands

.cirrus.yml, snap/snapcraft.yaml, sos/collector/clusters/pacemaker.py, sos/collector/sosnode.py, sos/utilities.py
When the snap is being packaged via core22, it used python3.10
but bionic used python3.6 and seems have runtime issues there.
Added the sos alias for testing, to ensure that when the stage
one testing is done, that sos is correctly tested within the
snap
This alternative ensures that the packaging module is packaged
in the snap, and can use this if the pkg_resources version does
not work
Add a wrapper function in utlities, so that the parse_version
can be used in a consistent way across the sos project
Closes: #3126
---
=> [snap][testing] Fix bionic snap runtime

sos/report/plugins/__init__.py
Every output of a command run on a container is saved in the 
sos_commands folder, also additionally a symbolic link is created from 
the sos_container folder to link the container where it was run to the 
output file. When there is a duplicated command on the list to be run 
on the container, the symbolic link creation will fail due to file 
already exists error.
To avoid this error we can trust on the check_path 
method, that will give us a clue avoid if the file already exists or 
not to continue with the symbolic link creation.
Closes #3131
---
=> [Plugin] Avoid overwrite existing symbolic link for a command output

sos/report/plugins/ceph_iscsi.py
Along with existing Ceph plugins, Ceph iSCSI gateway use case requires additional config and log files to be analyzed.
https://docs.ceph.com/en/latest/rbd/iscsi-overview/
Closes: #3098
Related-Bug: https://bugs.launchpad.net/ubuntu/+source/sosreport/+bug/2000672
Signed-off-by: Nobuto Murata <nobuto.murata@canonical.com>
---
=> [ceph] add iSCSI gateway

tests/unittests/cleaner_tests.py
Add unit test for #3030.
Relevant: #3030
Resolves: #3135
---
=> [tests] Add test for AD username obfuscation

tests/cleaner_tests/basic_function_tests/report_with_mask.py
Add test for #3071 : Prevent obfuscating tmpDir
Resolves: #3136
---
=> [tests] Add test for #3071

sos/report/plugins/rhui.py
Scrub registry_password value in /etc/rhui/rhui-tools.conf
Relevant: rhbz#2170893
Resolves: #3138
---
=> [rhui] Obfuscate registry_password in rhui-tools.conf

sos/report/plugins/rhui.py
registry_passwords occur in rhui-tools.conf (#3138) but also in (backups of) answers.yaml files.
Relevant: #3138
Resolves: #3140
---
=> [rhui] Obfuscate registry_password from answers files

sos/component.py, sos/report/__init__.py
sos report should print generated sosreport directory or tarball or etimate of size even with --quiet option.
Resolves: #3142
Closes: #3143
---
=> [report] Print work outcome even in quiet mode

sos/report/plugins/composer.py
/etc/osbuild-composer contains customizations users create for Image Builder. This directory
is not currently owned by any package but if present, it, and all files inside, should be 
gathered as well.
Related: RHBZ#2169776
---
=> [composer] Capure /etc/osbuild-composer file

sos/report/plugins/frr.py
FRR is deployed in a container for certain (RH)OSP deployments. As such, the `frr` plugin should attempt to collect various command outputs from that container if it exists.
---
=> [frr] Add vtysh command collection

sos/report/plugins/microshift.py
Use `oc get` instead of `microshift get`, which got dropped before the release.
Add `show-config` and `version` commands to the report.
---
=> [microshift] Fix microshift get and add commands

man/en/sos-report.1, sos/collector/__init__.py, sos/collector/sosnode.py, sos/report/__init__.py, sos/report/plugins/__init__.py, tests/report_tests/plugin_tests/logs.py
Historically, journal sizes have been limited to the *higher* of 100MB or `--log-size`. While this had the benefit of potentially controlling both logs and journals with the same option, it was not immediately intuitive to end users and downright prevented collecting less than 100MB of journals.
Address this by separating journal size limiting from `--log-size` by adding a new `--journal-size` option (default 100). This will allow users to individually control journal sizes without any "gotcha" scenarios with relation to general log size limiting.
---
=> [report,plugin] Control journal size separate from log-size

sos/report/plugins/__init__.py, sos/report/plugins/candlepin.py, sos/report/plugins/cman.py, sos/report/plugins/foreman_installer.py, sos/report/plugins/fwupd.py, sos/report/plugins/gnocchi.py, sos/report/plugins/landscape.py, sos/report/plugins/ldap.py, sos/report/plugins/logs.py, sos/report/plugins/mongodb.py, sos/report/plugins/monit.py, sos/report/plugins/openhpi.py, sos/report/plugins/openstack_horizon.py, sos/report/plugins/openstack_instack.py, sos/report/plugins/openstack_keystone.py, sos/report/plugins/openstack_novajoin.py, sos/report/plugins/openstack_tripleo.py, sos/report/plugins/origin.py, sos/report/plugins/ovirt.py, sos/report/plugins/rear.py, sos/report/plugins/redis.py, sos/report/plugins/saltmaster.py, sos/report/plugins/ssmtp.py, sos/report/plugins/tomcat.py
File content substitutions done via do_file_sub will newly work case insensitive. This simplifies detection and description of sensitive content, while a risk to obfuscate a regular content is pretty low.
The change is followed by simplification of do_file_sub and do_path_regex_sub calls in individual plugins, and also making them more generic: bfuscated string should not contain explicit case-sensitive key, but \1 rather, to prevent unintentional change of case of the key.
Closes: #3070
Resolves: #3156
---
=> [report] Ignore case when scrubbing via do_file_sub

man/en/sos-report.1, sos/collector/__init__.py, sos/collector/sosnode.py, sos/policies/distros/__init__.py, sos/report/__init__.py, tests/report_tests/low_priority_tests.py
Adds a new `--low-priority` option to report, which will attempt to constrain the process priority for the report generation. We do this by attempting to set ourselves to an 'idle' IO class, as well as setting our niceness to 19 to avoid contending for CPU time.
This is also exposed via `sos collect`, however users should note that this will not be effective until the sos-4.5.1 release.
Closes: #3127
---
=> [report] Allow users to constrain sos process priority

sos/report/plugins/powerpc.py
This patch is to update powerpc plugin to collect
lparnumascore logs.
lparnumascore displays the NUMA affinity score for the running LPAR.Following commands are added
lparnumascore
lparnumascore -c cpu -d 4
lparnumascore -c mem -d 3
Suggested-by: Laurent Dufour <ldufour@linux.ibm.com>
---
=> [powerpc]: To collect lparnumascore logs

sos.spec
Removes the lingering dependencies on `tar` and `xz` from `sos.spec`, as we have for some time now stopped shelling out to those tools and instead have leveraged their native python modules.
---
=> [build] Drop old dependencies from sos.spec

sos/report/plugins/subscription_manager.py
Make sure that passwords are scrubbed from files in /var/lib/rhsm/repo_server_val.
Example of scrubbing:
proxy_password=hackme
To:
proxy_password=********
Whitespace around '=' is allowed.
Fixes: #3163
---
=> [subscription_manager] Scrub proxy passwords from repo_server_val

tests/cleaner_tests/basic_function_tests/report_with_mask.py, tests/vendor_tests/redhat/rhbz1950350/sos.conf
When running avocado tests in a sequence on the same host, further tests are affected by cleaner default_mapping built from obfuscating specific keywords also. Prevent adding those keywords to the mapping.
Resolves: #3165
---
=> [tests] Call cleaner with --no-update when using keywords

sos.spec
Migrated License field to SPDX format as defined in
https://docs.fedoraproject.org/en-US/legal/update-existing-packages/
---
=> [spec] migrated to SPDX license

sos/report/plugins/logs.py
Previously, the way the distro tags were applied to the `Logs` and the `CosLogs` variant, the `CosLogs` plugin would be used for every distribution.
Fix this by separating an `IndependentLogs` class and marking the actual plugin content as a "base" plugin to build upon, and have the `CosLogs` plugin continue to subclass the base plugin, without inheriting the `IndependentPlugin` subclass.
Do this rather than folding the `CosLogs` plugin and `log_days` option back into the main `Logs` class as CoS seems to prefer an exported binary journal rather than the standard text output favored by other distributions.
Closes: #3166
---
=> [logs] Fix loading of CosLogs variant for every distro

sos/presets/__init__.py
Adds a new 'minimal' preset that serves to provide a minimal set of data for analysis. This involves reducing plugin/command timeouts and log/journal collection sizes. The `--low-priority` option is also enabled to further reduce system resource usage during report execution.
Close: #2686
---
=> [presets] Add new 'minimal' preset

sos/component.py, sos/report/__init__.py
When a loaded preset sets verbosity, we should just set it to relevant loggers without redeclaring or adding new ones.
Resolves: #3149
Closes: #3171
---
=> [report] Set log verbosity from presets properly

sos/report/plugins/ceph_mgr.py
Capture the output of some ceph mgr commands in json 
format, and add a new command to be collected.
Related: RHBZ#2116602
---
=> [ceph_mgr] Gather some commands in json format

sos/report/plugins/virsh.py
The virt-manager logs in /root/.cache/virt-manager/*.log and /root/.virt-manager/*.log may contain display spice passwords.
This patch ensures those are scrubbed off correctly.
Example of scrubbing:
passwd="hackme"
To:
passwd="******"
Resolves: #3181
---
=> [virsh] Scrub passwords in virt-manager logs.

sos/policies/distros/ubuntu.py
Ubuntu policy is missing a `return`  in `get_upload_url()` method that causes the upload to be implictly disabled when `--upload-url` is specified.
Closes: #3183
---
=> [ubuntu] Fix missing return in ubuntu policy

sos/component.py
When preset disables a plugin that user wants to manually enable, current merging of options ends up with -e PLUG -n PLUG which makes the plugin still disabled.
apply_options_from_cmdline method must remove the preset options for any plugin that interfere with cmdline options for the plugin.
Resolves: #3195
---
=> [report] Honour -o/-e/-n from cmdline over preset

sos/report/plugins/powerpc.py
This patch updates powerpc plugin to collect the slots and active memory sharing information and opal elogs.
Reported-by: Borislav Stoymirski <borislav.stoymirski@bg.ibm.com>
Tested-by: Borislav Stoymirski <borislav.stoymirski@bg.ibm.com>
=> Add Support to collect lsslot,amsstat,opal-elog-parse logs.

.cirrus.yml
F38 has been GA, so we should move off the Beta image for our testing.
---
=> [cirrus] Move F38 image from Beta to GA

tests/product_tests/foreman/foreman_tests.py, tests/sos_tests.py
Adds a new `arch` class attr that allows test classes to specify which architecture(s) they are allowed/designed to execute on. If the test is attempted to be executed on an architecture that is not in the specified list, we will skip the test before any setup or sos executions are done.
By default, the `arch` class attr is an empty list, which implies that the test can run on _any_ architecture. Tests should specify `arch` as a list even for single-arch tests.
Included in this change is restricting the Foreman tests to x86_64 only, as that is the only architecture on which that product is supported.
Closes: #3186
---
=> [tests] Allow tests to restrict execution architecture

sos/report/plugins/networkmanager.py
By default "nmcli con" only shows few fields of connections; many others are skipped and some of them are quite important like the filename, the autoconnect flag, and the last activation timestamp.
Add the full dump of connection fields. Since the output can be harder to quickly parse, also leave the plain "nmcli con" output.
---
=> [networkmanager] collect all fields of connections

sos/policies/package_managers/__init__.py, sos/policies/package_managers/dpkg.py, sos/policies/package_managers/rpm.py, sos/policies/package_managers/snap.py, sos/report/plugins/networking.py, tests/unittests/policy_tests.py
Adds a new `MultiPackageManager` class to handle systems that have multiple distinct package managers on them.
This initial implementation requires policies that will leverage this to define a `primary` package manager, and at least one fallback package manager. Policies will need to pass the uninstantiated class object to the initializing call to `MultiPackageManager`, for example:
self.pkgman = MultiPackageManager(primary=RpmPackageManager,
fallbacks=[DpkgPackageManager])
When a call to a `PackageManager` method is made to `MultiPackageManager`, the call is first directed to the primary manager. If that response is empty, None, etc... then the call is forwarded to each of the fallback managers in the order they were defined, until either a non-empty response is returned or we run out of …
=> [package_managers] Add MultiPackageManager support for policies

sos/report/plugins/networking.py
With this PR we are deprecating `route` command in favour of `ip route`.
We are also creating a single root symlink `ip_route` that will contain
aggregated IPv4 and IPv6 routes.
Closes: #3220
---
=> [networking] Collect IPv4 and IPv6 routes

sos/report/plugins/networking.py
Since some sysctl groups (e.g net.*) are namespaced, when gathering namespace data it's important to include the sysctl information as well.
Resolves: #3232
---
=> [networking] Collect `sysctl -a` from namespaces

sos/policies/package_managers/snap.py
The __init__ was not required, so removing it
---
=> [pm][snap] remove __init__

sos/report/plugins/apt.py
The /etc/apt/sources.list or files in /etc/apt/sources.list.d may have credentials for private repositories. This change should mask the files and remove the username and the password.
Resolves: #1514
---
=> [apt] mask credentials in list files

sos/component.py, sos/policies/distros/redhat.py
2-patch set first allows `ui_log` to print debug level messages if verbosity is set high enough, and second adds debugging output to failed SFTP uploads when using the RHEL policy.
---
=> [redhat] Add debugging output to failed SFTP uploads

sos/collector/__init__.py
When sos is running on primary node with hostname listed in node_list, collect report from the node (until strict node option prohibits it).
Resolves: #3240
Related: rhbz#2186460
---
=> [collector] collect report from primary node if in node_list

sos/report/plugins/rhui.py
Fix small typo while obfuscating cookies.
---
=> [rhui] Fix small typo while obfuscating cookies

sos/report/plugins/kernel.py
After a kernel panic, /sys/fs/pstore data is backed off to /var/lib/systemd/pstore which should be collected as well.
Resolves: #3244
---
=> [kernel] collect /var/lib/systemd/pstore

sos/report/plugins/powerpc.py
Resource Monitoring and Control (RMC) responsible for establishing management connection between HMC (Hardware Management Console) and Logical partition (LPAR).
Add commands to collect the status/info of RMC service, node, and other system resource. Additionally collect RSCT node ID file.
---
=> powerpc: collect RMC status logs

sos/report/plugins/juju.py
Currently, it was inconsistent with the hidden file collection, this line ensures that we collect these files for better support
Closes: #3242
---
=> [juju] Ensure to collect hidden files

sos/report/plugins/rhc.py
RHC is a client tool and daemon that connects the system to 
Red Hat hosted services enabling system and
subscription management. This plugin captures
configuration files and the output of 'rhc status'.
Closes: RHBZ#2196649
---
=> [rhc] New plugin for RHC

sos/report/plugins/microk8s.py
Add a new plugin to support collecting data from microk8s on Ubuntu.
---
=> [microk8s][ubuntu] Add microk8s plugin

sos/report/plugins/foreman.py
When katello-agent is (still) enabled, "qpid-stat -q" provides a great overview of pending requests and connected agents.
As there is no katello plugin, we must collect it in foreman directly.
Resolves: #3251
---
=> [foreman] collect qpid-stat -q

sos/archive.py, sos/report/plugins/__init__.py, tests/unittests/plugin_tests.py
If we make an `add_copy_spec()` call to a file that is a symlink, and we are running in a container such that the host's `/` filesystem is one we leverage as our `sysroot`, if the symlink uses a short relative path, we were inadvertently copying the location with the container, rather than tracking the relative location to be from the sysroot path.
Fix this by forcing the use of the sysroot path in the event that we are executing from a container, and only if we are executing from a container as far as the loaded Policy is concerned.
Resolves: rhbz#2075720
---
=> [Plugin|Archive] Fix handling of symlink resolution within containers

.cirrus.yml, sos.spec
Adapt the specfile to new fedora packaging guidelines.
- use pyproject macros (see also https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_example_spec_file )
- use bin instead of sbin (see also [rhbz#2210708](https://bugzilla.redhat.com/show_bug.cgi?id=2210708)
Based on top of PR #3259
---
=> [specfile] new fedora guidelines

sos/report/plugins/apache.py
httpd.conf can refer to files in either conf.d or directly in conf dir, so let collect all configs by default.
Resolves: #3264
---
=> [apache] collect all /etc/httpd/conf/*.conf files

sos/report/plugins/lxd.py, sos/report/plugins/maas.py
Remove `check_enabled()` for the maas plugin, as that is now not required with `SnapPackageManager` now enabled for the `UbuntuPlugin`
Use package manager to detrmine is package is a snap rather than `snap list`
---
=> [pm] Update plugins to use package_manager

sos/report/plugins/cxl.py
Compute Express Link (CXL) is an industry-supported Cache-Coherent Interconnect for Processors, Memory Expansion, and Accelerators.
The CXL Consortium (https://www.computeexpresslink.org/) is an open industry standard group formed to develop technical specifications that facilitate breakthrough performance for emerging usage models while supporting an open ecosystem for data center accelerators and other high-speed enhancements.
There are currently three specifications (v1.1, 2.0, and v3.0) publicly available. CPUs are available from Intel and AMD that support CXL v1.1. Hardware is emerging that supports up to CXL v3.0.
This plugin uses open-source utilities from
https://github.com/pmem/ndctl that introduce new and updated commands to support CXL devices in the Linux Kernel.
---
Please …
=> [cxl] Add a new Compute Express Link (CXL) plugin

sos/report/plugins/__init__.py
Now that we ae using flags in re.subn, it doesn't like the full pattern that is being passed through via do_file_private_sub. So, we separete pattern and the flags, and pass these through to re.subn
Closes: #3261
---
=> [report] Add flags from regex if they exist

sos/collector/clusters/__init__.py, sos/collector/clusters/ocp.py, sos/collector/sosnode.py
First patch makes us handle errors in deleting the temporary project more gracefully, and informs the user that manual intervention is needed.
Second patch is a minor change noticed during testing to make `SosNode` report errors with sos execution using the `SosNode.ui_msg()` method, rather than directly printing the error to console in the log file format.
---
=> [ocp] Fix edge case handling of failure to remove temporary project

sos/report/plugins/ipa.py
Since https://www.freeipa.org/page/Releases/4.9.8, SID configuration is instegrated in the base installer. This logs into: /var/log/ipaserver-enable-sid.log
More information: https://pagure.io/freeipa/issue/8995
Resolves: #3268
---
=> [ipa] add SID log file (ipaserver-enable-sid.log)

sos/report/plugins/sssd.py
Widen the capturing of strings for the `ldap_default_authtok` substitution performed on sssd configuration files to also capture strings with spaces.
Closes: #3266
---
=> [sssd] Handle spaces in postproc regex substitution

sos/report/plugins/ipa.py
Since https://www.freeipa.org/page/Releases/4.8.7, IPA includes a tool to send email notifications to users when their passwords are about to expire.
This logs into: /var/log/ipaepn.log
More information: https://pagure.io/freeipa/issue/3687
Resolves: #3272
---
- [] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?
=> [ipa] add EPN log file (ipaepn.log)

sos/report/plugins/kernel.py
RedHat distributions can deliver kernel in RPM named either 'kernel' or 'kernel-redhat', in which case we must verify both package names.
See e.g. https://fedoramagazine.org/changes-eln-kernel-rpm-nvr/ for the background.
It can be bit controversial to customize an `IndependentPlugin` subclass and not using `RedHatPlugin`. But having `class RedHatKernel(Plugin, RedHatPlugin)` would need to replace:
- class Kernel(Plugin, IndependentPlugin):
+ class Kernel(Plugin, UbuntuPlugin, OpenEulerPlugin, CosPlugin, ..):
to list all other distros-plugins, *and maintain the list*. Since `Kernel` plugin being a subclass of `IndependentPlugin` would be honoured also on `redhat` distro/policy.
From a few options (like the "list all `*Plugin`s") I found neither as optimal and the chosen one as the least …
=> [kernel] verify also kernel-redhat on RedHatPolicy

sos/cleaner/__init__.py, sos/cleaner/archives/__init__.py, sos/cleaner/archives/insights.py, sos/cleaner/archives/sos.py, sos/cleaner/mappings/hostname_map.py, sos/cleaner/mappings/username_map.py, sos/cleaner/parsers/hostname_parser.py, sos/cleaner/parsers/keyword_parser.py, sos/cleaner/parsers/username_parser.py, sos/cleaner/preppers/__init__.py, sos/cleaner/preppers/hostname.py, sos/cleaner/preppers/ip.py, sos/cleaner/preppers/keywords.py, sos/cleaner/preppers/mac.py, sos/cleaner/preppers/usernames.py, tests/unittests/cleaner_tests.py
This patchset is the first that should set us on a path to providing multi-process `--clean` support in a way that is not fragile or particularly disadvantageous for single-archive cleaning.
In order to facilitate multi-process down the road, we need to separate some tight bindings between parsers and mappings that exist today. The first of which, is how the mappings get prepared from archives before we do the actual obfuscation work.
This set introduces the use of `SoSPrepper`s, which will be used to pull select data out of archives and use it to prepare the parsers and mappings. This was previously done via `prep_files` dicts for archive abstractions and via additional methods in parsers and/or mappings to handle specific data from specific prep_file contents.
By separating this out, we …
=> [cleaner] Separate process of preparing obfuscations

sos/report/plugins/conntrack.py
Two conntrack commands require several kmods - guard collection of the commands by relevant SoSPredicate.
Resolves: #3279
---
=> [conntrack] collect conntrack commands only when kmods are loaded

sos/report/plugins/__init__.py
When calling get_cmd_output_path() to create a directory via the plugin hpssm, sos threw the following exception:
Traceback (most recent call last):
File "/root/sos/sos/report/__init__.py", line 1224, in setup
plug.setup()
File "/root/sos/sos/report/plugins/hpssm.py", line 67, in setup
logpath = self.get_cmd_output_path()
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/sos/sos/report/plugins/__init__.py", line 2168,
in get_cmd_output_path
os.makedirs(cmd_output_path)
File "<frozen os>", line 225, in makedirs
FileExistsError: [Errno 17] File exists:
'/var/tmp/sos.1gdy83zb/sosreport-localhost-vbwfnpn/sos_commands/hpssm'
This was happening because the directory 'hpssm' was already created. With this change we avoid any race where we call os.makedirs() after we have already created the plugin …
=> [Plugin] Fix exception when calling os.makedirs

tests/report_tests/options_tests/options_tests.py, tests/report_tests/options_tests/options_tests_sos.conf
options_tests.py tests -n option which means tens of plugins are redundantly collected. Testing -o option is effectively the same while the sosreport run needs a half time only.
The functionality of -n option is tested elsewhere, thus the change does not shrink test coverage.
Resolves: #3288
---
=> [tests] Make options_tests faster by calling them on a few plugins only

sos/report/plugins/ceph_ansible.py, sos/report/plugins/ceph_common.py, sos/report/plugins/ceph_iscsi.py, sos/report/plugins/ceph_mds.py, sos/report/plugins/ceph_mgr.py, sos/report/plugins/ceph_mon.py, sos/report/plugins/ceph_osd.py, sos/report/plugins/ceph_rgw.py
This patch helps simplify the capture of data
from ceph plugins. After the original code was
divided in 8 different plugins, it may be a bit
confusing which plugins to use when running
sos and attempting to capture only ceph data.
By selecting the profile, sos will activate only
these ceph_* plugins that apply to a specific
ceph node.
---
=> [ceph] Add a new profile for Ceph plugins

sos/report/plugins/grub2.py
sos report does not gather the symlink
/etc/grub2-efi.cfg when present.
If a system is legacy, but has this file,
grubby default to using this one first in
some cases. Therefore we need to know if
it's present or not.
Closes: RHBZ#2218563
---
=> [grub2] Capture /etc/grub2-efi.cfg

man/en/sos-clean.1, man/en/sos-collect.1, man/en/sos-report.1, man/en/sos.1
Update the maintainer field to be more generic and direct readers to the upstream repo.
Closes: #3290
---
=> [docs] Update maintainer field in man pages

sos/cleaner/__init__.py, tests/cleaner_tests/basic_function_tests/report_with_mask.py
When copying files we applied a substitution in, we must replace just original file content (`shutil.copyfile`) and not also its stat data (`shutil.copy`).
Resolves: #3292
---
=> [clean] Respect permissions of sanitised files

sos/report/plugins/ssh.py
Resolves issue SUPDEV-137.
Adds a plugin option for the ssh module, defining whether it will or will not collect .ssh config files per user.
Default for new option is True
Signed-off-by: Daniel Zhou <dzhou@redhat.com>
---
- [ X] Are any related Issues or existing PRs …
=> [ssh] Add User .ssh Config File Option

sos/report/plugins/microshift.py
=> [microshift] Add initial support for backup info

.github/workflows/snap.yaml, snap/snapcraft.yaml
Adding workdlow to publish the released sos to the latest/candidate channel when the a new release is created via the tag. This ensures less mannual intervention for future releases.
Update the snap creation for anyone building manually, and need python3-venv as a build dependancy.
---
=> [gh_worklow] Build and push snap on release

sos/report/plugins/ceph_common.py, sos/report/plugins/ceph_mon.py, sos/report/plugins/ceph_osd.py
Add a new plugin to enable collecting Ubuntu microceph data
---
=> [microceph][ubuntu] Add changes for microceph collections

sos/options.py
Addresses ConfigParser.readfp removal in 3.12.
Fixes #3308
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2223526
---
=> [options] compatibility fix for python 3.12

sos/report/plugins/ceph_mds.py, sos/report/plugins/ceph_mgr.py, sos/report/plugins/ceph_mon.py, sos/report/plugins/ceph_osd.py, sos/report/plugins/ceph_rgw.py, sos/utilities.py
This lets files triggers use * and also updates the ceph plugins to trigger only if folders are non empty
Closes: #3311
---
=> [utilities][ceph] wildcard support for path in files, fix ceph plugin paths

sos/report/__init__.py
If sos is being used in a live environment to diagnose an issue, using sysroot can cause the network device enumeration via /sys/class/net crawling to fail. This will be the case for systems that do not use `nmcli`.
When in a live environment, network devices will not be under `/$sysroot/sys/class/net` but the "regular" path for the booted environment. Similarly, if sos is being run in a container that is properly configured, network devices will appear under `/sys/class/net` and not (necessarily) under the sysroot path that mounts the host's filesystem.
As such, disregard a configured sysroot when enumerating network devices by crawling `/sys/class/net`, and trap any exceptions that may percolate up from this in edge case environments.
Closes: #3307
---
Please place an 'X' inside each …
=> [report] Don't use sysroot for network device enumeration

sos/report/plugins/openvswitch.py
Since OVS 3.1 'ovs-appctl dpif-netdev/pmd-rxq-show' also supports showing the pmd rxq % usage over shorter timeframes than the default 1 minute, down to a granularity of 5 secs.
A user testing may send traffic and have a steady state for less than 1 min, so it is useful to also see pmd rxq % usage over some shorter time periods.
Add pmd-rxq-show stats for 5 and 30 secs.
---
=> [openvswitch] Add shorter pmd rxq usage periods

sos/report/plugins/containerd.py
This PR adds `containerd.io` RPM name to the packages set of the containerd.py plugin. While most sources of containerd RPMs name them `containerd` the docker repository names them `containerd.io`.
Closes #3321
Signed-off-by: Trevor Benson <trevor.benson@gmail.com>
---
=> [containerd] Enable plugin when RPM name is containerd.io

sos/report/plugins/discovery.py
Enable the plugin by running containers and collect some further system logs.
Resolves: #3324
---
=> [discovery] Enable the plugin by containers

sos/report/plugins/ubuntu.py
Adds a predicate to avoid loading the tls module if it is not loaded.
Resolves: #3326
---
=> [plugins/ubuntu] Do not load tls module if not loaded

sos/report/plugins/slurm.py
Slurm is a workload manager in the HPC space, this is a start on this, and there may be further additions in the future
Resolves: #3329
---
=> [slurm] Add slurm plugin

sos/report/plugins/__init__.py, sos/report/plugins/release.py
The error appeared while running automated tests
for PR 3337:
sos/report/plugins/release.py:9:52: E231 missing
whitespace after ','
Resolves: #3338
---
=> [flake8] Fix E231 in release.py

sos/cleaner/archives/__init__.py
Since Python 3.12, archive.extractall would require setting an extraction filter otherwise an exception is raised. See PEP 706 for more.
Since sos extracts just tarballs that should be compliant with safe extraction (no extracted file outside the target directory etc.), we should stick to the data filter.
Relevant: #3319
Closes: #3330
---
=> [cleaner] Use data filter for extraction

tests/sos_tests.py
grep_for_content should search for a fixed string, not for regexp. The reason is sos is unable to identify 1a2b3c4 as an IP address (which it is not), but grep_for_content would raise false match against 1.2.3.4 .
Resolves: #3320
---
=> [tests] search for fixed strings, not regexps

sos/report/plugins/openshift_ovn.py
With Interconnect support in latest OVN-Kubernetes, ovnkube-nodes logs grew large. This commit adds the ability to collect those additional logs.
---
=> [openshift_ovn] Collect additional ovnkube node logs

sos/report/plugins/maas.py
In MAAS 3.5, multiple services are introduced, and supervisor is replaced by Pebble in snap. This PR updates the `maas` plugin to collect the logs for new services.
---
=> [maas] Update MAAS plugin to collect logs for version 3.5+

sos/report/plugins/openvswitch.py
Since OVS 3.2 there is a command to capture the sleep configuration of DPDK PMD cores.
This shows the maximum amount of time the PMD cores may sleep for under low or no load traffic conditions.
---
=> [openvswitch] Add pmd-sleep-show command

sos/report/plugins/hpssm.py
This change adds new non "Smart Array" labeled controllers to the pattern match for each slot and includes controllers now showing up in slots 10+. 
It continues to honor older Smart Array Firmware which may report as `HP` instead of `HPE`.
Closes #3341
Signed-off-by: Trevor Benson <trevor.benson@gmail.com>
---
=> [hpssm] handle new names and higher slot positions

sos/report/plugins/openshift_ovn.py
This enables ovn sos report plugin to collect logs ovnkube-controller container because ovn-kubernetes now provides option to run both ovnkube-node and ovnkube-controller in same container with this PR https://github.com/ovn-org/ovn-kubernetes/pull/3807.
---
=> [openshift_ovn] Collect logs from ovnkube-controller container

sos/report/plugins/opencontrail.py
In a contrail environment, the container name could also start with `vrouter.*`, this then ensures that the relevant details are also collected from any host that has the containers running
---
=> [contrail] add another container regex

sos/report/plugins/landscape.py
If the relevant environment variables are set, then we collect some useful information to debug landscape-server further
---
=> [landscape] Add landscape-api command collection

sos/report/plugins/__init__.py, sos/report/plugins/foreman.py
Since scl is RHEL7-only related and foreman on RHEL7 is not further supported, let fully remove from scl wrapper.
Resolves: #3353
---
=> [foreman] Call gem list outside scl

sos/report/plugins/openstack_designate.py
Designate deploys bind DNS and unbound services which do not currently have their logs or ansible generate configuration collected.
---
=> [designate] include additional configs and log files

sos/report/plugins/greenboot.py, sos/report/plugins/microshift.py
=> [greenboot] seperate  logs to a standalone plugin.

sos/report/plugins/virsh.py
Adding --all will also get inactive pools/net. This would be helpful when working with a pool/net which failed to startup.
---
=> [virsh] Add --all for virsh pool and net

sos/report/plugins/microshift.py
---
Closes [ushift-1631](https://issues.redhat.com/browse/USHIFT-1631)
=> [microshift] add kube-apiserver log paths to microshift plugin

sos/archive.py, sos/cleaner/__init__.py, sos/policies/distros/redhat.py, sos/report/plugins/__init__.py, sos/report/plugins/candlepin.py, sos/report/plugins/firewall_tables.py, sos/report/plugins/foreman.py, sos/report/plugins/haproxy.py, sos/report/plugins/libvirt.py, sos/report/plugins/mssql.py, sos/report/plugins/pcp.py, sos/report/plugins/pulp.py, sos/report/plugins/pulpcore.py, sos/report/plugins/sos_extras.py
Fix a number of outstanding "File is not always closed" errors highlighted by GitHub's code scanning.
This involves (almost exclusively) changing such as:
```python
for line in open('/some/file', 'r').read().splitlines():
```
To using a context manager to ensure the file is always closed:
```python
with open('/some/file', 'r') as sfile:
for line in sfile.read().splitlines():
```
...or something similar. Overall the logic of what a specific block of code was doing (mostly in plugins) is not changed however.
---
=> [plugins,distros] Resolve code alerts for file not always closed

.gitignore
Updates .gitignore to exclude .DS_Store files that Finder may drop in the tree.
---
=> [git] Ignore DS_Store files from Finder

sos/cleaner/__init__.py, sos/cleaner/mappings/__init__.py, sos/cleaner/mappings/hostname_map.py, sos/cleaner/mappings/mac_map.py, sos/collector/__init__.py, sos/collector/clusters/ocp.py, sos/collector/sosnode.py, sos/collector/transports/__init__.py, sos/collector/transports/control_persist.py, sos/component.py, sos/help/__init__.py, sos/policies/__init__.py, sos/report/__init__.py, sos/report/plugins/__init__.py, sos/report/plugins/autofs.py, sos/report/plugins/ipa.py, sos/report/plugins/ovn_central.py, sos/utilities.py
This commit resolves the alerts generated by GitHub code scanning for mixing implicit and explicit returns. In most cases this is simply changing empty or implicit returns to `return None`, while in a few other places the return logic is slightly reworked.
---
=> [global] Fix alerts for mixing implicit and explicit returns

sos/report/plugins/firewall_tables.py
=> add -a to 'nft list rulest' command to add handle numbers to the output

sos/report/plugins/powerpc.py
Run an opal-prd command to collect nvdimm NV DIMM info which includes:
- Number of NV DIMMs
- Active slot
- Falsh lifetime
- Serial Number
- Runtime
The data generated by the opal-prd for NV DIMM info command is usually
around 1K.
---
=> [powerpc] Collect nvdimm logs

sos/report/plugins/filesys.py
Fix forbidding panfs - add_forbidden_path() needs to be called prior to add_copy_spec() for it to be useful.
Skip /proc/fs/FS for FS picked up by other plugins
---
=> [filesys] skip filesystems picked up by other plugins

.cirrus.yml, tests/test_data/foreman_setup.sh
Bump tested foreman versions - use current latest (3.7) on Ubuntu and CentOS and previous 3.5 and 3.3 to match supported Satellite versions.
---
=> [cirrus] bump foreman versions

sos/policies/runtimes/docker.py
A runtime's `check_is_active()` does not get passed a sysroot at any point, so the docker runtime abstraction should just use the policy sysroot directly.
Additionally, `check_can_copy()` should be simplified to simply return the already-determined active state of the runtime.
---
=> [docker] Fix runtime check_is_active sysroot consideration

sos/report/plugins/pulp.py
An LDAP bind password can be present in `/etc/pulp/settings.py` when running an Ansible private automation hub. This needs to be obfuscated in both the `settings.py` file and in the `dynaconf list` output.
---
=> [pulp] Fix dynaconf obfuscation and add AUTH_LDAP_BIND_PASSWORD

sos/report/plugins/snap.py
=> [snap] Add more items to collect

sos/policies/distros/__init__.py, sos/policies/runtimes/lxd.py
=> [lxd][runtime] Add LXD Runtime

sos/utilities.py
I am sending this as a draft as I won't be able to finish the checklist right away. Please do let me know if this seems OK to you and if so, I can amend the magical phrase to commit messages and rewrap them at 72 characters.
---
=> packaging.version related changes: chatch the proper exception and switch the priority

sos/report/plugins/pulpcore.py
Likewise in #3379, scrub the password also in pulpcore plugin.
Resolves: #3389
---
=> [pulpcore] Scrub AUTH_LDAP_BIND_PASSWORD value

sos/report/plugins/openvswitch.py
driverctl commands give info about which drivers are used for devices. They list PCI address and driver used e.g.
0000:01:00.0 vfio-pci
This can usually be correlated to the device type through lspci. However, lspci may not be available if only some plugins were captured as part of the report.
Even when lspci info is available, it is still convienent to have the device type co-located with the driver and override information.
Add verbose option to driverctl commands that support it to also list device type. e.g. (wrapped for line length)
0000:01:00.0 vfio-pci
(82599ES 10-Gigabit SFI/SFP+ Network Connection
(Ethernet 10G 4P X520/I350 rNDC))
---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidel …
=> [openvswitch] Add driverctl verbose option

sos/report/plugins/insights.py
Resolves: #3391
Closes: #3390
---
=> [insights] collect recursive listing of three dirs

sos/collector/__init__.py, sos/utilities.py
Capture two ImportError exceptions when
calling __import__()
---
=> [utilities|collect] Capture ImportError exceptions

sos/report/plugins/nfs.py
This commit removes the duplicate "rpcinfo_-p_localhost" log
from the sos_commands/nfs directory. Currently, the same log
file is being created in sos_commands/sunrpc/ directory,
as shown below:
```
sos_commands/nfs/rpcinfo_-p_localhost
sos_commands/sunrpc/rpcinfo_-p_localhost
```
Since rpcinfo command is included in rpcbind package, let's remove the one in the nfs directory.
---
=> [nfs] remove duplicate rpcinfo_-p_localhost log

sos/report/plugins/salt.py, sos/report/plugins/saltmaster.py
I'd like to modify the `salt` and `saltmaster` plugins to:
- Add support for the `venv-salt-minion` package
- Gather more useful data, such as:
- Systemctl status information
- Version reports
- Running job reports
- Grains/pillars
and others.
Related downstream issue: https://github.com/SUSE/spacewalk/issues/22700
---
=> [salt] Update salt plugins to gather more data

sos/report/plugins/kernelrt.py
In newer versions of tuna, the option -P has been
substituted for 'show_threads'.
Test if the new option is present in 'tuna --help' and if so, use it.
Closes: RH SUPDEV-150
---
=> [kernelrt] Update options format for tuna

sos/collector/clusters/__init__.py, sos/collector/sosnode.py, sos/collector/transports/__init__.py, sos/collector/transports/oc.py, sos/collector/transports/saltstack.py, sos/policies/package_managers/__init__.py
The `get_pty` parameter for remote executed commands was both a bit of a misnomer and applied too broadly.
Refactor this to `use_shell` to be more obvious about what the intent behind the option is, and default all transports to `False`, so that by default we do not wrap any commands in a bash shell.
This may be overriden on a per-transport basis via the ned `_need_shell` property within transport subclasses. Further, this facility has been expanded to be allowed on a per-command basis from `SoSNode.run_command()` and wherever that is linked.
Related: #3399
Related: #3400
---
=> [collect] Refactor `get_pty` functionality

sos/report/plugins/pacemaker.py
This patch replaces "pcs property list" with "pcs property config" because "pcs property list" is deprecated and will be removed:
```
Deprecation Warning: This command is deprecated and will be removed. Please use 'pcs property config' instead.
Cluster Properties:
...
```
This warning message was introduced in pcs v0.10.9:
https://github.com/ClusterLabs/pcs/commit/332f56ade4773bf22e2ee6c8c91962506b844135#diff-4c58cd856f4e8b23a9d99d961c357e224a9f6314542d50add71a04a2b0b6980cR96-R104
---
=> [pacemaker] Replace deprecated "pcs property list" command

sos/report/plugins/maas.py
Remove file /var/snap/maas/current/http/certs/regiond-proxy-key.pem so that it is not collected by sosreport. This is a private key
---
=> [MAAS] Remove snap TLS private key from report

sos/collector/clusters/juju.py, tests/unittests/juju/juju_cluster_tests.py
New version of juju uses colorisation, and therefore juju status and json.loads doesn't load the juju status correctly. By using --no-color based on the version of juju this should this particular use-case
Resolves: #3399
Resolves: SET-339
---
=> [juju][collect] Fix new juju collection

sos/report/plugins/canonical_livepatch_onprem.py
=> [canonical-livepatch-onprem] Add Canonical Livepatch on-prem server support

sos/report/plugins/networkmanager.py
This patch add some configuration files to be collected based on the description of man 5 NetworkManager.conf.
---
=> [networkmanager] Add config files to be collected

.cirrus.yml, debian/control, debian/rules, sos/policies/runtimes/lxd.py
* python3-setuptools is still required for building the package
* python3-yaml is required for build for tests with the conformance_tests
* Add the same ignores as dowstream build, so that we don't have to keep changing these. Once the avocado is packaged, we can take this out
* Update image for the deb creation, so that it can be minimal
* Fix lxd runtime, so that if the root device is not available, it will not look at the storage pools
Downstream build machines are much more minimal compared to gce instances, so we require more dependencies to be added.
---
=> [deb][pkg] Update control for downstream build

sos/report/plugins/ansible.py
Forbid collecting some files and dirs from /etc/ansible that are not interesting for any investigation but might potentially collect sensitive data.
Resolves: #3423
---
=> [ansible] Skip collecting redundant dirs and files from /etc/ansible

sos/report/plugins/frr.py, sos/report/plugins/libvirt.py, sos/report/plugins/logrotate.py, sos/report/plugins/openstack_edpm.py, sos/report/plugins/openstack_neutron.py, sos/report/plugins/openstack_nova.py, sos/report/plugins/ovn_host.py
EDPM (External DataPlane Management) will be the new way to deploy compute nodes startin from RHOSP 18 which will replace TripleO/Director.
- Added `openstack_edpm` plugin
- Added custom path for config and logs in frr/libvirt/logrotate/openstack_neutron/openstack_nova/ovn_host modules
- Tagged libvirt/openstack_neutron/openstack_nova/ovn_host modules as `openstack_edpm_compute`
---
- [] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
=> Add support for RHOSP 18 Openstack EDPM deployment

sos/policies/__init__.py
Clean up one old reference to an obsolete option.
---
=> [report] Clean up reference to obsolete ticket-number option

sos/report/__init__.py
When adding or deleting preset (and also when detecting no plugin leaves enabled), sos.report.execute must cleanup its working dir.
Since we don't use return value of the execute method, we can skip the return command.
Resolves: #3430
Closes: #3431
---
=> [report] Clean tmpdir when adding or deleting preset

sos/report/plugins/zvm.py
These modules are not present anymore, at least on RHEL8. The modules are not needed to execute 'vmcp' commands.
---
=> [zvm] Don't require 'vmcp' and 'cpint' kernel modules

sos/report/plugins/__init__.py
When running sphinx-build to generate html documentation, we get the following warning:
sos/report/plugins/__init__.py:docstring of
sos.report.plugins.Plugin.collection_file:15:
WARNING: Inline literal start-string without end-string.
Related: RH: RHEL-17923
---
=> [docs] Fix warning generated when running sphinx

sos/component.py, sos/report/__init__.py
As SoSComponent already works with --tmp-dir and it can be declared in a preset, we need to move whole options evaluation from SoSReport to SoSComponent constructor.
Resolves: #3425
Closes: #3432
---
=> [report] Update preset opts already in SoSComponent

sos/report/plugins/foreman.py
Collect up to 14 days of dynflow data instead of one month.
Also, change granularity of the plugin option from months to days - we are almost never interested in tasks older than one month.
Resolves: #3437
---
=> [foreman] Change scope of tasks history

sos/report/plugins/discovery.py
As part of the discovery is also discovery-toolbox plugin we should collect also logs from this plugin which may be helpful in debugging issues.
Resolves: #3442
---
=> [discovery] collect also logs from container discovery-toolbox

README.md
Commit ac17ca4f4 removed the command build_sphinx from setup.py, but the README.md file still references it. This patch offers an alternative for uses wishing to generate html docs, using the command sphinx-build.
Related: RH: RHEL-17924
---
=> [doc] Update README.md with new way to generate html docs

sos/report/plugins/mellanox_firmware.py
This patch reports the output of the following Mellanox firmware commands:
mlxdump
mstconfig
mstdump
mstflint
mlxreg
mlxlink
mlxcables
mst
Additionally, if the user allows system changes, we will atempt to start the mst device, add the cables and stop the device in the end.
---
=> [mellanox_firmware] Add Mellanox firmware plugin

sos/report/plugins/nvidia.py
Having nvidia-persistenced service status helps debugging issues with NVIDIA kernel driver behaviour with persistence mode on.
suggested-by: Borislav Stoymirski <borislav.stoymirski@bg.ibm.com>
Tested-by: Borislav Stoymirski <borislav.stoymirski@bg.ibm.com>
---
=> [nvidia] collect nvidia-persistenced service status

sos/report/plugins/hardware.py
ARM devices often don't have SMBIOS information, so dmidecode does not return anything useful. Add the device tree model information and compatible string, which at least provides the basics.
---
=> [hardware] Include basic info from device tree

sos/report/plugins/maas.py
=> [maas] fix working directory for rsyslog configs on snap install

sos/report/plugins/cockpit.py
Expand the cockpit plugin to capture configuration and output of cockpit-bridge.  
Also remove deprecated command 'remotectl'.
---
=> [cockpit] Expand plugin to capture cockpit-bridge

sos/report/plugins/lustre.py
Collect almost all params, except those explicitly excluded.
Those excluded are known to be less useful debugging, and/or known to be very large.
Some params are still split out to help limit size.
Some very large (but possibly useful) param are relegated to `--all-logs`
---
=> [lustre] Collect most params

sos/collector/transports/saltstack.py
Raise error when _connect() returns non zero status.
The salt `cmd.run` module obfuscates the exit codes of the commands executed on a minion. If a minion does not pickup the message in the queue then the master receives exit code of 1. If the minion picks up the message and upon execution returns any exit code besides 0, the salt master also gets an exit code of 1.
Closes #3457 
---
=> [transport] Prevent package list for unresponsive nodes

sos/report/plugins/tpm2.py
[tpm2.py] Added tpm2 plugin to collect Trusted Platform Module info
Now collecting TPM information using tpm2_tools
Signed-off-by: Bhushan Kale bhushanskale@hotmail.com
---
=> [tpm2.py] Added tpm2 plugin to collect Trusted Platform Module info

sos/report/plugins/auditd.py
ausearch sometimes outputs hexstream instead of raw text esp for "proctitle" values. Let collect more human readable output.
Resolves: #3461
Related: RHEL-19434
---
=> [auditd] Collect ausearch with more human readable output

sos/report/plugins/sedutil.py
[sedutil.py] Added sedutil plugin to collect SED drives info
Now collecting Self Encrypting Drives info using sedutil utility
Signed-off-by: Bhushan Kale bhushanskale@hotmail.com
---
=> [sedutil.py] Added sedutil plugin to collect SED drives info

sos/collector/__init__.py
Setting --upload-url should imply uploading the tarball at the end, regardless of --upload is explicitly set or not.
The same is already in place for "sos report", so let unify it.
Resolves: #3464
---
=> [collect] Imply --upload when --upload-url is set

man/en/sos-report.1
Remove reference to unused transifex.
---
- [] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?
=> [man] Remove reference to unused transifex

tests/report_tests/timeout/timeout_tests.py, tests/unittests/archive_tests.py, tests/unittests/cleaner_tests.py, tests/unittests/option_tests.py, tests/unittests/plugin_tests.py, tests/unittests/policy_tests.py, tests/unittests/report_tests.py, tests/unittests/utilities_tests.py
`unittest.TestCase.assertEquals()` was deprecated in Python 3 [1], and finally dropped in Python 3.12. This now causes the unit tests to fail [2].
[1] https://docs.python.org/3.5/library/unittest.html#deprecated-aliases
[2] https://bugs.debian.org/1058214
---
=> [tests] Drop obsolete TestCase.assertEquals()

sos/policies/distros/ubuntu.py
DISTRIB_RELEASE variable contains a float value for the Ubuntu releases and not an integer value.
Example, a 22.04 release is an LTS release, and a 22.10 release is an interim non-LTS release, changing this value to a float allows us to retrieve the full version rather than just the int.
---
=> [policies] Fix dist_version for Ubuntu

man/en/sos-report.1, sos/archive.py, sos/collector/__init__.py, sos/component.py, sos/report/__init__.py, sos/report/plugins/__init__.py
sos_logs/sos.log and sos_reports/manifest.json tracks command line where we must obfuscate upload passwords like:
--upload-pass=PASSWORD
--upload-url https://user:PASSWORD@some.url
So let move the `do_file_sub` functionality into archive class and call that from report before finalizing the archive.
Resolves: #3463
Closes: #3462
---
=> [archive, component] Obfuscate upload password in sos.log and manifest.json

sos/collector/clusters/saltstack.py
Creates a cluster transport for Saltstack. Options include
- **minion_id_unresolvable**
- Causes the cluster profile to obtain the fqdn from the minions grains.
- Use when a custom minion_id is defined and/or the server hostname is not resolvable to the collector, but the fqdn grain is.
- When the salt-minion service is offline the minion_id will be included in the nodes list, even when unresolvable.
- **compound** targeting
- **glob** targeting
- **grain** targeting
- **nodegroup** targeting
- **pillar** targeting
- **subnet** targeting
EDIT: Description updated to match final implementation.
---
=> [collector] Cluster profile for Saltstack

sos/report/plugins/pam.py
Evident s/add_copy_spec/add_cmd_output/ fix-up from #3438 .
Resolves: #3479
---
=> [pam] Collect authselect command, not file

sos/report/plugins/coredump.py
This plugin captures information about core dumps
on these systems where it's active and has replaced abrt.
Closes: #3325
---
=> [coredump] New plugin to capture coredump info

sos/report/plugins/kubernetes.py
Add DebianPlugin to the list of imports and
the class UbuntuKubernetes.
Related: #3484
---
=> [kubernetes] Add DebianPlugin to plugin kubernetes

snap/snapcraft.yaml, sos.spec, sos/collector/__init__.py, sos/component.py, sos/policies/distros/__init__.py, sos/report/__init__.py
=> [report|collector|policies] Add an S3 protocol upload option

sos/report/plugins/containerd.py
containerd uses CNI to configure the container's network.
The CNI uses different configuration files that by default are installed in `/etc/cni/net.d`, these files are important to understand how the network is configured.
Closes #3482
---
=> [containerd] obtain CNI config files

sos/report/plugins/foreman.py
No URI shall contain a secret or token so there is no need to scrub that file.
Resolves: #3477
---
=> [foreman] Stop scrubbing secrets in Apache access logs

sos/report/plugins/targetcli.py
Add passwords stored in /sys/kernel/config/target/ to the list of forbidden paths.
Related: RH RHEL-19056
---
=> [targetcli] Don't collect passwords from iscsi configs

sos/component.py
When using own preset, loggers verbosity is set even before they are configured. In such a case, we must guard accessing them properly.
Resolves: #3491
Relevant: RHEL-22395
---
=> [component] Check loggers attributes before referencing them

sos/policies/distros/redhat.py, sos/presets/redhat/__init__.py
Adds a new preset for `aap_eda`, or Ansible Automation Platform Event Driven Controller.
This preset will set the `containers_common` plugin to collect output for the `eda` user.
Related: #3486
---
=> [AAP EDA] Add new preset

sos/report/plugins/filesys.py
The file is libmount private (and optional)
but may provide important information as it stores userspace-specific mount data
Related: #3497
---
=> [filesys] Capture /run/mount/utab

sos/report/plugins/networkmanager.py
There are some configuration files which could affect NetworkManager's behaviors. "NetworkManager --print-config" is useful to verify the current configuration at a glance.
---
=> [networkmanager] Add "NetworkManager --print-config" command

sos/report/plugins/samba.py
'wbinfo -t/--check-secret' is one of the basic commands to check if the trust secret for domain is still valid.
'net ads testjoin' is used to check if participation in a domain is still valid.
Related: #RHEL-23665
---
=> [samba] Capture test commands from wbinfo and net ads

sos/report/plugins/fwupd.py
Without SoSPredicate, the plugin was starting
the fwupd service.
Related: RH: RHEL-24342
---
=> [fwupd] Add SoSPredicate to check for service fwupd

sos/report/plugins/ceph_mgr.py
It's part of a Ceph mgr module `prometheus` and the example output is as follows. That would be helpful to understand the timeline and the history of issues in Ceph.
[ceph healthcheck history ls]
```
Healthcheck Name          First Seen (UTC)      Last seen (UTC)       Count  Active
MON_DISK_LOW              2024/02/08 12:53:46   2024/02/08 12:53:46       1   Yes
MON_DOWN                  2024/02/08 12:58:46   2024/02/08 12:58:46       1    No
2 health check(s) listed
```
---
=> [ceph_mgr] collect healthcheck history

sos/collector/clusters/ocp.py
The option --config was moved to --kubeconfig in
OCP 4.7.
Related: RH: RHEL-24402
---
=> [ocp] Replace 'oc --config' command

sos/policies/distros/ubuntu.py
If running tests or sos without the snap or deb installed, then this will fail with TypeError as the sosreport package will not be installed. This will ensure we catch this, and use the default path.
Resolves: SET-338
---
=> [policy] Fix TypeError if snap or deb is not installed

sos/report/plugins/ceph_mds.py, sos/report/plugins/ceph_mgr.py, sos/report/plugins/ceph_mon.py, sos/report/plugins/ceph_osd.py
Ceph release 18.2.0 added a couple of new commands 'counter dump' and 'counter schema' and will supersede 'perf dump' and 'perf schema' which are deprecated now. For sosreport, we obviously need both commands to collect data on existing deployments.
At some point in the future, we can remove 'perf dump' and 'perf schema' from the list of commands for Ceph plugins.
---
=> [ceph] Add Reef release commands

sos/report/plugins/kubernetes.py, sos/report/plugins/microk8s.py
Currently, we are not supporting microk8s with the
same options as provided by kubernetes. This PR
extends the UbuntuKubernetes to get information
from microk8s.
Following the review, it also extends microk8s plugin
to add the credentials file in the copy spec and
runs the postproc() routine.
Closes: https://github.com/sosreport/sos/issues/3500
---
- [X ] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X ] …
=> [Kubernetes] Extend plugin to support microk8s

sos/report/plugins/flatpak.py
Running various flatpak commands can start gvfs mount, which is undesirable outcome of sos. Calling the commands with GVFS_REMOTE_VOLUME_MONITOR_IGNORE=1 env.variable prevents that behaviour.
Relevant: RHEL-14328
Closes: #3528
---
=> [flatpak] Prevent flatpak commands to mount gvfs

sos/cleaner/mappings/__init__.py, sos/cleaner/mappings/hostname_map.py, sos/cleaner/mappings/keyword_map.py, sos/cleaner/mappings/username_map.py, sos/cleaner/parsers/__init__.py, tests/unittests/cleaner_tests.py
PR for https://github.com/sosreport/sos/issues/3403 . For relevant mappings (hostname, username, partly keyword), skip obfuscation of strings <4 length and skip obfuscation of substrings inside words.
Reproducer to play with:
echo "repo" >> /etc/cron.deny
echo "map" >> /etc/cron.deny
echo "private" >> /etc/cron.deny
rm -rf /etc/sos/cleaner/default_mapping
sos report -o cron --batch --build --clean
..
A mapping of obfuscated elements is available at
/var/tmp/sosobfuscateduser2rt-pmoravec-rhel8-2024-01-28-ditdybr-obfuscateduser1_obfuscateduser0
while it should be:
/var/tmp/sosreport-pmoravec-rhel8-2024-01-28-ditdybr-obfuscateduser0_map
---
=> [cleaner] skip shortstrings and substrings

sos/report/plugins/nfs.py
Collect useful info by executing some more commands in nfs-utils package:
- nfsconf for the current configuration.
- mountstats for various NFS client statistics.
- rpcctl for SunRPC connection information.
---
=> [nfs] Add nfsconf, mountstats, and rpcctl commands

sos/plugins/candlepin.py, sos/plugins/foreman.py, sos/plugins/rpm.py
These commits are adding backports for Satellite installer log 
password obfuscation, collection of 'rpm --showrc' command 
and information about
about SCA. 
Related: #2388
Related: #2157
Related: #2901
Resolves: #3475
Signed-off-by: Barbora Vassova <bvassova@redhat.com>
---
=> [redhat] Backports of enhancements for RHEL7

sos/report/plugins/sapnw.py
The sapconf command is not distributed in RHEL 8 and 9, so the code is never executed, and its safe to remove.
Related: RH: RHEL-27830 and RHEL-27831
---
=> [sapnw] Remove capture of deprecated sapconf command

sos/report/__init__.py
As discussed in the [#3502](https://github.com/sosreport/sos/pull/3502#pullrequestreview-1859497147) adding new section under _get_hardware_devices(). Please review it.
---
=> Add new section fstype section under hardware devices.

sos/collector/clusters/juju.py, sos/collector/clusters/pacemaker.py, sos/collector/sosnode.py, sos/report/plugins/pacemaker.py, sos/utilities.py
There are couple of instances (both on pacemaker) of `parse_version` being used to compare the package
versions. In cases, notably on Ubuntu, where the version comform to PEP440, this fails. So we now convert those to PEP440 format before comparing.
Fixes #3548.
---
=> [pacemaker] Use pep440 formatted version for pcs version

.cirrus.yml, tests/test_data/foreman_setup.sh
A puppet regression in version 7.29.0 prevents foreman-installer to run.
Let prevent installing the buggy puppet-agent-7.29.0* .
Resolves: #3542
Closes: #3555
---
=> [tests] workaround puppet bug in foreman-installer

man/en/sos-clean.1, sos/cleaner/__init__.py, sos/cleaner/archives/__init__.py, sos/cleaner/parsers/__init__.py, sos/cleaner/parsers/hostname_parser.py, sos/cleaner/parsers/ip_parser.py, sos/cleaner/parsers/ipv6_parser.py, sos/cleaner/parsers/keyword_parser.py, sos/cleaner/parsers/mac_parser.py, sos/cleaner/parsers/username_parser.py, sos/collector/__init__.py, sos/report/__init__.py, tests/cleaner_tests/basic_function_tests/report_with_mask.py
A new option --skip-clean-files allows cleaner to skip cleaning files where the user is certain no sensitive information is present.
The option supports globs / wildcards.
Relevant: #3469
Closes: #3520
---
=> [cleaner] Add option to skip cleaning files

sos/report/plugins/ceph_mon.py
Currently we capture the output of 'ceph health detail' in json format only, but we need plain text output as well.
Related: RH RHEL-27525
---
=> [ceph_mon] Capture ceph health detail in plain text

sos/report/plugins/nginx.py
Implementing the exclusion of AAP nginx log files
The AAP configuration creates nginx logs with non-standard names
Related: RH AAP-19782, RH AAP-18409
---
=> [nginx] Implementing files exclusions from AAP for nginx

sos/report/plugins/ceph_common.py, sos/report/plugins/ceph_iscsi.py, sos/report/plugins/ceph_mds.py, sos/report/plugins/ceph_mgr.py, sos/report/plugins/ceph_mon.py, sos/report/plugins/ceph_osd.py, sos/report/plugins/ceph_rgw.py
Currently Ceph plugins do not take the `all-logs` flag into account 
which means that even if this flag is set compressed log files are 
not collected
This patch fixes that.
Resolves: SET-480
---
- [ x ] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [ x ] Is the subject and message clear and concise?
- [ x ] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [ x ] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ x ] Are any related Issues or existing PRs [properly …
=> [ceph] Ensure `all-logs` is enforced for Ceph plugins

sos/report/plugins/aap_hub.py
Adding the file 'aap_hub.py' for the sos report collects 
the files used for troubleshooting issues at
Ansible Automation Platform Automation Hub
Related: RH AAP-19782
Signed-off-by: Lucas Benedito <lbenedit@redhat.com>
---
=> [aap_hub] Implementing AAP Automation Hub Plugin

sos/report/plugins/openstack_keystone.py
Obfuscate OIDC client secret inside
/var/lib/config-data/puppet-generated/keystone/
etc/httpd/conf.d/10-keystone_wsgi.conf 
The secret looks like this:
 
OIDCClientSecret "Password"
And after obfuscation, it will look like this:
OIDCClientSecret *********
Related: RH: RHEL-26720
---
=> [openstack_keystone] Obfuscate OIDC client secret

sos/policies/__init__.py, sos/policies/distros/redhat.py, sos/report/plugins/__init__.py, sos/report/plugins/foreman.py, sos/report/plugins/jars.py, sos/report/plugins/postgresql.py, sos/report/plugins/redis.py
SCL is not used in RHEL past RHEL 7, and sos has not directly supported RHEL 7 for some years now due to the switch to python3 that came along with sos-4.0.
Drop SCLPlugin, as it will never be used in modern sos. Cleanup any references to it in existing plugins as well.
Resolves: #3559
---
=> [SCLPlugin] Drop SCLPlugin support

sos/report/plugins/openstack_nova.py
The console log files of Nova instances stored in /var/lib/nova/instances/*/console.log are collected when running sos with --all-logs.
---
=> [openstack_nova] Added the collection of console.log from Nova instances

sos/archive.py, sos/collector/__init__.py, sos/collector/clusters/__init__.py, sos/policies/distros/__init__.py, sos/report/__init__.py
This commit is a first pass at addressing a number of the `Empty Except` warnings flagged by CodeQL. These are for try/except blocks whose except statement simply contains a `pass`, and to address these we add a log message in almost all cases. Where we don't log, there is an added comment for context as to why we're passing without further action.
---
=> [global] Remove empty except warnings highlighted by CodeQL

sos/policies/distros/azure.py, sos/report/plugins/__init__.py
This commit creates an AzurePlugin class, adds the AzurePlugin as a valid subclass in the Azure Policy, updates the vendor url and updates the check method due to a product rebranding for Microsoft Azure Linux 3.0
---
=> [Plugin,Policy] Make an AzurePlugin class, Update the vendor url, Update the check function

man/en/sos-report.1
Add a note to the entries for --upload-user and --upload-pass clarifying that these options have been deprecated in RHEL systems.
---
=> [manpages] Add note about deprecation of options for RHEL

sos/report/plugins/cifs.py
Added some missing files from /proc/fs/cifs and blacklist some files that we don't need to capture.
Related: RH: RHEL-29707
---
=> [cifs] Capture missing files from /proc/fs/cifs

.github/PULL_REQUEST_TEMPLATE.md
This patch adds a new line to the github PR
template so users can assess that they have
obfuscated any password or similar from the
code they are submitting.
Closes: #3427
---
=> [github] Add check for data obfuscation

sos/report/plugins/samba.py
Capturing this command output can help find the domain status, specially in these cases where having multiple domains in the same forest/cross forest, or in cases where there is sssd and samba_winbind. This output complements that of 'net ads testjoin'.
Related: RH: RHEL-30958
---
=> [samba] Capture wbinfo --online-status

sos/report/plugins/aap_receptor.py
Adding the file 'aap_receptor.py' for the sos report collects 
the files used for troubleshooting issues at
Ansible Automation Platform Controller/Execution Nodes
Related: RH AAP-19657
---
- [] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?
=> [AAP RECEPTOR] Add a new AAP receptor plugin.

sos/report/plugins/aap_eda.py
Adding the line to collect the nginx log files for the AAP EDA 
sos report used for troubleshooting issues at 
Ansible Automation Platform Event Driven Controller
Related: RH AAP-12898
Signed-off-by: Rudnei Bertol Junior <rudnei@redhat.com>
---
=> [AAP EDA] Adding aap eda nginx log files to be collected

sos/policies/distros/redhat.py, sos/presets/redhat/__init__.py
Adds a new preset for `aap_controller`, or Ansible Automation Controller.
This preset will set the `containers_common` plugin to collect output for the `awx` user.
Related: #3561
Signed-off-by: Rudnei Bertol Junior <rudnei@redhat.com>
---
=> [AAP CONTROLLER] Add new preset

sos/collector/__init__.py, sos/collector/clusters/kubernetes.py, sos/collector/clusters/ocp.py, sos/collector/clusters/ovirt.py, sos/collector/clusters/satellite.py, sos/collector/sosnode.py, sos/collector/transports/__init__.py, sos/policies/runtimes/__init__.py, sos/policies/runtimes/crio.py
`pipes` is deprecated and being removed from Python in 3.13. Our usage is exclusively `pipes.quote()`, which has actually been calling `shlex.quote()` behind the scenes for some time (at least since 3.6).
Update our usage of `quote` to directly import from `shlex`.
Resolves: #3310
---
=> [global] Update use of pipes with shlex

sos/collector/clusters/ocp.py, sos/collector/clusters/ovirt.py, sos/collector/sosnode.py, sos/component.py, sos/policies/distros/redhat.py, sos/policies/init_systems/systemd.py, sos/report/plugins/dnf.py, sos/report/plugins/gluster.py, sos/report/plugins/jars.py, sos/report/plugins/pcp.py, sos/report/plugins/subscription_manager.py, sos/report/plugins/watchdog.py, sos/utilities.py
This commit resolves the remaining 'Empty except' alerts from CodeQL scanning.
Most of these involve logging something during exception handling when we were previously simply `pass`ing. Others, either when logging is unavailable or it makes no sense to log something for, are resolved by placing comments within the except block as the CodeQL alerts should be suppressed if the 'empty except' (`pass`ing) has an explanatory note.
---
=> [Global] Resolve empty except alerts from CodeQL

sos/policies/package_managers/__init__.py
When initializing _packages, a distinction must be made between not having any package and not being initialized at all. Otherwise, if a package manager returns no package, the query command will execute hundreds of times.
This can reproduce with 'flatpak' on RHEL when no package is returned:
```
--> no output
[...]
Press ENTER to continue, or CTRL-C to quit.
^C
350
```
---
=> [pkg] Don't initialize _packages to empty set

sos/cleaner/archives/__init__.py, sos/collector/clusters/ocp.py
* W4903: deprecated-argument
* W4902: deprecated-method
```
sos/collector/clusters/ocp.py:244:8: W4902: Using deprecated method warn() (deprecated-method)
sos/collector/clusters/ocp.py:244:8: W4902: Using deprecated method warn() (deprecated-method)
sos/cleaner/archives/__init__.py:295:8: W4903: Using deprecated argument onerror of method rmtree() (deprecated-argument)
```
---
=> [pylint] Fix deprecated warnings

sos/cleaner/archives/__init__.py
Commit d5d8c21 reordered files in the archive, such that the first member is not the archive root directory further more. Let change the get_archive_root method accordingly to prevent self.archive_root being empty.
Resolves: #3616
---
=> [archive] Fix get_archive_root after files reordering

sos/report/plugins/__init__.py, sos/report/plugins/logs.py
If user limit logs with --since, there is no reasons to have logs older than the limit.
---
=> [plugins] apply --since to all journal collection

sos/report/plugins/processor.py
The cpupower and turbostat applications are not installed by default on most environments, but where it is, it will load the `msr` module when running this commends. Adding the predicate will solve this.
Closes: #3610
Related: #3624, SET-622
---
=> [processor] handle `msr` module loading via predicate

.cirrus.yml, test-requirements.txt, tox.ini
This allows to run specific tests, and not all the tests in one go. This is especially useful if you're writing a plugin or creating a test for a specific scenario. Below an example of what would be possible
```
sudo tox -e stagetwo_tests -- tests/report_tests/plugin_tests/openstack/openstack.py
```
This will run stagetwo tests for the specific test, i.e. openstack in this case
This also fixes the stagetwo tests, so that it picks up the systemd python libs from the distro environment
Update the installation of avocado-framework from one place, so that we don't need to change the version in many places. Adding `test-requirements.txt` to handle this and integrate this with both tox and Cirrus CI
--- …
=> [tox] Use posargs for the tests

.cirrus.yml
Update the ubuntu images to the newest available.
`noble`(24.04) was released yesterday, and the new GCE image is available in the project, so we can officially start testing on that
---
=> [cirrus] Update images, add noble to supported list

sos/report/plugins/ssh.py
Collect sshd config files in its dedicated sshd_config.d directory, as well as config files included from them.
Resolves: #3595
---
=> [ssh] Collect sshd_config.d directory

sos/report/plugins/aap_gateway.py
Adding the plugin 'aap_gateway.py' for the sos report to collect
the files used for troubleshooting issues at 
Ansible Automation Platform Gateway
Related: RH AAP-20033
---
=> [aap_gateway] Implementing AAP Gateway Plugin 

.cirrus.yml, sos/report/plugins/processor.py
Ubuntu 24.10 release cycle has new started with the daily builds, so
we start testing on these to uncover any issues
Also update to latest GCE images for any new ubuntu images
Fix the `msr` predicate, such that it is caught on 24.04 and newer
releases of ubuntu
Related: https://github.com/sosreport/sos/issues/3610
---
=> [cirrus] Start testing on new devel ubuntu daily

sos/report/plugins/ebpf.py
The plugin was running even when the bpftool was
not present, throwing an exception when it tried to parse a json output:
INFO: [plugin:ebpf] Could not parse bpftool prog list as
JSON: Expecting value: line 1 column 1 (char 0)
It now checks if the program is present before running any command at all.
Related: RH SUPDEV-151
---
=> [ebpf] Check for bpftool presence before running plugin

sos/report/plugins/microovn.py, sos/report/plugins/ovn_central.py
=> [microovn] Added new plugin support for MicroOVN

debian/control
Now that the python3-boto3 package is in the `main` pocket we can now add to `Depends`. This will enhance future deb packages to allow S3 uploads.
---
=> [deb][pkg] Add python3-boto3 to depends

sos/report/plugins/kubernetes.py
Rework kubernetes plugin to make it collect in more cases
This PR can be split in multiple ones if prefered
Resolves #3628 
Supersedes #3626 
---
=> [kubernetes] plugin improvements

sos/report/plugins/canonical_livepatch.py
Add the service in the service dict so that we collect the journal for the corresponding service. Also acts as an extra trigger.
Obfuscate the certs that the config outputs
---
=> [livepatch] Add config output and bring out service

sos/policies/distros/redhat.py
The Red Hat Customer Portal has a max limit for
single http requests of 1Gb. From sos side, we never checked this and so customers had to wait for the whole upload to be attempted before receiving an error from the portal.
This patch attempts to stop the upload before it starts, informing customers of such limit, and switching to secure FTP where there's no limit.
Related: RHEL-22732
---
=> [redhat|policy] Check for archive size before upload

sos/report/plugins/ceph_mds.py
Newer versions of Ceph place information in
/var/lib/ceph/<fsid>/mds* instead of
/var/lib/ceph/mds/*, so we need to capture
the new path as well.
Related: RH: SUPDEV-154
---
=> [ceph_mds] Capture alternative mds file path

sos/report/plugins/networking.py
We see that the predicate is replicated among all Ubuntu distros after 22.04, so we simplify the check to ensure all distros are covered in the future.
---
=> [networking] Update ss predicate for Ubuntu

sos/policies/distros/almalinux.py
AlmaLinux OS is an Enterprise Linux distro, binary compatible with RHEL. This commit adds a AlmaLinux policy, which inherits the RedHatPolicy base.
Signed-off-by: Eduard Abdullin <eabdullin@almalinux.org>
---
=> [policies] Add AlmaLinux policy

pylintrc, tests/report_tests/plugin_tests/logs.py, tox.ini
Also fix tox issues with posargs and further fine tuning
---
=> [pylint] Refactor pylint configuration

sos/report/plugins/kdump.py
This change enables the RH plugin to display the content of /var/crash via the command 'ls', and adds a new option to capture the latest vmcores generated
in the last 24 hours, smaller than 2GB, as it's
done in the AzureDump class.
---
=> [kdump] Capture more commands for RH kdump

sos/report/plugins/openstack_edpm.py
These paths are also used by EDPM and should be collected by the plugin.
Signed-off-by: James Slagle <jslagle@redhat.com>
---
=> [openstack_edpm] Add additional paths

.cirrus.yml, .packit.yaml
Remove packit and cirrus references to centos-stream 8 that's EOL since May 31st 2024.
---
=> [packit|cirrus] Remove centos-stream-8 references

sos/report/plugins/__init__.py, sos/utilities.py
=> [global] Add the ability to run command as user

sos/report/plugins/apt.py, tests/report_tests/plugin_tests/apt/apt-proxy.conf, tests/report_tests/plugin_tests/apt/apt-sources.list, tests/report_tests/plugin_tests/apt/apt-sources.sources, tests/report_tests/plugin_tests/apt/apt.py
The configuration of apt was not being obfuscated if any of the URLs had a password; one example was the proxy. There is also a new format for the deb sources, so ensuring that would be obfuscated in the same way. Add some tests to ensure that this is always being obfuscated.
---
=> [apt] Obfuscate passwords for configs/sources

sos/utilities.py
If the chdir would have been set as well as runas, the chdir would not have taken effect, so updating to reflect the correct behaviour
Related: #3648 
---
=> [global][utilities] Move the chdir after the runas

sos/report/plugins/kernel.py
plugin
---
- [X ] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [ X] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or …
=> [kernel] Print human-readable timestamps with dmesg command in kernel

sos/report/plugins/kernel.py
PR #3657 added human readable timestamps to the dmesg command, but the command can be unreliable. This PR adds the plain 'dmesg' command capture again, to make sure that we still have an output with reliable
timestamps that can be easily converted to human readable in these cases where 'dmesg -T' could not be trusted.
---
=> [kernel] Add plain 'dmesg' command to plugin

snap/snapcraft.yaml
The version of the packaging was released to 24.1, and this causes an issue on 18.04. Pinning to 24.0 to allow it to work in 18.04
Closes: #3659
---
=> [snap] Fix snap build for bionic

.cirrus.yml, sos/policies/distros/redhat.py
Update the super() lint isuse that crept in while linitng work was being done
Generalise the linting to use python:latest rather than alpine image
Enfore pylint now, as that will catch stuff with all the disabled plugins
---
=> [linting] Fix linting issues

sos/report/plugins/__init__.py
Stops sos from logging ", as the None user" for command collections that do not specify a `runas` user (meaning when collections run as root).
---
=> [Plugin] Don't log "None" as a user with `runas`

sos/report/plugins/kubernetes.py
PR as promised here https://github.com/sosreport/sos/pull/3630#issuecomment-2113294101
Looking on https://access.redhat.com/downloads/content/package-browser latest version of
- kubernetes-master is from 2017-06-06
- atomic-openshift-master is from 2022-08-30
The first versions of openshift-hyperkube are
4.1.0-201905191700.git.0.cb455d6.el{7,8}, so it's
safe to drop openshift bits from kubernetes plugin.
We keep the "not openshift-hyperkube" check_enabled() as we might have files in common in the future.
---
=> [kubernetes] remove old openshift support

sos/report/plugins/charmed_postgresql.py
Example output of the plugin can be seen at https://drive.google.com/drive/folders/1t1QOwzqwFTv140xvpaRpB5-kqRPOYth5?usp=sharing
---
=> [charmed_postgresql] Add Charmed PostgreSQL support

sos/report/plugins/memcached.py
=> [memcached] Collect from memcached using the tool

sos/report/plugins/sunbeam.py
* Add juju related info for sunbeam
* Add logs from the sunbeam snap home user
Resolves: SET-682
---
=> [sunbeam] Update plugin to collet more details

bin/sos-collector, bin/sosreport, man/en/sos-clean.1, man/en/sos-collect.1, man/en/sos-report.1, man/en/sos.1, man/en/sos.conf.5, sos/cleaner/parsers/username_parser.py, sos/collector/__init__.py, sos/collector/clusters/__init__.py, sos/collector/sosnode.py, sos/collector/transports/control_persist.py, sos/collector/transports/saltstack.py, sos/missing.py, sos/options.py, sos/policies/__init__.py, sos/policies/distros/__init__.py, sos/policies/init_systems/__init__.py, sos/report/__init__.py, sos/report/plugins/__init__.py, sos/report/plugins/arcconf.py, sos/report/plugins/azure.py, sos/report/plugins/candlepin.py, sos/report/plugins/mvcli.py, sos/report/plugins/mysql.py, sos/report/plugins/sas3ircu.py, sos/report/reporting.py, tests/cleaner_tests/basic_function_tests/report_with_mask.py
This commit serves to reinforce the typing of "sos (space) report" in place of the legacy "sosreport", and similarly updates items such as "sos-collector" to "sos collect". The tool is `sos` ("ess-oh-ess"), of which `report` and `collect` are sub-commands.
The most visible change is the update to the line printed before the path to a generate sos report, which may be significant for scripts and/or automation. To be clear, this commit changes this line:
`Your sosreport has been generated and saved in:`
to
`Your sos report has been generated and saved in:`
Note that this does not change the use of `sosreport` when used as part of method names, nor does it change the *filename* of the generated archive for either `report` or `collect`.
---
Please place an 'X' inside each '[]' to confirm you …
=> [Global] Update strings to align with `sos` tooling names

sos/report/plugins/fail2ban.py
New plugin for fail2ban daemon.
---
=> [fail2ban] Add new plugin for fail2ban

sos/report/__init__.py
=> [sos] Fix typos in sos help

sos/report/plugins/rhc.py
Capture information from rhc worker playbooks, and obfuscate public ssh keys.
Related: RH: RHEL-27555
---
=> [rhc] Collect information related to rhc-worker-playbook

sos/report/plugins/__init__.py, sos/report/plugins/grafana.py, sos/report/plugins/kafka.py, sos/report/plugins/lxd.py, sos/report/plugins/maas.py
* Add function is_snap_installed, so that this can be used more widely
* This also reduces duplicate code in plugins.
* Add is_snap variable, that can be used if any of the packages is a snap; typically it's one of the other.
---
=> [common] Standardise snap package checks

sos/report/plugins/kernel.py
Collect /sys/kernel/debug/hv-balloon with Hyper-V ballooning usage information.
Resolves: #3692
---
=> [kernel] Collect hv-balloon

sos/report/plugins/container_log.py
In Kubernetes/OpenShift rotated logs have no symbolic link in /var/log/containers and they cannot be retrieved using `oc logs` either, so there is no way to get these rotated logs in a SOS report.
This patch proposes a new functionality for the `container_log` plugin to retrieve rotated logs for the containers.
Since there may be lots of rotated logs we also add the `maxage` option.
The plugin will not only download the `/var/log/pods` files but also the `/var/log/container` symlinks.
Closes #3677
Signed-off-by: Gorka Eguileor <geguileo@redhat.com>
---
=> [container_log] Get rotated logs

tests/cleaner_tests/existing_archive.py, tests/cleaner_tests/full_report/full_report_run.py, tests/cleaner_tests/ipv6_test/ipv6_test.py, tests/report_tests/options_tests/options_tests.py
To prevent avocado hiccups that slow down sos execution, let disable debug logs to stdout.
Resolves: #3693
---
=> [tests] Disable verbose stdout killing avocado performance

.cirrus.yml, .github/workflows/snap.yaml, snap/snapcraft.yaml
=> [snap] Build snap with core24

.github/workflows/snap.yaml
The snap can be build on 22.04 in the workflow as the action creates the relevant versioned container and builds the snap
Closes: #3696
---
=> [snap,workflow] snap build fix for core24

sos/report/plugins/ceph_mds.py
Current output of this command without a path is:
```
Invalid command: missing required parameter root(<string>)
dump tree <root> [<depth:int>] :  dump metadata cache for subtree
admin_socket: invalid command
```
---
=> [ceph_mds] Add required path parameter to `dump tree`

sos/policies/distros/__init__.py
When using rpm-ostree, /boot/config-{release} doesn't exists but RHEL/Fedora family also ship the kernel config file in /lib/modules/{release}/config, so try that as fallback.
---
=> [policies] Fallback to /lib/modules/*/config

pylintrc, sos/cleaner/__init__.py
=> [pylint] re-enable W0105: pointless-string-statement

sos/report/plugins/sunbeam_hypervisor.py
Previous environment tests did not have ceilometer, and testing on new version brought out this issue.
Also solved the hooks.log obfuscation
Resolves: #3713
---
=> [sunbeam_hypervisor] Fix obfuscation for ceilometer and hooks.log

pylintrc, sos/policies/distros/__init__.py, sos/policies/distros/redhat.py
=> [pylint] Re-enable useless-return

sos/report/plugins/networking.py
Capture 'nmstatectl show' and 'nmstatectl show --running-config'
Related: RHEL-50639
---
=> [networking] Capture nmstatectl commands

sos/report/plugins/memory.py
Capture two files from /sys/kernel/memory/lru_gen:
- enabled
- min_ttl_ms
Related: RHEL-50917
---
=> [memory] Capture content of /sys/kernel/memory/lru_gen

plugins_overview.py, pylintrc, sos/archive.py, sos/cleaner/__init__.py, sos/cleaner/archives/__init__.py, sos/collector/transports/control_persist.py, sos/report/__init__.py, sos/utilities.py, tests/cleaner_tests/basic_function_tests/report_with_mask.py, tests/cleaner_tests/existing_archive.py, tests/cleaner_tests/full_report/full_report_run.py, tests/cleaner_tests/report_disabled_parsers.py, tests/unittests/archive_tests.py, tests/unittests/plugin_tests.py, tests/unittests/utilities_tests.py
=> [pylint] re-enable consider-using-{with, f-string}

sos/report/plugins/maas.py
Changes:
- plugin_timeout = 1800 (because journal collection takes time)
- collect journal for all MAAS related services (by default since yesterday)
- mask passwords in (conf|yaml|yml|toml) files with `do_path_regex_sub`
- collect only recent syslog data for machines (if `--all-logs` was not provided) 
snap:
- collect all `.conf` and `.yaml` files
- exclude files containing secrets and keys under `/var/snap/maas/**`
deb:
- add missing service `maas-temporal-worker` introduced in MAAS 3.5
- collect `/var/lib/maas/temporal`
- use glob pattern to collect `.conf` files
- exclude secrets and keys under `/var/lib/maas/**` and `/etc/maas/**`
- remove `/var/log/upstart/maas-*` as it was removed in xenial
- remove `maas-region dumpdata` as it can expose sensitive information
---
Please place an …
=> [maas] improve/refactor MAAS plugin

sos/report/plugins/maas.py
The commit 992fda9440891000e1b1cf783b829a4e722e2a84 reintroduced one of the pylints checks (`redefined-builtin`) that was already removed. Fixing it here.
---
=> [pylint] Fix redefined-builtin in maas plugin

sos/utilities.py
The commit d65e135c8 appears to have introduced a bug when converting formats to use f-strings. This apparently broke the `convert_bytes()` function.
---
- [x ] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
=> [common] Fix a bug in f-string usage

man/en/sos-clean.1, man/en/sos-collect.1, man/en/sos-help.1, man/en/sos-report.1
This was reported as part of deb packaging in Debian.
---
=> [man] Fix man page lintian issues

pylintrc, sos/__init__.py, sos/cleaner/__init__.py, sos/cleaner/mappings/ip_map.py, sos/policies/auth/__init__.py, sos/policies/distros/__init__.py, sos/policies/distros/redhat.py, sos/policies/package_managers/__init__.py, sos/report/plugins/__init__.py, tests/sos_tests.py, tests/unittests/plugin_tests.py, tests/vendor_tests/redhat/rhbz1928628.py
The following are fixed in this change:
W3101 - missing-timeout
W0231 - super-init-not-called
C0123 - unidiomatic-typecheck
C0207 - use-maxsplit-arg
E0611 - no-name-in-module
E0702 - raising-bad-type
E1101 - no-member
E1135 - unsupported-membership-test
---
=> [pylint] Fixes more pylint issues

sos/report/plugins/__init__.py, sos/report/plugins/grafana.py, sos/report/plugins/lxd.py, sos/report/plugins/maas.py, sos/report/plugins/sunbeam.py
Add a new flag to add_cmd_output to suggest a snap_cmd, so that sos
does not direct the command directly to a file.
Resolves: #3683
---
=> [common] handle all_logs when snap package is installed

sos/policies/distros/cloudlinux.py
CloudLinux OS is an Enterprise Linux distro, binary compatible with RHEL.
This commit adds a CloudLinux policy, which inherits the RedHatPolicy base.
Signed-off-by: Eduard Abdullin eabdullin@almalinux.org
---
=> [policies] Add CloudLinux policy

sos/policies/distros/cloudlinux.py
Previous merge included a preemptive "or later" addition to the license header pending the early discussion in #3705. Revert that to be consistent with the "GPLv2 only" stance of the project.
---
=> [cloudlinux] Revert license header change

sos/report/plugins/scsi.py
Capture the WWN for disks via lsscsi.
---
=> [scsi] Capture the WWN for disks in the output of lsscsi

sos/policies/distros/redhat.py
Fix the return of the size checks for Red Hat uploads to customer portal. Without this fix, uploads were failing silently.
---
=> [redhat] Fix return of function check_file_too_big()

sos/report/plugins/__init__.py, tests/report_tests/basic_report_tests.py
`add_dir_listing` method in #3664 hid exact filesizes in "`ls -l`" like outputs in favour of human readable output. That has two drawbacks:
1) It provides less precise information, while particular filesizes for some files can be essential to know. E.g. `3.1K` can mean `3075` or `3174` bytes and the difference can matter for some well known files with well known default sizes.
2) It makes it difficult to parse the size by various analytical tools
`sos` tool should be data collectio tool rather than interpreting them. So let replace human readable filesize by exact one.
Resolves: #3758
---
=> [Plugin] Collect exact filesizes in add_dir_listing

sos/policies/distros/__init__.py, sos/policies/distros/redhat.py, sos/policies/distros/ubuntu.py
Adds _get_obfuscated_upload_url(self, url) method in LinuxPolicy class to be used when passwords in upload urls are needed to be obfuscated. The same is used in RedHatPolicy and UbuntuPolicy classes.
Closes: #3465
Example stdout:
```
$ sos report --upload-url https://user:PASSWORD@URL --batch
...
Creating compressed archive...
Your sos report has been generated and saved in:
/var/tmp/sosreport-fedora-2024-08-23-yxxrsqh.tar.xz
Size	21.50MiB
Owner	root
sha256	896cce985997729a8107635b5aa7e9b51ad79f03b39e65b1445ebb77fb655252
Please send this file to your support representative.
Attempting upload to https://user:********@URL
...
```
---
=> [policies] Obfuscate upload password in `get_upload_url_string()`

sos/cleaner/mappings/keyword_map.py
Check whether item keyword exists in dataset before obfuscation in sanitize_item(self, item) method. Resolves redundant increments when the same keyword is provided more than once, and the current obfuscation "obfuscatedwordX" is preserved.
Closes: #3745
Example stdout (using the example in the issue):
1. First run with keywords: 
```
root@fedora:sos# ./bin/sos report --batch -o block --clean --map-file /etc/sos/cleaner/default_mapping --keywords supercalifragilisticexpialidocious,supersecret,topsecretstuff
...
root@fedora:sos# jq '.keyword_map' /etc/sos/cleaner/default_mapping
{
"supercalifragilisticexpialidocious": "obfuscatedword0",
"supersecret": "obfuscatedword1",
"topsecretstuff": "obfuscatedword2"
}
```
2. Obfuscations are preserved in the subsequent runs:
```
root@fedora:sos# …
```
=> [cleaner] Check if keyword exists in dataset before obfuscation

sos/report/plugins/processor.py
The `turbostat` command has been seen to hit the default 5-minute timeout for reasons that are not immediately obvious. The behavior pattern is that the `turbostat --debug sleep 10` command this plugin captures may not exit until some form of input is received, at which point the command "fails successfully" with the following message:
`turbostat: get_rapl_counters: failed to read perf_data (8 1): Success`
Prevent this condition from holding up sos report execution by adding a timeout to this collection.
Resolves: #3753
---
=> [processor] Add a timeout to turbostat collection

sos/report/__init__.py
During conversion to f-strings in #3606, some changes in UI output happen. That makes some output less readable and could break some automated tests anticipating given preset or plugin output strings.
This commit reverts back tto the original output, using f-strings.
Resolves: #3762
---
=> [report] Revert changed formatting of plugin+presets lists

snap/snapcraft.yaml, sos.spec
According to https://spdx.org/licenses/GPL-2.0.html "GPL-2.0" is deprecated and "GPL-2.0-only" must be used instead. See: https://spdx.org/licenses/GPL-2.0-only.html
---
=> [specfile] specify GPL v2 only

sos.spec
rpm module is not being used by sos.
---
=> [specfile] drop python-rpm dependency

sos/report/plugins/kea.py
This plugin captures config files and status of
the Kea DHCPv4/DHCPv6 and DDNS server by ISC.
Related:  RHEL-40285
---
=> [kea] New plugin for kea dhcp/ddns server

sos/report/plugins/bird.py, sos/report/plugins/networking.py
Two commits that first add the `bird` plugin and second add several `devlink` commands to the `networking` plugin, originally proposed in #1541, which seems to have been abandoned.
Commits have been updated to reflect modern sos/plugin design and current state of the networking plugin.
Closes #1541 
---
=> [bird, networking] Carry forward PR 1541

sos/report/plugins/__init__.py
=> [plugins] Apply --skip-files also to destination of symlinks

sos/report/plugins/sudo.py
Capture sudo and sudoers debug log files.
---
=> [sudo] Capture sudo and sudoers debug log files

sos/report/plugins/leapp.py
The `leapp-repository` package was renamed to `leapp-upgrade-elXtoY`
in [1], and while we could list all possible combinations here,
the main `leapp` package should be enough to trigger this plugin
While at it, also enable plugin when /var/lib/leapp exists, as
after an upgrade is performed, users often uninstall the leapp packages,
but it can still be beneficial for SOS to collect data about the fact
that this is a system that was upgraded (and data about the upgrade) and
/var/lib/leapp shows exactly that.
Also include /etc/migration-results and /var/log/leapp/answerfile in
collected files.
[1] https://github.com/oamg/leapp-repository/commit/924c398a003f8ada079f2819fa3305adda7dfcda
--- …
=> [leapp] improve plugin enablement and add more collected files

sos/report/__init__.py
Replace (count, plugname) by pure plugname in two debug logs - the int is misleading rather than helping.
Resolves: #3778
---
=> [report] print plugname instead of plugin tuple

sos/report/plugins/bootc.py
Add new plugin to support bootable
containers tool bootc.
Related: RHEL PLMCORE-10590
---
=> [bootc] Add new plugin bootc

sos/report/plugins/block.py
Capture a list of clevis bindings from LUKS encrypted block devices.
Related: RHEL-57102
---
=> [block] Enhance LUKS capture in block plugin

sos/collector/sosnode.py, sos/component.py, sos/policies/__init__.py, sos/policies/distros/__init__.py, sos/policies/distros/almalinux.py, sos/policies/distros/amazon.py, sos/policies/distros/anolis.py, sos/policies/distros/azure.py, sos/policies/distros/circle.py, sos/policies/distros/cloudlinux.py, sos/policies/distros/cos.py, sos/policies/distros/debian.py, sos/policies/distros/opencloudos.py, sos/policies/distros/openeuler.py, sos/policies/distros/redhat.py, sos/policies/distros/rocky.py, sos/policies/distros/suse.py, sos/policies/distros/ubuntu.py, sos/policies/distros/uniontechserver.py
There is a common theme for new policies to subclass an existing one and just update the `check()` method. In almost all instances, the `check()` method remains almost entirely the same, simply changing a release file name or string.
Reduce repeating ourselves by consolidating this into the base `LinuxPolicy.check()`, and leverage per-policy class attributes `os_release_file`, `os_release_name`, and `os_release_id`. The first of which will enable a policy if the specified file is found. Failing that, `os_release_name` is used to check the `NAME` field in `/etc/os-release`, and `os_release_id` is used to check the `ID` field in the same file if the name pattern does not match (or is not set).
Note that we do _not_ check the `ID_LIKE` field.
This allows a policy to be defined with as little …
=> [Policy] Consolidate check() across policies

pylintrc
Disable alert for too-many-positional-arguments
---
=> [pylint] Disable alert for too-many-positional-arguments

sos/report/plugins/containerd.py
Starting with containerd 1.6.27 and 1.7.12, warnings are issued for the use of deprecated features.  The new `ctr deprecations list` command can be used to retrieve warnings.
Closes https://github.com/sosreport/sos/issues/3786
---
=> [containerd] record deprecation warnings

sos/report/plugins/pulpcore.py
These columns are either empty, containing passwords or some encoded data.
Get the *remaining* column names and query for them.
If the query for column names fail, failover to current "SELECT *".
Relevant: #3783
Resolves: #3784
---
=> [pulpcore] Don't collect args columns from tasks tables

sos/report/plugins/vmware.py
---
Howdy! In a recent case it came to my attention that this plugin wasn't triggering on Ubuntu systems on vmware estates. Since all the config files, commands, etc are all the same on Ubuntu as they are for RHEL, I gave it a quick test with these minor adjustments and found it to work swimmingly.
Let me know thoughts/opinions on this!
=> [vmware] Enable vmware plugin support on Ubuntu

sos/report/plugins/nvidia.py
Capture commands related to nvidia container toolkit.
Related: RHEL-58172
---
=> [nvidia] Capture more nvidia commands

sos/report/plugins/vdo.py
Capture more information about vdo volumes
Related: VDO-5797
---
=> [vdo] Capture more information about vdo volumes

sos/report/plugins/cgroups.py
Collect cgroup information for each process
Related: #3799
---
=> [cgroups] Collect cgroup information per process

sos/report/plugins/docker.py, sos/report/plugins/podman.py
Adds collection of container image layers for the docker and podman plugins via the `history` and `tree` subcommands repsectively.
Resolves: #3796
---
=> [docker,podman] Collect container image layers

sos/report/plugins/openshift.py
Added "openshift-kubelet" to the list of packages for the "openshift" sos plugin, so that it works in 4.16+
Related: SUPDEV-161
---
=> [openshift] Fix openshift plugin for 4.16+

sos/report/plugins/openstack_heat.py
This was discovered while verification of 4.7.2 to go into Ubuntu stable release
---
=> [heat] Obfuscate Add auth_encryption_key in config

plugins_overview.py
Running plugins_overview.py after commit be1ad32a7 resulted in the following traceback:
Traceback (most recent call last):
File "/sos_plugin_overview_fix/plugins_overview.py", line 92, in <module>
with open(os.path.join(PLUGDIR, plugfile),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object does not support the context manager protocol
This is because the call to read() returns a str and it was
happening within the 'with' statement. This fix separates the
action of opening the file via 'with' and the action of reading its content via 'read()'.
---
=> [report] Fix traceback when running plugins_overview.py

.cirrus.yml, debian/changelog, sos/report/plugins/processor.py
* Update to latest images from GCE for Ubuntu distros
* Update ubuntu_latest to be now 24.10, which was released recently
* Drop 18.04, now we want to start using python 3.8
* Update deb packaging to use latest ubuntu (24.10)
* Test ubuntu latest also using the snap
* Fix `msr` load issue, and update predicate to also include 22.04
---
=> [testing] Update Ubuntu images

sos/report/plugins/perccli2.py
=> [perccli2] Add perccli2 plugin, PERC H965 and newer controllers

sos/report/plugins/coredump.py
Refactor the plugin to adjust how `coredumpctl info` and coredump file collection is handled.
Plugin will now collect the compressed coredump file for coredump entries for which coredumpctl reports that the file is present, for the first X number of coredump files where X is the new `dumps` plugin option.
A second new plugin option, `executable`, can be used to specific a regex string to match coredump entries against to determine if they should be collected or not. The default behavior is to collect for all entries.
A symlink for coredump file collections will be dropped in the plugin directory to aide in associating dump files with coredumpctl entries, as it may not always be obvious for end users based on filenames alone.
---
Please place an 'X' inside each '[]' to confirm you adhere …
=> [coredump] Refactor info and dump collection

sos/report/plugins/ssh.py
Commands like 'ls -laZ' can take some time to run in remote filesystems, for example NFS. When you have hundreds of them, sos can take a long time to walk through it, and could be even worse if we use the option 'recursive'.
For ssh home dirs, we don't need the listing, so in this patch we detect the type of filesystem and run the command only on local ones.
Related: RHEL-22389, SUPDEV-156
---
=> [ssh] Stop collecting 'ls' information from non-local home dirs

sos/collector/sosnode.py
While parsing the output of 'sos report -l', we
were attempting to split an empty line, and
getting the following exception:
[<ip address>:_regex_sos_help] Error parsing sos help: list index out of range
Related: #3827
---
=> [collect] Fix exception while parsing sos help

sos/collector/sosnode.py
Resolves: #3827
Resolves: #3828
---
----
1. `sudo sos collect --batch  --nopasswd-sudo --ssh-key ~/.ssh/id_setasside --ssh-user project-user --nodes 192.168.124.121`
2. `sos collect --batch  --nopasswd-sudo --ssh-key ~/.ssh/id_setasside --ssh-user project-user --nodes 192.168.124.121`
3. `sudo sos collect --batch --ssh-key ~/.ssh/id_setasside --ssh-user project-user --nodes 192.168.124.121`
4. `sudo sos collect --ssh-key ~/.ssh/id_setasside --ssh-user project-user --nodes 192.168.124.121`
5. `sos collect --ssh-key ~/.ssh/id_setasside --ssh-user project-user --nodes 192.168.124.121`
6. `sudo sos collect --password --ssh-user project-user …
=> [collect] SosNode._format_cmd local node return without sudo/su when already root.

sos/report/plugins/ansible.py
The directory contains random server's files to copy, potentially with sensitive data, not relevant to any troubleshooting.
Resolves: #3845
---
=> [ansible] Forbid collecting /etc/ansible/files

man/en/sos-collect.1, sos/collector/__init__.py
Using --batch --password together in sos-collect leads to an error:
Unable to open remote session:
unsupported operand type(s) for +: 'bool' and 'str'
This PR removes the check for the batch option, enabling
the prompt for password as specified in the man page:
--batch
Run in non-interactive mode.
This will skip prompts for user input,  with  the
exception  of  a prompt for the SSH password.
Related: #3839
---
=> [collect] Fix exception when using collect with batch and password

sos/report/plugins/kubernetes.py, sos/report/plugins/microk8s.py
Also, fix command for microk8s, and use variable
---
=> [kubernetes] Add support for k8s snap

sos/options.py, sos/report/__init__.py, sos/report/plugins/__init__.py
IOError is covered by OSError since Python 3.3 so
lines like:
except (OSError, IOError) as e:
Were being marked with warning B014.
---
=> Fix duplicate-handler-exception in OSError exceptions

sos/cleaner/mappings/__init__.py, sos/cleaner/mappings/hostname_map.py, tests/cleaner_tests/full_report/full_report_run.py
Leftover from #3403 / #3496 where match_full_words_only is ignored for hostname mapping due to own get_regex_result method.
Resolves: #3593
---
=> [cleaner] Skip obfuscation of substrings for hostnames properly

sos/report/plugins/sunbeam.py, sos/report/plugins/sunbeam_hypervisor.py
* Forbid the pki folder collection newly added recently
* Add manifest collection from sunbeam
Related: SET-813
---
=> [sunbeam] Forbid pki folder & manifest inclusion

sos/report/plugins/selinux.py
`semanage` command with `boolean` and `-l` will collect all the list of booleans and put it in
`sos_commands/selinux/semanage_boolean_-l` file. It is helpful on many occasions to see if
particular boolean is enabled or not.
Signed-off-by: Shreyas Mahangade [smahanga@redhat.com](mailto:smahnaga@redhat.com)
---
=> [selinux] Add "boolean list" option to "semanage" command

man/en/sos-report.1
`--plugopts` is yet another alternative to `-k`/`--plugin-option` that sos report accepts. Let list it in man pages.
Resolves: #3865
---
=> [man] List --plugopts variant of -k/--plugin-option

sos/report/plugins/ceph_mon.py
=> [ceph_mon] Add json output for 'ceph config dump'

tests/test_data/foreman_setup.sh
=> [foreman] Update location for deb repo

sos/report/plugins/os_net_config.py
Issues with os-net-config can cause major problems with hypervisor provisioning and configuration, but the logfile is not currently captured.  Explicitly capture it.
---
=> [os-net-config] Include the os-net-config logfile

sos/report/plugins/foreman.py
production.log can (unintentionally) contain http_proxy URL including credentials. Since the URL can appear on one logline twice, obfuscating the 2nd instance is more tricky than usual.
Also, obfuscate the same password in settings table.
Related: SAT-30137
Closes: #3878
---
=> [foreman] Obfuscate http_proxy passwords

sos/report/plugins/kubernetes.py
2 small enhancements to the kubernetes plugin
I'm open to proposal for another name than `kube-system-log-files`:
```
The following plugin options are available:
kubernetes.all            on              collect all namespace output separately
kubernetes.describe       on              collect describe output of all resources
kubernetes.podlogs        on              capture stdout/stderr logs from pods
kubernetes.podlogs-filter                 only collect logs from pods matching this pattern
kubernetes.kube-system-log-files off             copy some kube-system pod logs without using the API
```
---
=> [kubernetes] add kube-system-log-files option, collect some kubelet files

sos/policies/distros/__init__.py
Fixes a bug in #3764.
A bug in the distro-identifying logic caused incorrect identification of the distro as CentOS, Fedora, or RHEL under the following conditions:
1. Distro inherits RedHatPolicy
2. Distro has either of /etc/{centos,fedora,redhat}-release
3. Policy file appears earlier than redhat.py in dictionary order
The issue occurs because the distro-identifying logic relies on the existence of the above os_release_file without examining its contents, more than checking NAME or ID in the /etc/os-release file. As a result, once /etc/{centos,fedora,redhat}-release is found, the contents of /etc/os-release are never checked, leading to distro misidentification.
At least AlmaLinux is affected by this bug.
---
```shell
$ git clone https://github.com/sosreport/sos
$ podman run -it --rm -v …
```
=> [policies] Fix bug in distro identification

sos/report/plugins/networkmanager.py
system-connections files can be found not only under /etc/NetworkManager, but also /usr/lib/NetworkManager and /run/NetworkManager, so we need to capture and post process these locations as well.
Resolves: #3875
---
=> [NetworkManager] Get system-connections files from other locations

sos/report/plugins/subscription_manager.py
Curl to https://subscription.rhsm.redhat.com contains proxy password in plaintext. That is visible in process listing, stored in cmd output filename and kept in few other places (manifest, sos.log,..).
When proxy password is set, use an auxiliary curl config file to store the password.
Resolves: #3880
---
=> [subscription_manager] Obfuscate proxy password from curl cmdline

sos/report/plugins/__init__.py, sos/report/plugins/foreman.py
=> [foreman] Obfuscate http_proxy passwords. PR-3878 improvement

sos/collector/transports/saltstack.py
=> [collector] Saltstack transport remote_exec handle stderr like other transports

README.md
Adds a couple helpful badges to the top-level README. In particular, adds a python version badge showing our minimum supported version.
---
=> [readme] Add badges to repo README

sos/report/plugins/foreman_installer.py
=> [foreman_installer] Collect correct satellite_metrics.yml

sos/report/plugins/aap_containerized.py
This commit checks that the output of the command:
'podman ps -a --format {{{{.Names}}}}'
Ran without errors, so the container names returned is correct.
Resolves: RHEL-77339
---
=> [aap_containerized] Check podman command for errors before using it

sos/report/plugins/python.py
The idea is to be able to see the path where the module is installed. So I would prefer to having 
```
Package                         Version   Location                               Installer
------------------------------- --------- -------------------------------------- ---------
aiodns                          3.0.0     /usr/lib/python3.9/site-packages
aiofiles                        22.1.0    /usr/lib/python3.9/site-packages
aiohttp                         3.9.2     /usr/lib64/python3.9/site-packages
```
Over
```
Package                         Version
------------------------------- ---------
aiodns                          3.0.0
aiofiles                        22.1.0
aiohttp                         3.9.2
```
to ease my troubleshooting of support-cases, where we suspect the module …
=> [python] Collect verbose output via pip

sos/report/plugins/__init__.py, sos/utilities.py, tests/report_tests/plugin_tests/defaults.py, tests/unittests/utilities_tests.py
Instead of generating all the logs and tailing the last 100M, we get the first 100M of 'journalctl --reverse' that we then reverse again using our own implementation of tac.
To handle multiline logs we would need to use "tac -brs '^[^ ]'" that takes ~30s on 100M of logs when plain 'tac' takes ~0.3s. Our simple implementation in python takes 0.7s, and avoid an extra dependency.
On journalctl timeout we now get the most recents logs.
During collection logs are now buffered on disk, so we use 2xsizelimit. While running our tac we could actually truncate the source file to limit disk usage. Previously buffering was in RAM (also 2xsizelimit).
On my test server, logs plugin runtime goes from 34s to 9.5s.
Fixes https://github.com/sosreport/sos/issues/3615
---
Please place an 'X' inside each '[]' …
=> [utilities,plugins] speedup journal collection (v2)

sos/report/plugins/openvswitch.py
Without meters, we lack complete visibility into OpenFlow, which 
means we cannot fully monitor the networking activities in 
OCP/OSP that rely on meters through OVN.
This change adds both necessary outputs.
Signed-off-by: Flavio Leitner <fbl@redhat.com>
---
=> [openvswitch] Dump meter configuration and stats.

.cirrus.yml, debian/control, tests/product_tests/foreman/foreman_tests.py, tests/report_tests/plugin_tests/apt/apt.py, tests/report_tests/plugin_tests/defaults.py, tests/report_tests/plugin_tests/krb5.py, tests/report_tests/smoke_tests.py, tests/sos_tests.py
* Add new debian_only to replace current ubuntu_only.
* ubuntu_only now only tests true for only Ubuntu distros.
* Add extra packages to install for Debian ditsros, as these are not installed by default.
As per discussions in the maintainer call, wanted to start testing more on Debian, and this is a first start on testing debian regularly
---
=> [testing] Add debian to standard testing

sos/report/plugins/__init__.py, sos/report/plugins/containerd.py, sos/report/plugins/crio.py, sos/report/plugins/gluster.py
Two patchset that:
First, updates `Plugin.get_process_pids()` with a new `exact` argument that, if `True`, will only return PIDs that exactly match the given string, which is necessary to capture the "root"/"main" `containerd` process(es) for the second patch.
Second, adds a `containerd.stackdump` option that, if enabled, will send `SIGUSR1` to the containerd process(es) to trigger writing stack dumps to disk, then marking them for collection.
Resolves: #3918 
---
=> [containerd] Add option to collect stack dump files

LICENSE, sos/report/plugins/omnipath_client.py, sos/report/plugins/omnipath_manager.py
While packaging for Fedora, rpmlint detected incorrect FSF address in a few files. Updating with most recent version of GPLv2 text from <https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt>
---
=> Update FSF address in license text

README.md
Also fix the new package names in both Ubuntu and Debian to point to sos instead of sosreport.
---
=> [doc] lintian fix to reduce the line size

sos.spec
- add /etc/sos which was unowned
- address forbidden `%{pythonX_site(lib|arch)}/*` in `%files` See <https://pagure.io/packaging-committee/issue/782>
- trimmed trailing whitespaces
---
=> [packaging] address fedora-review issues

sos/cleaner/__init__.py, sos/collector/__init__.py, sos/component.py, sos/upload/__init__.py
The function _fmt_msg() was in three different subsystems. This commit removes the code from collector, cleaner, and upload into SosComponent.
Related: #3746
---
=> [component] Move _fmt_msg() to SoSComponent

sos/report/plugins/networking.py
If a user uses `.yml` for a netplan configuration file, netplan silently ignores it. I've engaged with upstream since that behavior isn't ideal, but it isn't likely that it will change soon.
This at least gives us better visibility without needing to worry about obfuscating the contents of other (possibly malformatted) files.
---
=> [networking] List contents of netplan configuration dirs

sos/report/plugins/memory.py
Changes to THP result in sysfs `enabled` file alone (and the kernel parameter) are now insuffiecient to know if THP is enabled or not. For example, `shmem_enabled` can be set to `[always]` while `enabled` can be set to `[never]` and THP will still be enabled but only for shmem segments. As such, to better know if and how THP is enabled, collect all files under `/sys/kernel/mm/transparent_hugepage/` rather than just `enabled`.
Fixes #3945 
---
=> [memory] Collect all sysfs THP files

sos/report/plugins/openvswitch.py
OpenvSwitch stores important settings in the manager table so we should include it in the table we capture.
---
- [x ] Is the subject and message clear and concise?
=> Include manager table in ovs captured data

sos/report/plugins/helm.py
This commit adds a new sos report plugin that performs some basic output
collection from several helm commands to view the installed
repositories, plugins, and charts.
Closes #3504
Signed-off-by: Bryan Fraschetti <bryan.fraschetti@canonical.com>
---
=> [helm] Created new sos report plugin for Helm

sos/report/plugins/iscsi.py
Obfuscate discovery and node seesion passwords that can be found in other files inside /var/lib/iscsi directory.
Related: RHEL-81187
---
=> [iscsi] Add /var/lib/iscsi/send_targets to the obfuscation list

sos/cleaner/preppers/usernames.py, sos/report/plugins/login.py
Add lslogin and lastlog2 output. Then use these for username obfuscations for clean. New distros don't have lastlogin anymore and last is not always installed by default.
timout: is excluded as well. When the command is run, it runs with timout command, and if the command doesn't exist, it parses that as the username.
Related: #3960
---
=> [login,clean] Update login plugin and use for clean

sos/report/plugins/cups.py
Add new command captures to the cups plugin.
Also, add a new option, 'userconfs', that when enabled is used to capture config files inside .cups in users' home directories.
Related: SUPDEV-171
---
=> [cups] Expand captures in cups plugin

sos/report/plugins/foreman.py
To know the configured subnets in Foreman is helpful for debugging issues because it provides critical network-related data that assists in troubleshooting deployment, provisioning, and communication problems.
---
- [X ] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [X ] Are any related Issues or existing PRs [properly …
=> [foreman] Add subnets table information

sos/report/plugins/charmed_mysql.py
This plugin is intended to add support for Charmed MySQL deployments. 
An example of the output for the report can be found here: [Charmed MySQL example report](https://drive.google.com/drive/folders/1SyFB5T0JNM8ey-dMRRp4Ju8MGW7_dF2x?usp=sharing)
Please note: this PR requires PR #3968 to be merged before this is functional.
---
=> [charmed_mysql] Add Charmed MySQL support

sos/report/plugins/cups.py, sos/report/plugins/ssh.py
.. otherwise self.get_option(..) returns string that can be wrongly evaluated as a bool statement. That namely affects ssh plugin where overriding default True to False/off/0 has no real effect.
Resolves: #3973
---
=> [ssh,cups] Dont set val_type=str for bool PluginOpt

sos/report/plugins/pulseaudio.py, sos/report/plugins/soundcard.py
This commit adds a new plugin for pulseaudio, which is the default sound server middleware package in Ubuntu LTSes up to and including Jammy as well as RedHat up to and including RHEL 9. The plugin collects the output of commands that list the detected sinks, sources, and soundcards, which helps determine the available input and output audio devices. The other commands included aid in determining any applied configurations which may affect the prioritization of device selection.
It seemed appropriate to move the add_copy_spec of the pulseaudio directory from the soundcard plugin to the new pulseaudio plugin for organizational structure, grouping it with the rest of the package's collection. Especially as Ubuntu LTSes will be using Pipewire by default from Noble onwards, so PulseAudio is …
=> [pulseaudio]: Created new plugin for pulseaudio

sos/report/__init__.py
With the current size, we have some misaligned options:
lvm2.metadata             off             attempt to collect headers
and metadata via pvck
networking.traceroute     off             collect a traceroute to
www.example.com
networking.namespace-pattern                 Specific namespace names
or patterns to collect, whitespace delimited.
networking.namespaces     0               Number of namespaces
to collect, 0 for unlimited
networking.ethtool-namespaces on              Toggle if ethtool
commands should be run for each namespace
networking.eepromdump     off             Toggle collection
of 'ethtool -e' for NICs
ostree.fsck               off             collect ostree fsck
Increasing it from 25 from 30 seems to cover all options.
---
Please place an 'X' inside each '[]' to confirm …
=> [report] Increase column size for plugin options

sos/policies/auth/__init__.py
Change calls to deprecated datetime.utcnow to datetime.now.
---
=> [policies|auth] Move away from deprecated datetime.utcnow

sos/report/plugins/tomcat.py
`/etc/tomcat/keystore` is assumed to contain just keystores to application's data - let preventively don't collect it.
Closes: #3991
---
=> [tomcat] skip collecting keystore

.cirrus.yml
The family name for the GCP images for Fedora have been updated to include the arch, so we need to update our cirrus config accordingly.
---
=> [cirrus] Update Fedora GCP image family name

sos/report/plugins/lustre.py
These increase the debug values for lustre OSD devices without wildly expanding size of data.
---
=> [lustre] Add more OSD values

sos/policies/distros/redhat.py
At some point, Fedora packaging switched to placing `sos` into `/usr/bin` instead of `/usr/sbin` like RHEL does. Update this in policy so that `sos collect` calls the proper location on remote Fedora hosts.
---
=> [FedoraPolicy] Update sos binary path for collect

sos/report/plugins/boot.py
---
It is very often to check the default kernel set for the boot case(always set one kernel version, but boot with different kernel version, or forget to set). so add it:
```
/boot/vmlinuz-5.14.0-427.35.1.el9_4.x86_64
```
=> [boot] add default kernel show

sos/report/plugins/chrony.py
Capture logs in /var/log/chrony
Related: RHEL-84134
---
=> [chrony] Capture chrony logs

sos/report/plugins/ceph_common.py
Since the last update to the ceph_common plugin, microceph has added
new features and commands such as microceph pool list, microceph remote
list, and microceph replication list rbd. This commit collects the output of
those commands
Signed-off-by: Bryan Fraschetti <bryan.fraschetti@canonical.com>
=> [ceph_common]: Add New Microceph Commands

sos/report/plugins/ssh.py
Collecting that still causes issues similar to mounting NFS.
Since the data are rarely used, let change the default of ssh.userconfs to False.
Closes: #4009
---
=> [ssh] Disable default listing of users's .ssh dirs

sos/report/plugins/kdump.py
Capture the newly added vmcore-creation.status
under var/crash/<vmcore-dir>/
Related: RHEL-91178, RHEL-29941
---
=> [kdump] Capture vmcore-creation.status file

sos/report/plugins/dnf.py
Examples of credentials:
`/var/log/dnf.librepo.log`:
2025-05-20T11:28:23+0200 INFO Downloading: https://username:password@host.name.com/some/path/repodata/repomd.xml
or `/etc/yum.repos.d/cutom.repo` having either of:
baseurl = https://username:password@host.name.com/some/path/
gpgkey = https://username:password@host.name.com/some/path/GPG-KEY.pub
Closes: #4018
---
=> [dnf] Scrub passwords in repository URIs

sos/report/plugins/leapp.py
That file overrides default dnf.conf during leapp (pre)upgrade.
Closes: #4023
---
=> [leapp] collect /etc/leapp/files/dnf.conf

sos/cleaner/preppers/hostname.py
HostnamePrepper should always be fed by FQDN to ensure domain names are recognized properly.
This is important esp. when:
- /etc/hosts is empty
- "hostname" contains shortname only
- "hostname -f" contains FQDN
Resolves: #4022
Closes: #4026
---
=> [cleaner] Use "hostname -f" in HostnamePrepper

sos/report/plugins/foreman.py
Useful for Host inventory upload issues against console.redhat.com.
Closes: #4044
---
=> [foreman] Collect `/var/lib/foreman/red_hat_inventory` dir list

sos/report/plugins/juju.py
By default the introspect commands are aliases in the bash login profile, so these won't be available via sos. This extraplotes the commands that are available and passes it to juju-introspect.
---
=> [juju] Fix juju agent introspect commands

sos/report/plugins/networking.py
Capture more ethtool, ss, and netstat command
outputs.
Related: #3708
---
=> [networking] Capture more networking commands

sos/report/plugins/tftpserver.py
Add /var/lib/tftpboot to the directory listing.
This is the default directory for boot files for tftp booting. 
Reference: /usr/share/doc/tftp-server/README.security
Signed-off-by: Charlie Krell <ckrell@redhat.com>
---
=> [tftpserver] Add Directory Listing /var/lib/tftpboot

sos/upload/__init__.py
This commit fix a backtrace that appears when
the user cancels a file upload after authentication.
Related: RHEL-94968
---
=> [upload] Fix backtrace when cancelling upload

sos/report/plugins/aap_containerized.py
Add commands to list_instance and check_licenses.
Closes: AAP-22872, RHEL-93893
Signed-off-by: Lucas Benedito <lbenedit@redhat.com>
---
=> [aap_containerized] Add container command

sos/component.py
Rather than using /var/tmp by default, grab the tmp_dir from the policy. The default will be from tempfile.gettempdir() from the sos.policies, so should be getting it from the OS default.
Closes: #4061
---
=> [component] Grab tmpdir from policy

sos/report/plugins/saltmaster.py
- Obfuscates root level passwords, secrets and keys
- Includes api and encryption keys, but keeps original negative lookbehind for any other "key"
- Obfuscates a pillar root in any collected path in addition to `/etc/salt`
Closes #4058
---
=> [saltmaster] Obfuscate pillar roots in any path

sos/report/plugins/kdump.py, sos/report/plugins/release.py
Change the format of the import line for plugins
to parenthesis so it matches what we do in all
other plugins that contain multiline imports.
Also, this change ensures that the script
plugins_overview.py's output is consistent
across all plugins and doesn't contain
errors.
Related: #4071
---
=> [kdump|release] Change format of imports

sos/report/plugins/subscription_manager.py
Obfuscate proxy env variables from the curl
command.
Related: RHEL-103749
---
=> [subscription_manager] Obfuscate proxy env variables

sos/upload/targets/redhat.py
Resolve an issue where sos could ask twice for a case id.
Related: RHEL-95366
---
=> [upload] Avoid asking twice for case id

sos/upload/__init__.py
Use importlib.import_module(modname) instead of python internal __import__ method
Closes: #4082
=> [upload] Only load sos upload targets and not its policies

sos/report/plugins/__init__.py, sos/report/plugins/pulpcore.py, sos/report/plugins/rhui_containerized.py, sos/utilities.py
As RHUI5 will run inside a container run under a non-root user, this PR aims to:
1) Enhance `add_copy_spec` to collect files from containers run as non-root.
2) Support scrubbing secrets in files collected from containers
3) Enhance pulpcore plugin to collect the same data but within the `rhui5-rhua` container under `rhui` user
4) Add a new `rhui_containerized` plugin to collect RHUI5 specific data, as well as collect postgres data (enhancing postgres plugin would make more mess than gain, esp. due to `find` method)
---
=> [report] Add rhui_containerized plugin

sos/cleaner/__init__.py, sos/cleaner/archives/__init__.py, sos/cleaner/archives/sos.py, sos/cleaner/mappings/__init__.py, sos/cleaner/mappings/ip_map.py, sos/cleaner/mappings/ipv6_map.py, sos/cleaner/mappings/mac_map.py, sos/cleaner/parsers/__init__.py, sos/cleaner/parsers/hostname_parser.py, sos/cleaner/parsers/ip_parser.py, sos/cleaner/parsers/ipv6_parser.py, sos/cleaner/parsers/keyword_parser.py, sos/cleaner/parsers/mac_parser.py, sos/cleaner/parsers/username_parser.py, tests/cleaner_tests/existing_archive.py, tests/unittests/cleaner_tests.py
Draft version adding to the traditional sequential backend also sqlite3 and file based concurrent ones.
TL;DR: please review the idea, test it and comment or ack or nack the approach. Then I will fix the TODOs.
Let me explain various factors and reasons that affected the chosen implementation.
As very very first, I implemented both sqlite3 and files based approaches, see reasoning below. And left the original behaviour just for (performance) comparison (it must be run with `-j 1`).
First, mappings are very independent objects that do maintain their dataset on their own. Even adding an item to obfuscate (say, FQDN) means the dataset is updated a few times (by the host, FQDN and/or domain). I tried to respect this as I like that independency (and also changing it would require a lot of …
=> [cleaner] Make cleaner concurrent inside one archive

sos/report/plugins/__init__.py, sos/report/plugins/openshift_ovn.py
This Update allows a specific container runtime to be passed to add_cmd_output so commands that must use a specific runtime do so.
Related: SUPDEV-180
---
=> [openshift_ovn] Allow specific container runtime for plugin command

sos/report/plugins/md.py
WHile plugin execution makes sense only when mdadm package is installed.
Closes: #4095
---
=> [md] Condition the plugin by mdadm package

sos/upload/targets/__init__.py, sos/upload/targets/redhat.py
Uploads of files greater than 1Gb switch to go to sftp. The code incorrectly tried to write to the home directory in sftp, but should switch into the /{user} directory instead so proper permissions exist.
Related: RHEL-52919
---
=> [upload] Enable sos uploads of files bigger than 1Gb

sos/report/plugins/apt.py
The command apt-mark showhold is useful to show what packages have been marked as 'held' in apt, as this can lead to a variety of issues.
---
- [ X] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issue …
=> [apt] add list of held apt packages sos_commands

sos/report/plugins/__init__.py, sos/report/plugins/logs.py
Add a new option to capture sparse files' size when running ls.
Also, add this new option to the call in the 'logs' plugin.
---
=> [plugin] Add a new option to capture spare files' size with the 'ls' command

sos/report/plugins/loki.py
Plugin for Loki, a logs backend by Grafana. If run from a Loki container, it fetches Loki internal logs and config (both on paths from a regular container / standalone installation as well as the charmed version). If `-k loki.fetch-logs=true` is passed, it also calls Loki API to fetch logs. 
---
=> [loki] Fetch loki logs

sos/report/plugins/podman.py
Collect detailed disk usage of Podman resources, including images, containers, and volumes.
---
=> [podman] collect podman disk usage

sos/report/plugins/block.py
Capture the /etc/crypttab file
Related: RHEL-108949
---
=> [block] Capture the /etc/crypttab file
