sosreport/sos

sos/plugins/tuned.py

Collect additional configurations files and profiles for tuned.
Resolves Issue #232

[tuned] Collect additional configurations files for tuned.

---

sos/plugins/openstack_sahara.py

Signed-off-by: Rohan Kanade <rkanade@redhat.com>

Remove Secrets from openstack_sahara plugin data

---

sos/plugins/ceph.py

Add calamari and radosgw logs, calamari config
Add & update few ceph commands output
Resolves: #496
Resolves: rhbz#1210527
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

[ceph] add logs, report and calamari conf

---

sos/plugins/apache.py

Signed-off-by: Hisanobu Okuda <hokuda@redhat.com>

[apache] Added collection for JBoss Web Server

---

sos/utilities.py

Fixes #720 
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

[utilities] remove unused hashlib import

---

sos/utilities.py

[utilities] Support glob expansion in command arguments

---

sos/plugins/lightdm.py

Signed-off-by: Bryan Quigley <bryan.quigley@canonical.com>

[lightdm] Add missing "" to command

---

sos/plugins/docker.py

Adds output for 'docker inspect' for each unique image on the host.

[docker] Collect image inspect output

---

sos/plugins/networking.py

This commit adds collection of more detailed link information, and the configuration of macsec devices.

[networking] collect more link data from iproute

---

sos/plugins/samba.py

Guenther
Signed-off-by: Guenther Deschner <gd@samba.org>

Fix dc-connect winbind logfile path for samba plugin

---

sos/plugins/iscsi.py

Signed-off-by: Louis Bouchard <louis.bouchard@canonical.com>

[iscsi] Enable plugin for Ubuntu and Debian

---

sos/plugins/targetcli.py

collecting the /sys/kernel/config/target
Signed-off-by: venkata edara <redara@redhat.com>
---

[targetcli] added one item

---

sos/plugins/cs.py

Red Hat Certificate System 9 (Dogtag 10) has been out for a while.
This commit adds the ability to capture those logs and config
files for each subsystem.
Added pki-base because redhat-pki or dogtag-pki do not have to be
installed to build a Certificate Authority.
Removed "/usr/share/java/pki" check because CS 9 uses the same
directory.
Signed-off-by: Brian Gribble <bgribble@redhat.com>
---

[cs] Add Certificate System 9 data capture

---

tests/plugin_tests.py

[unittest] Added recursive symlink unittest

---

sos/plugins/infiniband.py

[infiniband] fix ports_cmds typo

---

sos/plugins/kernel.py

As copying of them hangs.
Resolves: #1445
---

[kernel] dont collect some tracing instance files

---

sos/plugins/composer.py

[composer] add missing commas in list in add_copy_spec

---

sos/plugins/satellite.py

Recursive listing of the directory is sufficient.
Resolves: #1555
---

[satellite] don't collect /root/ssl-build

---

sos/plugins/__init__.py
sos/plugins/corosync.py
sos/plugins/ovirt.py

Fix ovirt regex formatting

---

sos/plugins/subscription_manager.py

Collect subscription-manager release [--show|list] that helps
identifying yum/dnf issues with inaccessible repositories.
Resolves: #1912
---

[subscription_manager] Collect release info

---

setup.py
sos.spec
sos/__init__.py
sos/archive.py
sos/options.py
sos/policies/__init__.py
sos/policies/redhat.py
sos/report/__init__.py
sos/report/plugins/__init__.py
sos/report/plugins/navicli.py
sos/report/plugins/ovn_central.py
sos/report/plugins/xfs.py
sos/report/reporting.py
sos/utilities.py
tests/archive_tests.py
tests/plugin_tests.py
tests/utilities_tests.py

Resolves: #2006
Signed-off-by: Bryan Quigley <bryan.quigley@canonical.com>
---

[global] Drop use of python six and other 2.X bits

---

sos/plugins/__init__.py
sos/plugins/redis.py

[redis] Collection of redis from scl

---

.cirrus.yml
tests/product_tests/foreman/foreman_tests.py
tests/sos_tests.py

Adding an integration test for the Foreman project, which feeds into RH Satellite.
These tests will be gated to only run when a PR is posted that affects the plugins related to Foreman/Satellite, or the cirrus config itself.
---

[tests] Add CI testing for foreman 

---

sos/report/plugins/rpm.py

Removes the use of awk in the `rpm` command that generates the
`installed-rpms` output, instead relying on rpm's builtin query tags.
Further removes the `add_rpm_cmd` method and directly calls
`add_cmd_output` with the proper parameters now.
Resolves: #2548
---

[rpm] Use query tags and drop use of piping to awk

---

sos/report/plugins/python.py

Collect "pip list installed" for all versions of pip.
Resolves: #2592
---

[python] collect all pips installed lists

---

sos/report/plugins/__init__.py
sos/report/plugins/ansible.py
sos/report/plugins/pulpcore.py
sos/report/plugins/rhui.py

Two commits patchset that fixes some findings from using `pulpcore` and `rhui` plugins on a real environment.
Individual commit messages provide more descriptive explanation.
Resolves: #2593
---

Sos pmoravec rhui fixups

---

sos/cleaner/__init__.py
sos/collector/__init__.py
sos/report/__init__.py

Unify --map[-file] argument among report/collect/clean.
Resolves: #2602
---

[report,collect] unify --map-file arguments

---

sos/collector/__init__.py
sos/options.py

Sos pmoravec config file honoring all longopts

---

sos/policies/distros/uniontechserver.py

Signed-off-by: liugang <liuganga@uniontech.com>
---

[policies] add uniontech os policy support

---

sos/report/plugins/sar.py

Currently, the plugin captures only files
with the format saDD. If an user enables the
option -D, the format changes to saYYYYMMDD.
By using this regex, we gather both formats
while ignoring .xz files and other non-sar
files.
Resolves: #2633 
---

[sar] Capture all formats of sar files

---

sos/report/plugins/qaucli.py

[qaucli] Add QLogic plugin support

---

sos/report/plugins/storcli.py

[storcli] Add LSI MegaRAID device support

---

sos/report/plugins/ipmitool.py

[ipmitool] Include channel, raw, and lan information.

---

sos/report/plugins/smclient.py

[smclient] Add SANtricity storage device (NetApp) support

---

sos/report/plugins/networking.py

Alongside of that, unify list of collected ethtool short options
with list of tags added.
Resolves: #2634
---

[networking] collect 'ethtool -m'

---

sos/report/plugins/storcli.py

[storcli] Add 'json' option collecting data in JSON format.

---

sos/report/plugins/pulp.py

Closes #2564
Signed-off-by: Barbora Vassova bvassova@redhat.com
---

[pulp] adding obfuscation of proxy_password in /etc/pulp/server/plugins.conf.d/

---

sos/report/plugins/rhui.py

- obfuscate "rhui_manager_password: xxx" in /root/.rhui/answers.yaml*
- no need to collect or obfuscate anything from /etc/ansible/facts.d
- newly detect the plugin via /etc/rhui/rhui-tools.conf file or rhui-manager
command (only)
Resolves: #2637
---

[rhui] Update the plugin on several places

---

sos/report/plugins/opencontrail.py

Signed-off-by: Matt Criswell <mcriswell@mirantis.com>
---
- [ x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [ x] Is the subject and message clear and concise?
- [ x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x ] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [x ] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-is …

[opencontrail] adds a plugin for opencontrail

---

tests/sos_tests.py

Previously new test cases had to be written in such a way that they
could be run on any supported distribution, even if their individual
tests were all marked for specific distributions. Use of the distro-only
decorators would fail when applied to test cases as a whole due to how
test instantiation errors are handled.
To address this, provide a distro check within `BaseSoSTest` so that
tests can be made distro-specific and we can signal to avocado to skip
all tests within that test case without failing the test suite entirely.
---

[tests] Allow entire test classes to be distro specific

---

sos/report/plugins/openstack_instack.py

Currently TripleO supports using additional yaml files to define
resource overrides.
- hieradata_override
- net_config_override
Because these files are useful when checking configurations in
an undercloud node, this change makes sosreport capture these yaml
files. The undercloud.conf file is parsed to look up these yaml files.
Signed-off-by: Takashi Kajinami <tkajinam@redhat.com>
---
- [ X ] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [ X ] Is the subject and message clear and concise?
- [ X ] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if …

[openstack_instack] Capture yaml files to define overrides

---

sos/report/plugins/sapnw.py

For better complexity of code i am proposing
check for len(fields) >= 7 as we later in code
getting fields[7] values.
Resolves: #2647
---

[sapnw] Add condition for length of fields var

---

sos/policies/distros/openeuler.py

Signed-off-by: lijingwei <lijingwei@uniontech.com>
---

[policies] add openeuler policy support

---

sos/report/plugins/ceph.py

RH Ceph 4 can either be installed as RPM or as containers. The changes
permits to collect the ceph config on both kind of setup.
Signed-off-by: Teoman ONAY <tonay@redhat.com>
This is an alternative to PR https://github.com/sosreport/sos/pull/2180 which didn't progress for a year. Instead of having a new plugin for containerized Ceph, I followed the request from the maintainers asking to put everything in one plugin.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1882544
---

[Ceph] Add support for containerized Ceph setup

---

sos/report/plugins/ssh.py

The SSH daemon will not accept connection for users whose `.ssh`
forlders don't have proper permissions set. This change makes
the ssh plugin to list (ls -laZ) the `~/.ssh` folders of
all users found in the system.
Closes #2658
Signed-off-by: Maciej Strzelczyk <strzelczyk@google.com>
---

[ssh] Include info about ~/.ssh folders of users.

---

sos/report/plugins/foreman.py
sos/report/plugins/foreman_proxy.py

On Debian the Apache package is named apache2 and this is also used in directory paths such as /etc/apache2 and /var/log/apache2.
---

[foreman] Correct Apache package on Debian

---

sos/report/plugins/openstack_octavia.py

Currently, we're collecting loadbalancer details from nodes by running
specific commands irrespective of whether octavia client package is
installed or OS_* env variables are set required for collecting
LoadBalancer or its associated subcommands information.
This patch adds a check for both environment variables and whether
octavia package is installed.
Resolves: #2670
Signed-off-by: Purandhar Sairam Mannidi <pmannidi@redhat.com>
---

[openstack_octavia] Stop collecting Loadbalancer details

---

snap/snapcraft.yaml

After discussion with the snapcraft team, this fits the bill
for a classic snap
Closes: #1992
Supersedes: #2233 
Reference: https://forum.snapcraft.io/t/25673
Reference: https://forum.snapcraft.io/t/26447
Signed-off-by: Nicolas Bock nicolas.bock@canoical.com
---

Add snap configuration file

---

sos/report/plugins/origin.py

Removed the diagnostics part as it is no longer maintained and doesn't
work on Openshift.
Adding additional projects to collect.
Removed getting all namespaces as it is not needed for troubleshooting
and project names are sensitive for some customers.
Adding condition to collect the logs from systemd openshift services if
not running as static pods.
Signed-off-by: Vladislav Walek <22072258+vwalek@users.noreply.github.com>
---

[origin] Removing unused configuration

---

sos/report/plugins/networking.py

If iptables has built-in nf_tables kmod, then
'ip netns <foo> iptables-save' command requires the kmod which must
be guarded by predicate.
Analogously for ip6tables.
Resolves: #2703
---

[networking] prevent iptables-save commands to load nf_tables kmod

---

sos/report/plugins/__init__.py

[plugins] remove py2/3 relict in __nonzero__ / __bool__

---

sos/component.py

If the `TMPDIR` env var is set, we should reference it if the user has
not provided `--tmp-dir` by the cmdline or sos.conf.
The order of precedence is now:
1. cmdline use of `--tmp-dir`
2. setting `tmp-dir` in `/etc/sos/sos.conf`
3. the `TMPDIR` environment variable
4. `/var/tmp` as a default
Closes: #2738
---

[sos] Reference TMPDIR environment variable if set

---

sos/report/__init__.py

Enhance --estimate-mode to calculate sizes of also:
- symlinks
- directories themselves
- manifest.json file
Use os.lstat() method instead of os.stat() to properly calculate the
sizes (and not destinations of symlinks, e.g.).
Print five biggest plugins instead of three as sos logs and reports do
stand as one "plugin" in the list, often.
Resolves: #2752
---

[report] Calculate sizes of dirs, symlinks and manifest in estimate mode

---

sos/report/plugins/networking.py

Collect "ip route cache" data
Fixes https://github.com/sosreport/sos/issues/2757
Signed-off-by: Michael Cambria <mcambria@redhat.com>
---

[Networking] Collect "ip route cache" data

---

sos/report/plugins/nvidia.py

This patch is to update nvidia plugin to collect
logs for Nvidia GPUs
Signed-off-by: Mamatha Inamdar <mamatha4@linux.vnet.ibm.com>
Reported-by: Borislav Stoymirski <borislav.stoymirski@bg.ibm.com>
Reported-by: Yesenia Jimenez <yesenia@us.ibm.com>
---
- [x ] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x ] Is the subject and message clear and concise?
- [x ] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x ] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [x ] Are any …

[nvidia]:Patch to update nvidia plugin for GPU info

---

sos/policies/distros/__init__.py
sos/policies/distros/redhat.py

Update SFTP API from v1 to v2.
Also set remote filename as fname stripped from its path.
---

[redhat] SFTP api change

---

sos/collector/clusters/ocp.py

[clusters:ocp] fix get_nodes function

---

sos/report/plugins/networkmanager.py

[networkmanager] Add journal logs for NetworkManager plugin

---

sos/report/plugins/unbound.py

Initial version of the plugin.
Resolves: #2789
Related to: rhbz#2018228
---

[unbound] Add new plugin for Unbound DNS resolver

---

sos/report/plugins/cman.py

Resolves: #2792
Closes: #2791
---

[cman] remove debugfs handling dead code

---

sos/report/plugins/rhui.py

Rhui new log folder

---

sos/report/plugins/foreman_proxy.py

Foreman new vhosts

---

sos/collector/__init__.py
sos/report/__init__.py

Signed-off-by: Jeremy Coulombe <jeremy.coulombe@hotmail.fr>
closes #2802
---
- [X ] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X ] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?

[report][collector]Fix typo in sensitive in collector and report init

---

sos/report/plugins/crio.py

According to instructions in https://github.com/cri-o/cri-o/blob/main/tutorials/debugging.md
Signed-off-by: Peter Hunt <pehunt@redhat.com>
---

[crio] Collect goroutine information

---

sos/collector/__init__.py

OCP project wasn't deleted e.g. if node filter returned empty list
---

[collector] Add cluster cleanup for all exit() calls

---

sos/report/plugins/ceph_mds.py

Enhance the ceph_mds plugin to collect data specific
to mds nodes.
Related: #1945
Resolves: #2800
---

[ceph_mds] Collect mds specific data in ceph_mds

---

sos/report/plugins/perccli.py

PowerEdge RAID Controller management
https://www.dell.com/support/kbdoc/en-us/000177280/how-to-use-the-poweredge-raid-controller-perc-command-line-interface-cli-utility-to-manage-your-raid-controller
---

[perccli] Add new plugin

---

sos/report/plugins/__init__.py
sos/report/plugins/virsh.py

[virsh] Call virsh commands in the foreground / with a TTY

---

sos/report/plugins/foreman.py

In dynflow >=1.6.3, dynflow* tables in postgres are encoded by
msgpack which makes plain CSV dumps unreadable. In such a case,
psql-msgpack-decode wrapper tool from dynflow-utils (of any
version) must be used instead of the plain psql command.
Resolves: #2830
---

[foreman] Use psql-msgpack-decode wrapper for dynflow >= 1.6

---

snap/snapcraft.yaml

After testing directly from snapcraft server, there was an
issue wrt classic snaps and paths. This update resolved this
particular issue
---

[snapcraft] Update snapcraft.yaml

---

sos/report/plugins/foreman_installer.py

The file keeps status of foreman-maintain activitis in progress.
Resolves: #2847
---

[foreman-installer] collect foreman-maintain config and storage data

---

sos/collector/sosnode.py

Adds a fallback version check for 4.2-13 for RHEL downstreams that
backport the `container-runtime` option into sos-4.2.
Carry this in upstream to account for use cases where a workstation used
to run `collect` from may be from a different stream than those used by
cluster nodes.
---

[sosnode] Handle downstream versioning for runtime option check

---

sos/report/plugins/smartcard.py

smartcards: Add more related files and packages

---

sos/report/plugins/collectd.py
sos/report/plugins/openstack_aodh.py
sos/report/plugins/openstack_ceilometer.py

[Plugins] Adjust paths for containerized setup

---

sos/report/plugins/openstack_nova.py

Update the openstack plugin to collect nova metadata logs
---

[openstack_nova] Collect containerized metadata logs

---

sos/report/plugins/sar.py

The conversion of 'saX' binary data to human-readable 'sar' format is
typically handled by sysstat on the host system when a new day rolls
over the previous 'saX' file. As such, there should generally only be
one day (the current day's data) that needs manual conversion. For this
reason, limit our calling of 'sar' to files that have not been converted
already _and_ are less than a week old, to avoid spending time
converting very old files that are likely not useful.
Further, remove the shell encapsulation of the sar command.
Finally, add a docstring description of the plugin for `sos help`
output.
Closes: #1741
--- …

[sar] Limit sar conversion by age, remove shell encapsulation

---

sos/report/plugins/openshift.py

Opening the PR to implement the usage of localhost.kubeconfig present only on masters to use it when collecting data from the API.
Localhost kubeconfig is file containing the cert/key for system:admin user.
Signed-off-by: Vladislav Walek <22072258+vwalek@users.noreply.github.com>
---

Adding ability to use the localhost.kubeconfig 

---

sos/report/plugins/openshift_ovn.py

Should have been done here [PR#2883](https://github.com/sosreport/sos/pull/2883) together with adding new container for collection
---

[openshift_ovn] Add one more container for plugin enablement

---

sos/plugins/foreman.py

In dynflow >=1.6.3, dynflow* tables in postgres are encoded by
msgpack which makes plain CSV dumps unreadable. In such a case,
psql-msgpack-decode wrapper tool from dynflow-utils (of any
version) must be used instead of the plain psql command.
Resolves: #2900
Signed-off-by: Barbora Vassova <bvassova@redhat.com>
---

[foreman] Use psql-msgpack-decode wrapper for dynflow >= 1.6 

---

sos/report/plugins/candlepin.py

This change should start to collecting information about
SCA enablement per organization.
Resolves: #2901
Related: RHBZ2060925
---

[candlepin] collect information about SCA

---

man/en/sos-collect.1
sos/collector/__init__.py
sos/collector/transports/oc.py
sos/options.py

Set --force-pull-image=True by default, can be turned off with
--force-pull-image=False
---

[collector] Use --force-pull-image option for pods created with oc

---

sos/collector/clusters/ocp.py
sos/report/plugins/openshift.py

Previously, in #2888, the `openshift` plugin was extended to allow API
collections by using a default-available kubeconfig file rather than
relying on user-provided tokens. This also included flipping the default
value of the `no-oc` plugin option to `True` (meaning do not collect API
output by default).
This worked for the plugin, but it introduced a gap in `sos collect`
whereby the cluster profile could no longer reliably enable API
collections when trying to leverage the new functionality of not
requiring a user token.
Fix this by updating the cluster profile to align with the new
default-off approach of API collections.
Along with this, add a toggle to the cluster profile directly to allow
users to toggle API collections on or off (default off) directly. This
is done via a new …

[ocp, openshift] Re-align API collection options and rename option

---

sos/report/plugins/corosync.py
sos/report/plugins/pacemaker.py

Modifies the collection specs for pacemaker and corosync logs to also
include rotated copies. Additionally add collections of `pengine` files
for pacemaker.
---

[pacemaker,corosync] Collect rotated logs

---

sos/report/plugins/shmcli.py

Make matching 'DELL' case insensitive.
Signed-off-by: Nikhil Kakade <nikhilkaka1@gmail.com>
---

    [shmcli] Make matching 'DELL' case insentitive.

---

sos/policies/runtimes/crio.py

crictl added a field to the `crictl ps` output and that broke parsing - now we use json output format that (hopefully) won't change in the future
---

[runtimes:crio] switch from parsing output in table format to json

---

sos/report/plugins/openvswitch.py

The next OVS release will be numbered 3.0.
In a near future, the Red Hat Fast Datapath channel will provide
packages versionned in a same manner.
Signed-off-by: David Marchand <david.marchand@redhat.com>
---

[openvswitch] Extend package version pattern

---

sos/report/plugins/openstack_aodh.py

This change ensures a few more sensitive values are masked when
gathering the config file for the Aodh service.
Signed-off-by: Takashi Kajinami <tkajinam@redhat.com>
---

[openstack_aodh] Mask more sensitive values

---

sos/collector/__init__.py

There were multiple exit paths and behaviors within sos collect, that
were not the easiest to logically follow. Fix this by standardizing on
leveraging `self.exit()` to exit in all situations. If a message is
provided to this call, it is regarded as an error message and logged as
such. This method will still set the exit code according to the `error`
parameter, however that has been changed to default to 0 to signify a
"clean" end of execution.
Finally, there is a new `force` parameter which is meant to be used when
exiting from within a child thread when the entire process needs to exit
(and thus needs to leverage the lower-level `os._exit()` instead).
Closes: #2882
---
Please place an 'X' inside each '[]' to confirm you adhere to our …

[collect] Standardize use of `exit()`

---

snap/snapcraft.yaml

[snap] Update snapcraft.yaml to fix PYTHONPATH

---

sos/report/plugins/hpssm.py

[ssacli] Add ssacli plugin to gather status and config detail for HPE Smart Storage Array controllers.

---

snap/snapcraft.yaml

* Previous commit for dist was wrong, and required site-packages instead
* sos report was unablt to run in bionic, and required python3-magic as
dependancy
---

[snap] Further fixes in snapcraft.yaml for build and run

---

.cirrus.yml

[testing] Test building of snap

---

sos/report/plugins/containerd.py
sos/report/plugins/crio.py
sos/report/plugins/docker.py

Add crio support for COS
Signed-off-by: Varsha Teratipally <teratipally@google.com>
---

[crio] add crio and containerd plugin support for Cos

---

sos/report/plugins/fapolicyd.py

Collect all relevant config files, a logfile and a few CLI check
outputs.
Resolves: #3020
---

[fapolicyd] Add plugin for Fapolicyd framework

---

sos/collector/clusters/ocp.py

Newer OCP versions have a more restrictive default deployment configuration. As such, add the required labels to the temporary namespace/project we use for collections.
---

[ocp] Add newly required labels to temp OCP namespace

---

sos/report/plugins/dnf.py

- collect legacy yum->dnf symlinks
- collect dnf global vars
- obfuscate all passwords in all vars
---

[dnf] Collect legacy yum config and dnf global vars

---

.cirrus.yml

Updates the images used for CentOS Stream 8/9.
---

[cirrus] Update CentOS image versions

---

sos/report/plugins/etcd.py

Today, etcd is almost exclusively deployed in a container for kubernetes/OCP clusters. This commit serves to update the plugin to be primarily designed for those types of deployments, and removes the v1 and v2 collections.
Resolves: #2906
---

[etcd] Update plugin for containerized deployment

---

snap/snapcraft.yaml

* Using the python from pip rather than the package
* Fine tune the environment, so less repetitive
Closes: #3044
---

[snap] fix python_magic with snap

---

sos/report/plugins/ovn_central.py

This additional command will tell us the ovn_controller connection 
status to OVN SBDB.
This is done thanks to ovn-appctl command using -t option to specify
the target over the ovn_controller socket, a function has been created
in order to located the ovn_controller socket path that is name is
different from each controller node.
---

[ovn_central] Query ovn_controller SBDB connection with ovn-appctl

---

.github/workflows/snap.yaml

When a any MRs or commits are added to the main branch then automatically create a snap, and push to latest/edge channel
---

[build] Build snap and push to latest/edge

---

.github/workflows/snap.yaml

* snapcraft-channel was the old method, updating to release
* fetch all history, so that the version of the snap will be based on the latest tag plus the number of commits since
---

[build] Update snap push workflow

---

.github/codeql/codeql-config.yaml
.github/workflows/codeql.yaml
README.md
sos/collector/__init__.py
sos/collector/clusters/__init__.py
sos/report/__init__.py
sos/report/plugins/networking.py
sos/report/plugins/openstack_instack.py
sos/utilities.py

LGTM is shutting down shortly, as it has been folded into GH CodeQL. As such, we need to switch over to using CodeQL to maintain automatic code analysis.
Do this by using the provided CodeQL workflow configuration, and add a config file to limit the analysis to the appropriate `sos/` directory.
---

[testing] Switch to CodeQL from LGTM

---

sos/report/plugins/postfix.py

Changed to sosreport exclude files set by following options.
- `lmtp_sasl_password_maps`
- `smtp_sasl_password_maps`
- `postscreen_dnsbl_reply_map`
- `smtp_sasl_auth_cache_name`
Resolvs : #3073
Signed-off-by: Iwao Miyake <miyake.iwao@fujitsu.com>
---

[postfix] Exclude password files

---

sos/report/plugins/nfs.py

Collect nfsd information:
- The contents of /proc/fs/nfsd
- The output of nfsdclnts
Signed-off-by: Thiago Rafael Becker <thiago.becker@gmail.com>
---

[nfs] add nfsd information collection

---

.gitignore

Ignore the entirety of the `.idea/` directory within the repo for anyone using PyCharm as an IDE.
---

[devel] Ignore entire .idea/ directory from pycharm

---

sos/policies/distros/circle.py

Circle Linux is an production-ready distribution from RHEL.
Signed-off-by: Bella Zhang <bella@cclinux.org>
---

[policies] Add policy for Circle Linux

---

sos/report/plugins/pcp.py

fix spelling error
Signed-off-by: lilinjie <lilinjie@uniontech.com>
---

[pcp] fix typo

---

sos/policies/distros/opencloudos.py

Add a basic policy for OpenCloudOS distributions. 
Signed-off-by: zoedong <zoedong@tencent.com>
---

[policies] Add policy for OpenCloudOS

---

.cirrus.yml

Update most of the GCE images we use for CI testing to their latest releases for their respective versions.
---

[cirrus] Update GCP images

---

sos/report/plugins/foreman_openscap.py

Collect /etc/foreman_scap_client/config.yaml on any Foreman OpenSCAP client system.
Resolves: #3115
---

[foreman_openscap] Add foreman OpenSCAP client plugin

---

sos/collector/exceptions.py
sos/collector/sosnode.py
sos/collector/transports/saltstack.py

Closes #3085 
Signed-off-by: Trevor Benson <trevor.benson@gmail.com>
---

[sos collector] - Add SaltStack Transport 

---

tests/cleaner_tests/ipv6_test/ipv6.py
tests/cleaner_tests/ipv6_test/ipv6_test.py
tests/cleaner_tests/ipv6_test/sos-test-ipv6.txt

Relates: #3060
Signed-off-by: Miroslav Hradilek <mhradile@redhat.com>
---

[test] Add stage 2 test for ipv6 obfuscation

---

sos/report/plugins/azure.py

- add `--noproxy` option
- update api-version to `2021-01-01`
- add query parameter `format=json`
Reference: [official document](https://learn.microsoft.com/en-us/azure/virtual-machines/linux/instance-metadata-service?tabs=linux) 
---

[Azure] Update curl command for Azure Metadata

---

sos/report/plugins/microshift.py
sos/report/plugins/microshift_ovn.py

Add MicroShift initial plugin.
Does not share code with OpenShift plugin because of little similarity except helper functions. Preferred to keep it separated as MicroShift is far apart from OCP in terms of similarity and might evolve differently.
---

Add MicroShift plugin

---

sos/presets/redhat/__init__.py
sos/report/plugins/ostree.py

[presets] drop --verify from RHOCP preset, call "ostree fsck" under plugin specific option

---

.cirrus.yml

[testing] Grab snap build logs on failure

---

sos/report/plugins/unpackaged.py

If a file in $PATH is unpackaged symlink leading to a (packaged) file, print rather the symlink instead of its destination, including whole symlink chain to the destination.
This prevents confusion when `unpackaged` reports a file owned by a package, instead of an unpackaged symlink leading to it.
Further, add trailing '\n' to nonempty output.
Resolves: #3157
Relevant: rhbz#2169684
---

[unpackaged] Print unpackaged symlinks instead of targets

---

sos/report/plugins/__init__.py
sos/report/plugins/ceph_iscsi.py

Signed-off-by: Raimund Sacherer <rsachere@redhat.com>
---

[plugins:__init__] Fixing comment typo

---

sos/report/plugins/ovn_central.py

The upcoming u/s OVN release will introduce a new command called
'debug/chassis-features-list', this patch add to the ovn_central
plugin's list of commands, in order to promptly obtain this
information.
Note that in case the OVN version doesn't support this command,
the plugin will not crash but instead save as output 'not a 
valid command' msg.
Also a small refactor has been carried out in terms of reuse, 
for function _find_sock, as ovn-appctl commands for northd service
need to run over specific socket.
---

[ovn_central] add command ovn-appctl debug/chassis-features-list

---

.cirrus.yml

Routine update of the images used by our CI testing in GCP
---

[cirrus] Update CI testing images

---

sos/policies/distros/redhat.py

Fixes #3190
---
- [X ] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [X ] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [X ] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) …

[redhat] Fix commercial URL

---

sos/policies/distros/mariner.py

[policies] Add CBL-Mariner policy

---

sos/report/plugins/lustre.py

[lustre]: Collect job_stats and export information

---

sos/report/plugins/ceph_mon.py

[ceph]: dump mon's config database

---

sos/policies/package_managers/snap.py

[snap] add snap pkg manager

---

sos/collector/clusters/juju.py
tests/unittests/juju/juju_cluster_tests.py

Fix below two scenarios:
1. If subordinate's parent is missing.
2. If subordinate's parent's units is missing.
Closes: #3213
---

[juju] Fix cluster collection doesn't work in 2 scenarios

---

sos/report/plugins/elastic.py

[elastic] Add shard, aliases and update log collection

---

sos/report/plugins/ubuntu.py

* Add new command to check status using `pro`
* Add json format for the status command
* Add /var/log/ubuntu-advantage-timer* logs
Related: #3224
---

[ubuntu] Update plugin to support pro

---

sos/report/plugins/lxd.py

[lxd] Add logs from the snap

---

sos/report/plugins/alternatives.py

[alternatives] Add ubuntu section

---

sos/policies/distros/azure.py

[policies] Mariner has been rebranded to Azure Linux

---

sos/report/plugins/landscape.py

[landscape] Add more logging

---

sos/report/plugins/lstopo.py

This package is the one for ubuntu to run the lstopo command
---

[lstopo] Add detection for hwloc package

---

sos/report/plugins/apache.py
sos/report/plugins/openstack_aodh.py
sos/report/plugins/openstack_ceilometer.py
sos/report/plugins/openstack_cinder.py
sos/report/plugins/openstack_glance.py
sos/report/plugins/openstack_gnocchi.py
sos/report/plugins/openstack_heat.py
sos/report/plugins/openstack_horizon.py
sos/report/plugins/openstack_keystone.py
sos/report/plugins/openstack_manila.py
sos/report/plugins/openstack_neutron.py
sos/report/plugins/openstack_nova.py
sos/report/plugins/openstack_octavia.py
sos/report/plugins/openstack_placement.py
sos/report/plugins/openstack_sahara.py
sos/report/plugins/openstack_swift.py
sos/report/plugins/openstack_trove.py

Update the apache plugin to only collect the defaults and update the openstack bits to collect specifics for their service
Closes: #2525
---

[openstack_*][ubuntu] Update paths and collections

---

snap/snapcraft.yaml

Originally, it was working by coincidence
Reference: https://github.com/canonical/rockcraft/issues/225#issuecomment-1597025315
---

[build][snap] Fix build of snap

---

sos/report/plugins/vault.py

[vault] Add vault plugin

---

sos/report/plugins/__init__.py
sos/report/plugins/collectd.py
sos/report/plugins/grafana.py
sos/report/plugins/juju.py
sos/report/plugins/openssl.py
sos/report/plugins/openstack_ansible.py
sos/report/plugins/openstack_aodh.py
sos/report/plugins/openstack_barbican.py
sos/report/plugins/openstack_ceilometer.py
sos/report/plugins/openstack_cinder.py
sos/report/plugins/openstack_designate.py
sos/report/plugins/openstack_glance.py
sos/report/plugins/openstack_heat.py
sos/report/plugins/openstack_horizon.py
sos/report/plugins/openstack_instack.py
sos/report/plugins/openstack_ironic.py
sos/report/plugins/openstack_keystone.py
sos/report/plugins/openstack_manila.py
sos/report/plugins/openstack_neutron.py
sos/report/plugins/openstack_nova.py
sos/report/plugins/openstack_octavia.py
sos/report/plugins/openstack_placement.py
sos/report/plugins/openstack_sahara.py
sos/report/plugins/openstack_swift.py
sos/report/plugins/openstack_trove.py
sos/report/plugins/ovirt.py
sos/report/plugins/salt.py
sos/report/plugins/saltmaster.py

Add a common regex for re.MULTILINE so that doesn't need to be defined and remove the definitions where `(?m)` is being defined
Closes: #3301
---

[plugins] py311 fix for re.M

---

sos/report/plugins/samba.py

[plugins/samba] collect output of 'net ads info'

---

sos/report/plugins/openshift_ovn.py

This updates openshift_ovn plugin to collect ovn db files and logs when it is running with interconnect configuration.
---

[openshift_ovn] Collect db files for ovn interconnect environment

---

sos/report/plugins/ultrapath.py

Relevant: rhbz2187407
Resolves: #3328
Author: Nitin U. Yewale <nyewale@redhat.com>
---

[ultrapath] Add new plugin for Huawei UltraPath

---

README.md

[readme] Update for snap status and installation

---

.cirrus.yml

[cirrus] Update gce images

---

sos/report/plugins/selinux.py

[selinux] Add ubuntu check and plugin

---

sos/report/plugins/openstack_masakari.py
sos/report/plugins/openstack_masakarimonitors.py

[masakari] Add masakari plugin

---

sos/report/plugins/rpmostree.py

[rpmostree] Enhance status output with more details

---

sos/report/plugins/microshift.py

[microshift] Add microshift-etcd.scope service

---

sos/report/plugins/microshift.py

[microshift] Add /etc/microshift file copy spec

---

sos/report/plugins/openvswitch.py

Add commands that report info about DPDK lcore usage, log levels and memory usage.
---

[openvswitch] Add DPDK info commands

---

sos/report/plugins/foreman.py

collect schema_migrations from foreman

---

sos/report/plugins/networking.py

[networking] obfuscate password in netplan

---

sos/report/plugins/microshift.py

[microshift] Fix microshift-etcd.scope journal retrieval

---

sos/policies/distros/redhat.py
sos/policies/package_managers/flatpak.py

[flatpak] Add flatpak pkg manager

---

sos/report/plugins/opensvc.py

[opensvc] Add relay config dump

---

sos/report/plugins/logs.py

[logs] Add auth.log collection to the logs plugin

---

requirements.txt
setup.py
sos.spec

This is a followup for 56904018045fdbdad666e55f0a850bc365809e50
---

[build] Actually indicate this requires packaging

---

sos/policies/runtimes/lxd.py

Sometimes the update_sources attribute is not available so cannot build the list
---

[lxd_runtime] Fix image metadata

---

sos/policies/package_managers/__init__.py

[package_manager] Remove unused method pkg_nvra

---

debian/control

Related: #3398
Related: #3383
Resolves: SET-326
---

[deb][packaging] Use python3-packaging as default

---

sos/report/plugins/libvirt.py

[libvirt] Add snapshot xml files

---

sos/report/plugins/pam.py

Collect current auth profile details.
Resolves: #3438
Relevant: RHEL-18576
---

[pam] Collect "authselect current"

---

sos/report/plugins/arcconf.py

Currently, the arcconf getconfig and GETLOGS commands are added with the assumption that the system has only one controller with ID 1. It is possible that a system can have multiple controllers, so commands need to be added to extract information for all available controllers.
The arcconf utility does not have a dedicated command to get the list of controllers available in the system. Therefore, parse the 'arcconf list' output to obtain the controller ID for all controllers in the system, and add getconfig and GETLOGS commands for each available controllers.
---

[arcconf] add getconfig and GETLOGS commands for all available controllers

---

sos/report/plugins/omnipath_client.py
sos/report/plugins/omnipath_manager.py

[omnipath] Enable UbuntuPlugin

---

sos/report/plugins/slurm.py

[slurm] Add configless support

---

sos/report/plugins/openvswitch.py

Add driverctl persistant overrides and more dpdk mempool info

---

.packit.yaml

Enables packit to build and provide repositories for centos stream 8 and stream 9.
---

[packit] Configure copr builds for centos stream

---

sos/report/plugins/convert2rhel.py

Capture the txt and json files generated when analyzing the system for pre-conversion to RHEL.
Related: RH: RHEL-21331
---

[convert2rhel] Capture information about pre-conversion

---

sos/report/plugins/rhui.py

Fixes: https://issues.redhat.com/browse/RHEL-21490
---
- [ x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [ x] Is the subject and message clear and concise?
- [x ] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- Please advise what ^ this means.
- [x ] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved …

[rhui] Added the rhui-installer directory to rhui sos plugin

---

sos/report/plugins/networking.py

This patch fixes the ss predicate on Ubuntu by selecting the necessary kernel modules to load based on dist_version.
---

[networking] Add ss predicate for Ubuntu

---

sos/report/plugins/aap_eda.py

Adding the file 'aap_eda.py' for the sos report collects  
the files used for troubleshooting issues at 
Ansible Automation Platform Event Driven Controller
---

[aap_eda] Add a new AAP EDA plugin.

---

sos/report/plugins/aide.py

[aide] Add Aide support

---

sos/report/plugins/nvme.py

[nvme] Added few new spec paths
---

[nvme] Added few new spec paths

---

sos/report/plugins/snap.py

Closes: #2241
Resolves: #2257
Signed-off-by: Adam R Bell <adam.bell@canonical.com>
---

[snap] Collect state.json file, omitting sensitive data.

---

sos/report/plugins/lxd.py

The list of modules was too broad, and depending on the different attributes configured the list of modules to be loaded could also be different. Liaising with the LXD team suggested to check for the `snap.lxd.daemon` service rather then the modules to collect `lxd.buginfo`. This is due to the fact that LXD is socket activated, and running any lxd based command could start the service and hence load the modules. Gating this with either the `snap.lxd.daemon` for snap or `lxd` service for debs respectively should prevent this from happening.
This also no obfuscates the certificate that is retrieved from `lxd.buginfo`
Resolves: SET-377
---

[lxd] Fix predicate for lxc commands collection for snap

---

sos/report/plugins/openstack_cinder.py
sos/report/plugins/openstack_glance.py
sos/report/plugins/openstack_heat.py
sos/report/plugins/openstack_neutron.py
sos/report/plugins/openstack_nova.py
sos/report/plugins/openstack_placement.py

Similar to how we do in openstack_nova, collect commands from cinder and collect all the detals of the glance images.
Resolves: SET-337
---

[openstack] Add collection of commands

---

sos/report/plugins/infinidat.py

Adding a plugint to collect:
- infinidat storage logs
- some info that could be useful for debugging purposes
Resolves: SET-454
---
- [ x ] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [ x ] Is the subject and message clear and concise?
- [ x ] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [ x ] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?

[infinidat] Add infinidat plugin

---

sos/report/plugins/vectordev.py

[vectordev] Add new vectordev plugin

---

debian/control

---
- [xIs the subject and message clear and concise?

[Ubuntu] Change Ubuntu maintainer

---

sos/report/plugins/microk8s.py

[microk8s] Add obfuscation for client.config

---

sos/report/plugins/libvirt.py

[libvirt] Capture virtlogd.conf

---

plugins_overview.py
tests/unittests/archive_tests.py
tests/unittests/cleaner_tests.py
tests/unittests/conformance_tests.py
tests/unittests/plugin_tests.py
tests/unittests/policy_tests.py
tests/unittests/report_tests.py

[pep8][tests] Update flake8 styling

---

docs/index.rst

doc: fix github url

---

sos/collector/sosnode.py

Ensure that we format the package versions to the pep440 standard. This is necessary as we are using `parse_version()` from the `packaging` package to verify that the sos collector node version is equal or bigger than the versions we are collecting from the nodes. If we pass the wrong format to `parse_version()`, we are unable to do the comparison and unable to run `sos report` on those nodes.
This addresses the issue of the Ubuntu packaging version naming with `+` and `~` signals as well as generic versioning schemes.
Resolves: #3544 
---

[collect] refactor _format_version

---

sos/report/plugins/foreman.py

Modify queries sorting by started_at so we can obtain recent tasks, plans, actions and steps
---

[foreman] Sort foreman_tasks_tasks by started_at asc

---

sos/report/plugins/proxmox.py

[proxmox] Add new plugin for Proxmox Virtualization Environment

---

debian/control

This will ensure that we have the right python version dependancy for deb packages.
Resolves: SET-543
---

[pkg][debian] Add python version dependancy

---

sos/report/plugins/ceph_mds.py
sos/report/plugins/ceph_mgr.py
sos/report/plugins/ceph_osd.py
sos/report/plugins/ceph_rgw.py

[ceph] Add Microceph support for RGW and MDS

---

sos/report/plugins/process.py

Collect also processor ID assigned to the process (psr).
Resolves: #3575
Relates to: RHEL-26246
---

[process] ps output to collect also psr column

---

sos/report/plugins/aap_controller.py

Adding the file 'aap_controller.py' for the sos report collects
The files used for troubleshooting issues at
Ansible Automation Platform Automation Controller
Related: RH AAP-18409
Signed-off-by: Lucas Benedito <lbenedit@redhat.com>
---

[aap_controller] Implementing AAP Automation Controller Plugin

---

sos/report/plugins/kernel.py

Copy the kernel config - `/boot/config-{kernel-version}`
---

[kernel] Copy the kernel config

---

sos/report/plugins/ceph_common.py

[snap] Collect more info on microceph snap

---

sos/report/plugins/kubernetes.py

Add more resources to output when kubernetes.all option is true. Output json format if kubernetes.all option is true. Export pod logs to an individual file for each container, so the plugin can export logs if there are multiple containers in a pod.
---

[kubernetes] k8s improvements for Charmed Kubernetes

---

.cirrus.yml
sos/policies/runtimes/lxd.py
tests/cleaner_tests/basic_function_tests/report_with_mask.py
tests/collect_tests/help_output_tests.py
tests/report_tests/basic_report_tests.py
tests/report_tests/encryption_tests.py
tests/report_tests/exception_tests.py
tests/report_tests/options_tests/options_tests.py
tests/sos_tests.py
tests/unittests/policy_tests.py

This PR is to ensure that we test against the upcoming releases of ubuntu, so that we don't encounter issues at release time, and we can solve these before releases
---

[cirrus] Run tests on latest daily builds for ubuntu

---

sos/report/plugins/kafka.py

Adding a plugin to collect:
- Kafka logs and config files
- basic installation info for debugging purposes
Resolves: SET-96
---
- [ x ] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [ x ] Is the subject and message clear and concise?
- [ x ] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [ x ] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ x ] Are all passwords or private data gathered by this PR [obfuscated](https://github.com/sosreport/sos/wiki/How-to-Write-a-Plugin#how-to …

[kafka] Add kafka plugin

---

.cirrus.yml
tests/collect_tests/help_output_tests.py
tests/sos_tests.py
tox.ini

Extra changes required due to module and function changes
---

[avocado] Upgrade avocado to 103.X LTS

---

sos/report/plugins/aap_receptor.py

*[aap_receptor]** Add receptorctl work list output

---

sos/report/plugins/kdump.py

This change collects kdump information for Azure Linux.
With this change, we will check the 'path' variable in /etc/kdump.conf to check where information is being dumped.
If get_vm_core is set to true, collect the latest vm core created
in the last 24 hours that is <= 2GB
---

[kdump] Create AzureKDump class

---

sos/report/plugins/ceph_common.py

[ceph] Add more microceph commands

---

sos/report/plugins/aap_receptor.py

[aap_receptor] Add receptor status output

---

sos/report/plugins/pulp.py

This change, allows the sosreport to collect the
settings.local.py file, when customer has custom changes out of the default settings.py file.
---

[pulp] Including settings.local.py file to be collected and parsed.

---

sos/report/plugins/openvswitch.py
sos/report/plugins/ovn_host.py
sos/report/plugins/sunbeam.py
sos/report/plugins/sunbeam_hypervisor.py

Refactor ovn_host and openswitch plugins to utilise the commands from
sunbeam
Closes: #3297
Resolves: #3586
Related: SET-87
---

[sunbeam] Add new plugin for sunbeam

---

sos/cleaner/mappings/hostname_map.py
sos/collector/__init__.py
sos/policies/__init__.py
sos/presets/redhat/__init__.py
sos/report/__init__.py
sos/report/plugins/ssh.py

Resolve the remaining handful of alerts from CodeQL, while others have been manually dimissed after review.
---

[CodeQL] Resolve remaining alerts from CodeQL scans

---

sos/report/plugins/openstack_neutron.py

[neutron] Don't collect ml2 certs

---

tests/report_tests/encryption_tests.py
tests/report_tests/help_output_tests.py
tests/report_tests/plugin_tests/networking/networking.py
tests/report_tests/smoke_tests.py
tests/sos_tests.py
tests/unittests/conformance_tests.py

[pylint] Convert all tests to f-strings (part 2)

---

.cirrus.yml

Updates the CentOS Stream image versions to their current latest builds.
---

[cirrus] Update CentOS Stream image versions

---

sos/report/plugins/lvm2.py

---
- [X ] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved …

[lvm2] fetch lock_type for the vg

---

sos/report/plugins/filesys.py

---
- [X ] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [X ] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved …

[filesys] show filesystem type in df command

---

sos/report/plugins/gfs2.py

Capture output of tunegfs2 for mounted GFS2
filesystems.
Related: RHEL-40871
---

[gfs2] Capture output of tunegfs2

---

sos/report/plugins/__init__.py

The `maxage` argument in PlugIn's `add_copy_spec` method doesn't work, and when it is passed it will raise an exception:
```
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/sos/report/__init__.py", line 1231, in setup
plug.setup()
File "/usr/lib/python3.9/site-packages/sos/report/plugins/pod_log.py", line 33, in setup
self.add_copy_spec(
File "/usr/lib/python3.9/site-packages/sos/report/plugins/__init__.py", line 1815, in add_copy_spec
files = list(filter(lambda f: time_filter(f), files))
File "/usr/lib/python3.9/site-packages/sos/report/plugins/__init__.py", line 1815, in <lambda>
files = list(filter(lambda f: time_filter(f), files))
File "/usr/lib/python3.9/site-packages/sos/report/plugins/__init__.py", line 1810, in time_filter
(maxage and (time()-filetime < …
```

[plugins] Fix add_copy_spec's maxage argument

---

sos/report/plugins/ssh.py

Fine tune the code to use the pwd module, this ensures that we are not parsing getent or the `/etc/passwd` file
---

[ssh] Use pwd module for passwd data

---

sos/report/plugins/curtin.py
sos/report/plugins/system.py
tests/report_tests/plugin_tests/curtin/curtin-install-cfg.yaml
tests/report_tests/plugin_tests/curtin/curtin-install.log
tests/report_tests/plugin_tests/curtin/curtin.py

[curtin] New plugin curtin

---

sos/report/plugins/process.py

Capture debug and features files from
/sys/kernel/debug/sched/
Related: RHEL-44353
---

[process] Capture sched debug and features

---

sos/report/plugins/krb5.py

---
- [ X] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?
- [ X] Are all passwords or private data gathered by this PR …

[Krb5]  Additon of keytab Validation

---

sos/report/plugins/microcloud.py

This implements a new small plugin support for the MicroCloud snap.

[microcloud] Added new plugin support for MicroCloud.

---

.cirrus.yml
man/en/sos-report.1

[man] Fix man page lintian issue from Debian packaging

---

pylintrc
sos/archive.py

[pylint] Re-enable useless-parent-delegation

---

docs/conf.py
pylintrc
sos/__init__.py
sos/report/__init__.py
tests/unittests/juju/juju_cluster_tests.py
tests/unittests/plugin_tests.py

[pylint] Re-enable W0622: redefined-builtin

---

sos/report/plugins/ceph_rgw.py

[ceph] Expand Ceph RGW data collection

---

pylintrc
sos/archive.py
sos/utilities.py
tests/sos_tests.py

[pylint] Re-enable redefined-outer-name

---

pylintrc
sos/archive.py
sos/cleaner/archives/__init__.py
sos/cleaner/mappings/hostname_map.py
sos/cleaner/mappings/ipv6_map.py
sos/cleaner/preppers/mac.py
sos/collector/__init__.py
sos/collector/clusters/kubernetes.py
sos/collector/clusters/ovirt.py
sos/collector/sosnode.py
sos/collector/transports/__init__.py
sos/collector/transports/saltstack.py
sos/options.py
sos/policies/auth/__init__.py
sos/policies/distros/__init__.py
sos/policies/distros/redhat.py
sos/policies/distros/ubuntu.py
sos/report/__init__.py
sos/report/plugins/__init__.py
sos/report/plugins/ovn_central.py
sos/utilities.py
tests/sos_tests.py

[pylint] re-enable no-else-return and inconsistent-return-statements

---

pylintrc
sos/archive.py
sos/collector/clusters/__init__.py

[pylint] Re-enable assignment-from-no-return

---

sos/report/plugins/pam.py

Capture authselect config file
Related: RHEL-48608
---

[selinux] Capture authselect config file

---

docs/conf.py
pylintrc
sos/archive.py
sos/cleaner/__init__.py
sos/cleaner/archives/__init__.py
sos/cleaner/mappings/ip_map.py
sos/cleaner/mappings/mac_map.py
sos/cleaner/preppers/keywords.py
sos/collector/__init__.py
sos/collector/clusters/__init__.py
sos/collector/clusters/juju.py
sos/collector/transports/control_persist.py
sos/collector/transports/saltstack.py
sos/component.py
sos/policies/__init__.py
sos/policies/distros/__init__.py
sos/policies/distros/redhat.py
sos/policies/init_systems/__init__.py
sos/report/__init__.py
sos/report/reporting.py
sos/utilities.py
tests/report_tests/plugin_tests/logs.py
tests/sos_tests.py
tests/unittests/juju/juju_cluster_tests.py
tests/unittests/juju/juju_transports_test.py
tests/unittests/plugin_tests.py

[pylint] Re-enable unused-{variable, argument}

---

pylintrc
sos/__init__.py
sos/archive.py
sos/cleaner/archives/__init__.py
sos/cleaner/mappings/hostname_map.py
sos/collector/__init__.py
sos/collector/sosnode.py
sos/collector/transports/__init__.py
sos/collector/transports/control_persist.py
sos/options.py
sos/policies/__init__.py
sos/policies/distros/__init__.py
sos/policies/distros/redhat.py
sos/presets/redhat/__init__.py
sos/report/__init__.py
sos/report/plugins/__init__.py
sos/report/plugins/lvm2.py
sos/report/plugins/openstack_edpm.py
sos/report/plugins/openstack_novajoin.py
sos/report/plugins/qpid.py
sos/report/plugins/shmcli.py
sos/report/reporting.py
sos/utilities.py
tests/sos_tests.py
tests/unittests/juju/juju_transports_test.py
tests/unittests/option_tests.py
tests/unittests/plugin_tests.py

The following are fixed & enabled in this PR:
- consider-using-in
- superfluous-parens
- no-else-raise
- useless-object-inheritance
- consider-using-sys-exit
---

[pylint] re-enable checks

---

plugins_overview.py
pylintrc
sos/__init__.py
sos/cleaner/mappings/hostname_map.py
sos/cleaner/mappings/ip_map.py
sos/cleaner/parsers/ipv6_parser.py
sos/collector/__init__.py
sos/collector/clusters/__init__.py
sos/collector/clusters/ocp.py
sos/help/__init__.py
sos/options.py
sos/policies/__init__.py
sos/policies/distros/__init__.py
sos/policies/distros/redhat.py
sos/report/__init__.py
sos/report/plugins/__init__.py
tests/sos_tests.py

[pylint] Re-enable consider-using-dict-items

---

pylintrc
sos/collector/__init__.py

---
- [] Are all passwords or private data gathered by this PR [obfuscated](https://github.com/sosreport/sos/wiki/How-to-Write-a-Plugin#how-to-prevent-collecting-passwords)?

[pylint] Enable consider-using-set-comprehension

---

pylintrc
sos/collector/__init__.py
sos/policies/distros/__init__.py
sos/policies/package_managers/__init__.py
sos/report/__init__.py
sos/report/plugins/__init__.py
tests/unittests/juju/juju_cluster_tests.py

- modified-iterating-list
- cell-var-from-loop
- use-implicit-booleaness-not-len
- try-except-raise
- use-implicit-booleaness-not-comparison
---

[pylint] Re-enable the following checks

---

pylintrc
sos/collector/__init__.py
sos/collector/transports/control_persist.py
sos/component.py
sos/policies/__init__.py
sos/policies/distros/__init__.py
sos/policies/distros/suse.py
sos/report/__init__.py
sos/report/plugins/__init__.py
sos/report/reporting.py
tests/unittests/plugin_tests.py
tests/unittests/report_tests.py
tests/unittests/utilities_tests.py

The following are addressed here:
- redundant-u-string-prefix
- simplifiable-if-expression
- consider-using-generator
- access-member-before-definition
- simplifiable-if-statement
- signature-differs
---

[pylint] Fix pylint issues

---

pylintrc
sos/cleaner/mappings/__init__.py
sos/cleaner/mappings/ip_map.py
sos/cleaner/mappings/ipv6_map.py
sos/cleaner/mappings/username_map.py
sos/collector/clusters/ocp.py
sos/policies/__init__.py
sos/policies/distros/redhat.py
sos/policies/distros/ubuntu.py
tests/unittests/plugin_tests.py

[pylint] Fix arguments-renamed and arguments-differ

---

debian/copyright
snap/snapcraft.yaml
sos.spec
sos/report/plugins/microcloud.py
sos/report/plugins/omnipath_client.py
sos/report/plugins/omnipath_manager.py

[global] Change license to GPL-2.0 across all files

---

pylintrc
sos/collector/__init__.py
sos/collector/clusters/ocp.py
sos/collector/clusters/pacemaker.py
sos/options.py
sos/report/plugins/__init__.py
sos/report/reporting.py

Fixes unnecessary-{negation,dunder-call,comprehension,lambda}.
---

[pylint] Re-enable unnecessary-{negation,dunder-call,comprehension, lambda}

---

pylintrc
sos/archive.py
sos/collector/clusters/__init__.py
sos/component.py
sos/policies/__init__.py
sos/policies/distros/__init__.py
sos/policies/init_systems/__init__.py
sos/policies/package_managers/__init__.py
sos/report/plugins/__init__.py
tests/sos_tests.py
tests/unittests/policy_tests.py

[pylint] Fix abstract-method and unnecessary-pass

---

pylintrc
sos/__init__.py
sos/cleaner/mappings/hostname_map.py
sos/cleaner/mappings/ip_map.py
sos/collector/__init__.py
sos/collector/sosnode.py
sos/policies/__init__.py
sos/policies/distros/__init__.py
sos/policies/init_systems/__init__.py
sos/policies/package_managers/__init__.py
sos/report/__init__.py

[pylint] Fix consider-iterating-dictionary

---

pylintrc
sos/report/__init__.py
sos/utilities.py
tests/sos_tests.py

[pylint] Fix logging-not-lazy

---

pylintrc
sos/collector/clusters/__init__.py
sos/collector/clusters/juju.py
sos/collector/clusters/openstack.py
sos/collector/transports/juju.py
sos/component.py
sos/options.py
sos/policies/distros/__init__.py
sos/report/__init__.py
tests/sos_tests.py

[pylint] Fix raise-missing-from

---

sos/report/plugins/foreman.py
sos/report/plugins/foreman_proxy.py

Add ALL_PROXY and NO_PROXY to collected env_vars
Resolves: #3788
---
- [ x] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [ x] Is the subject and message clear and concise?
- [ x] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [ x] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ x] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-reque …

[foreman] [foreman_proxy] Add ALL_PROXY and NO_PROXY to collected env_vars

---

sos/report/plugins/containerd.py

[containerd] Collect image and container list

---

sos/report/plugins/openstack_placement.py

This was discovered while verification of 4.7.2 to go into Ubuntu stable release
---

[placement] Obfuscate passwords that have been missed

---

sos/report/plugins/mysql.py

This was discovered while verification of 4.7.2 to go into Ubuntu stable release
---

[mysql] Add obfuscation for password in conf files

---

sos/report/plugins/juju.py

[juju] Add juju commands from juju agents

---

sos/report/plugins/saltmaster.py

AttributeError: 'NoneType' object has no attribute 'get'
Resolves: #3819
---

[saltmaster] handle undefined pillar_roots

---

man/en/sos-report.1

updated the directory location for presets
Resolves: #3826
---

[man] update to the location of presets

---

sos/report/plugins/microk8s.py

[microk8s] Obfuscate token in client.config

---

.cirrus.yml

[tests] Update ubuntu devel to 2504

---

sos/report/plugins/process.py

Add output of 'ps auxfwww'
Resolves: #3706
---

[process] Add output of 'ps auxfwww'

---

sos/report/plugins/processor.py

[processor] Update msr load issue to include focal

---

.cirrus.yml

[cirrus] Update to use image_family

---

sos/report/plugins/sunbeam_hypervisor.py

[sunbeam] Fix obfuscation for masakari and url

---

.cirrus.yml

[cirrus] Update IncludeOnly to check for all man pages

---

sos/report/plugins/foreman_installer.py

Collect Satellite usage metrics file.
Resolves: #3888
no secrets in the file, just various stats
---

[foreman_installer] collect satellite_metrics.yml

---

sos/report/plugins/networking.py

[networking] Update predicate to include Debian

---

sos/report/plugins/microcloud.py

On a single-node:
```
$ sudo microcloud status
Status: WARNING
┃ ! Reliability risk: 3 systems are required for effective fault tolerance
┃ ! No MicroCeph OSDs configured
┌──────┬───────────────┬──────┬─────────────────┬────────────────────────┬────────┐
│ Name │    Address    │ OSDs │ MicroCeph Units │     MicroOVN Units     │ Status │
├──────┼───────────────┼──────┼─────────────────┼────────────────────────┼────────┤
│ sos  │ 172.24.26.120 │  0   │   mds,mgr,mon   │ central,chassis,switch │ ONLINE │
└──────┴───────────────┴──────┴─────────────────┴────────────────────────┴────────┘
```
and on a multi-node:
```
$ sudo microcloud status
Status: HEALTHY
┌────────┬──────────────┬──────┬─────────────────┬────────────────────────┬────────┐
│  Name  │   Address    │ OSDs │ MicroCeph Units │ …
```

[microcloud]: Invoke `microcloud status`

---

sos/report/plugins/ptp.py

[ptp] Capture config files in /etc/sysconfig

---

sos/report/plugins/pulpcore.py

Refer to https://github.com/sosreport/sos/issues/3928
---

[pulpcore] psql: error: FATAL: password authentication failed for user "pulp"

---

.cirrus.yml
.gitignore
debian/changelog
debian/control
debian/copyright
debian/patches/0001-debian-change-tmp-dir-location.patch
debian/patches/0002-debian-do-not-install-LICENSE-README-AUTHORS.patch
debian/patches/series
debian/rules
debian/source/lintian-overrides
debian/tests/control
debian/tests/simple.sh
debian/upstream/metadata
debian/watch

Bringing in most of the relevant changes from downstream build environment
---

[debian][pkg] Update to latest packaging config

---

README.md
tox.ini

Update the doc to use tox for the tests, this ensures the doc is based on the code itself.
---

[docs] Remove nosetest details

---

sos/report/plugins/ceph_common.py

[ceph_common] Obfuscate rgw password in ceph.conf

---

.readthedocs.yaml

Add .readthedocs.yaml to build correctly

---

sos/report/plugins/ubuntu.py

* Use the packages tuple to trigger for plugin
* Remove the if statement to check for package install, this seemed redundant
* Add collection of uaclient.conf
---

[ubuntu] Revamp of plugin

---

sos/report/plugins/opensvc.py

This commit adds the collection of OpenSVC threads during the sosreport.
Signed-off-by: Théo Carpentier theo.carpentier@opensvc.com
---

[opensvc] add the collection of opensvc threads

---

sos/report/plugins/virsh.py

[virsh] Update pkg trigger for Ubuntu/Debian

---

sos/report/plugins/ubuntu.py

[ubuntu] Add extra logs to be collected

---

sos/cleaner/preppers/usernames.py

[clean] Update the last command for obfuscation

---

sos/report/__init__.py

When a value is given it should be preserved rather than changing the case of the value
---

[report] Don't lowercase values by default

---

sos/report/plugins/charmed_mysql.py

This PR is a modification to the Charmed MySQL plugin to add support for the Kubernetes version of this charm. The main difference is what paths are constructed for configuration and logs.
There are also new MySQL queries to gather more data about the state of the database and juju deployment.
An example of the report can be found here: [Charmed MySQL K8s Example report](https://drive.google.com/drive/folders/1lnH0EYvAYWjqAsmMnnrkSDkyoMXpO8V1?usp=sharing)
---

[charmed_mysql] Add Charmed MySQL K8s support

---

sos/report/plugins/leapp.py

[leapp] Update data collected by leapp plugin for RHEL 10

---

sos/report/plugins/redis.py

[redis] Fix path error in redis report collection

---

.cirrus.yml

Update the Fedora images we use for testing, now that newer Fedora image builds, beyond the coreos images that we don't use, are again being published by the Fedora Project.
---

[cirrus] Update Fedora testing images

---

sos/report/plugins/kdump.py

Fadump sysfs

---

sos/report/plugins/openstack_gnocchi.py

The openstack_gnocchi plugin had some simple obfuscations in place, but was not correctly obfuscating the password in the database connection string. This resolves that issue and aligns the obfuscations better with other OpenStack plugins.
---
- [ X] Are any related …

[openstack_gnocchi] added missing obfuscation for db connection

---

sos/report/plugins/subscription_manager.py

---
It is useful to add facts check, so add it.

[subscription_manager] add facts cmd

---

.cirrus.yml

[cirrus] Update latest and dev release

---

sos/report/plugins/fapolicyd.py

---
- add more checks for fapolicyd
```
Fapolicyd CLI Tool
--check-config        Check the daemon config for syntax errors
--check-path          Check files in $PATH against the trustdb for problems
--check-status        Dump the deamon's internal performance statistics
--check-trustdb       Check the trustdb against files on disk for problems
--check-watch_fs      Check watch_fs against currently mounted file systems
-d, --delete-db       Delete the trust database
-D, --dump-db         Dump the trust database contents
```

[fapolicyd] add more checks

---

sos/report/plugins/ssh.py

Capture the output of extended test mode.
Related: RHEL-91218
---

[sshd] Capture sshd -T

---

sos/report/__init__.py
sos/report/plugins/crio.py
sos/report/plugins/docker.py
sos/report/plugins/foreman.py
sos/report/plugins/foreman_proxy.py
sos/report/plugins/podman.py
sos/utilities.py

---
Based on the experience, the proxy would caused lots of issues(e.g cannot register, cannot dnf, curl...etc.), 
it would set in different conf(rhsm.conf, dnf.conf..) for different services, but the system setting(e.g profile, or simply export) also work, currently sos just collect variable name under system plugin, so it would better to collect proxy (e.g. https_proxy=xxx) individually, and make it easy check with `root_symlink`.
```
system-proxy-setting -> sos_commands/system/system_proxy_setting
e.g.
No system proxy settings found.
http_proxy=http://********@proxy.example-test-test.com:8080 …
```

[system] add system proxy check

---

sos/report/plugins/leapp.py

[leapp] add version check

---

man/en/sos.1

Fix two minor issues in man page

---

sos/report/plugins/ovn_central.py
sos/report/plugins/ovn_host.py

[ovn_central]
- Collect /etc/ovn/ovn-northd-db-params.conf
- Collect certificate validity dates
[ovn_host]
- Collect certificate validity dates
---
- [N/A] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?
- [N/A] Are all passwords or private data gathered by this PR [obfuscated](https://github.com/sosreport/sos/wiki/How-to-Write-a-Plugin#how-to-prevent-collecting-passwords)?

[ovn_central,ovn_host] OVN Plugin Updates

---

sos/report/plugins/firewalld.py

---
- [x ] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [x ] Is the subject and message clear and concise?
- [x ] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [x ] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [x ] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved …

[firewalld] Collect runtime and permanent policies

---

sos/report/plugins/networkmanager.py

Capture /var/run/NetworkManager folder
Related: NMT-1074
---

[NetworkManager] Capture /var/run/NetworkManager folder

---

sos/report/plugins/networking.py

Capture /etc/services file
Related: RHEL-105407
---

[networking] Capture /etc/services file

---

sos/report/plugins/snapm.py

Add a plugin for the snapm snapshot manager tool:
https://github.com/snapshotmanager/snapm
Collect:
* /etc/snapm configuration directory
* snapm snapset list
* snapm snapshot list
* snapm plugin list
* snapm schedule list
* snapm -vv --debug=all snapset show
N.b: the /etc/snapm directory and the 'snapm schedule list' command are part of the v0.5.0 release currently in testing. Earlier releases lack these files/subcommands:
https://github.com/snapshotmanager/snapm/releases/tag/v0.5.0
---

[snapm] add new plugin

---

README.md

[doc] Remove reference to legacy sosreport command

---

.cirrus.yml

[cirrus] Add debian-13 to test matrix
